Repository vassalengine/vassal, pull requests merged in 2020-09, with the labels that each got.

#335 3.4.3(?) PieceDefiner uses BrowserHelp
  vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java
Labels: 3.4.3

#315 Docs for VASSAL 3.5 - Flare, etc.
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/ChatLog.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Flare.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/MessageFormat.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/ReportChanges.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/Flare.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/Flare2.png
Labels: 3.5.0

#249 3.5 - 13333 - Better handling of logfile/savefile comments
  vassal-app/src/main/java/VASSAL/build/module/Chatter.java
  vassal-app/src/main/java/VASSAL/build/module/GameState.java
  vassal-app/src/main/java/VASSAL/build/module/metadata/SaveMetaData.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: 3.5.0

#286 3.5 - Javadoc4 - GamePiece, EditablePiece, BasicPiece
  vassal-app/src/main/java/VASSAL/build/Buildable.java
  vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java
  vassal-app/src/main/java/VASSAL/build/module/properties/PropertySource.java
  vassal-app/src/main/java/VASSAL/command/FlareCommand.java
  vassal-app/src/main/java/VASSAL/counters/ActionButton.java
  vassal-app/src/main/java/VASSAL/counters/BasicPiece.java
  vassal-app/src/main/java/VASSAL/counters/Deck.java
  vassal-app/src/main/java/VASSAL/counters/Decorator.java
  vassal-app/src/main/java/VASSAL/counters/EditablePiece.java
  vassal-app/src/main/java/VASSAL/counters/GamePiece.java
  vassal-app/src/main/java/VASSAL/counters/StateMergeable.java
  vassal-app/src/main/java/VASSAL/property/PersistentPropertyContainer.java
Labels: 3.5.0

#261 MouseOverStackViewer show n pieces of decks. Previously would only show 1
  vassal-app/src/main/java/VASSAL/build/module/map/CounterDetailViewer.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: 3.5.0

#317 3.5 - 13414 - Help Button for Preferences Screen
  vassal-app/src/main/java/VASSAL/preferences/PrefsEditor.java
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Preferences.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/ImageTearing.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/Preferences.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/PreferencesChat.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/PreferencesCompatibility.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/PreferencesPersonal.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/PreferencesServer.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/PreferencesSounds.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/PreferencesTurn.png
Labels: 3.5.0

#273 3.5 - 13352 - Title Bar of module should always show most recent Save/Load/Log
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/build/module/BasicLogger.java
  vassal-app/src/main/java/VASSAL/build/module/GameState.java
  vassal-app/src/main/java/VASSAL/build/module/Map.java
  vassal-app/src/main/java/VASSAL/build/module/PredefinedSetup.java
  vassal-app/src/main/java/VASSAL/build/module/WizardSupport.java
  vassal-app/src/main/java/VASSAL/chat/node/NodeClient.java
  vassal-app/src/main/java/VASSAL/chat/ui/SynchAction.java
  vassal-app/src/main/java/VASSAL/launch/EditorWindow.java
  vassal-app/src/main/java/VASSAL/launch/ExtensionEditorWindow.java
  vassal-app/src/main/java/VASSAL/launch/ModuleEditorWindow.java
  vassal-app/src/main/java/VASSAL/launch/Player.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: 3.5.0

#285 3.5 - 13368 - preference to control drag-at-edge-of-map width
  vassal-app/src/main/java/VASSAL/build/module/Map.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: 3.5.0

#303 3.5 - 13415 - MouseoverStackViewer - HTML Compliant! - Holy Actual Crap!
  vassal-app/src/main/java/VASSAL/build/module/Chatter.java
  vassal-app/src/main/java/VASSAL/build/module/map/CounterDetailViewer.java
  vassal-app/src/main/java/VASSAL/tools/image/LabelUtils.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: 3.5.0

#308 3.5 - More i18n Foundation work.
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/RegionGrid.java
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
  vassal-app/src/main/java/VASSAL/configure/EditPropertiesAction.java
  vassal-app/src/main/java/VASSAL/configure/TranslatingStringEnumConfigurer.java
  vassal-app/src/main/java/VASSAL/counters/BasicPiece.java
  vassal-app/src/main/java/VASSAL/counters/Clone.java
  vassal-app/src/main/java/VASSAL/counters/Delete.java
  vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java
  vassal-app/src/main/java/VASSAL/counters/SendToLocation.java
  vassal-app/src/main/java/VASSAL/launch/EditorWindow.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: 3.5.0

#337 3.4.3 - 13435 - Warnings with less-than sign being interpreted as HTML
  vassal-app/src/main/java/VASSAL/build/GameModule.java
Labels: 3.4.3

#336 3.4.3 - Bug 13433 - ObcuredToOthers now returns null in face-down dec…
  vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java
  vassal-app/src/main/java/VASSAL/counters/Deck.java
  vassal-app/src/main/java/VASSAL/counters/GlobalCommand.java
  vassal-app/src/main/java/VASSAL/counters/Properties.java
Labels: 3.4.3

#346 3.4.3 - 13433 - Card draw facing revisited
  vassal-app/src/main/java/VASSAL/counters/GlobalCommand.java
Labels: 3.4.3

#340 Null safety for BoardPicker.currentBoards
  vassal-app/src/main/java/VASSAL/build/module/map/BoardPicker.java
Labels: 3.4.3

#343 13442 Toggle password visibility + 13441 Fix repeated SVG scaling
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/configure/PasswordConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/password/ToggleablePasswordConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/password/ToggleablePasswordFieldPanel.java
  vassal-app/src/main/java/VASSAL/launch/BasicModule.java
  vassal-app/src/main/java/VASSAL/tools/imageop/Op.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
  vassal-app/src/main/resources/icons/scalable/eye-slash.svg
  vassal-app/src/main/resources/icons/scalable/eye.svg
Labels: 3.4.3

#339 3.4.3 - Bug 13434 - Reduce number of deprecated messages. Clarify Text. Log details.
  vassal-app/src/main/java/VASSAL/tools/ProblemDialog.java
  vassal-app/src/main/java/VASSAL/tools/swing/Dialogs.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: 3.4.3

#338 3.4.3 - 13436 - Module Managers for multiple versions of VASSAL can coexist
  vassal-app/src/main/java/VASSAL/Info.java
  vassal-app/src/main/java/VASSAL/launch/ModuleManager.java
  vassal-app/src/main/java/VASSAL/launch/ModuleManagerWindow.java
  vassal-app/src/main/java/VASSAL/tools/BugDialog.java
  vassal-app/src/main/java/VASSAL/tools/BugUtils.java
Labels: 3.4.3

#349 13452: Bundle Java 15
  bootstrap.sh
Labels: 3.4.3

#344 3.5 - Default logfile prompt to on
  vassal-app/src/main/java/VASSAL/build/module/BasicLogger.java
Labels: 3.5.0

#363 3.5 - Allow full-translated strings into TranslatedStringEnum/TranslatingStringEnumConfigurer family as CTOR option
  vassal-app/src/main/java/VASSAL/configure/AutoConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/TranslatableStringEnum.java
  vassal-app/src/main/java/VASSAL/configure/TranslatingStringEnumConfigurer.java
Labels: 3.5.0

#242 Add private server type, remove Jabber server type
  Makefile
  vassal-app/pom.xml
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/chat/AddressBookServerConfigurer.java
  vassal-app/src/main/java/VASSAL/chat/ChatServerConnection.java
  vassal-app/src/main/java/VASSAL/chat/DummyMessageServer.java
  vassal-app/src/main/java/VASSAL/chat/DynamicClient.java
  vassal-app/src/main/java/VASSAL/chat/DynamicClientFactory.java
  vassal-app/src/main/java/VASSAL/chat/InviteCommand.java
  vassal-app/src/main/java/VASSAL/chat/PlayerInfoWindow.java
  vassal-app/src/main/java/VASSAL/chat/ServerAddressBook.java
  vassal-app/src/main/java/VASSAL/chat/ServerConfigurer.java
  vassal-app/src/main/java/VASSAL/chat/jabber/Interceptor.java
  vassal-app/src/main/java/VASSAL/chat/jabber/JabberClient.java
  vassal-app/src/main/java/VASSAL/chat/jabber/JabberClientFactory.java
  vassal-app/src/main/java/VASSAL/chat/jabber/JabberPlayer.java
  vassal-app/src/main/java/VASSAL/chat/jabber/JabberRoom.java
  vassal-app/src/main/java/VASSAL/chat/jabber/JabberStatus.java
  vassal-app/src/main/java/VASSAL/chat/jabber/LockableJabberRoomControls.java
  vassal-app/src/main/java/VASSAL/chat/jabber/ModuleAccountInfo.java
  vassal-app/src/main/java/VASSAL/chat/jabber/PacketProcessor.java
  vassal-app/src/main/java/VASSAL/chat/node/NodeClient.java
  vassal-app/src/main/java/VASSAL/chat/node/NodeClientFactory.java
  vassal-app/src/main/java/VASSAL/chat/node/NodeHybridClient.java
  vassal-app/src/main/java/VASSAL/chat/node/OfficialNodeClient.java
  vassal-app/src/main/java/VASSAL/chat/node/OfficialNodeClientFactory.java
  vassal-app/src/main/java/VASSAL/chat/node/PrivateNodeClient.java
  vassal-app/src/main/java/VASSAL/chat/node/PrivateNodeClientFactory.java
  vassal-app/src/main/java/VASSAL/chat/node/SocketNodeClient.java
  vassal-app/src/main/java/VASSAL/chat/peer2peer/ClientTest.java
  vassal-app/src/main/java/VASSAL/chat/peer2peer/DirectPeerPool.java
  vassal-app/src/main/java/VASSAL/chat/peer2peer/EchoClient.java
  vassal-app/src/main/java/VASSAL/chat/peer2peer/P2PClient.java
  vassal-app/src/main/java/VASSAL/chat/peer2peer/P2PClientFactory.java
  vassal-app/src/main/java/VASSAL/chat/peer2peer/TextClient.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
  vassal-app/src/test/resources/clirr-ignored-differences.xml
Labels: 3.5.0

#369 3.4.4-13458-Allow floats to be compared in Beanshell. (Regression).
  vassal-app/src/main/java/VASSAL/script/ExpressionInterpreter.java
  vassal-app/src/test/java/VASSAL/script/expression/PropertyMatchExpressionTest.java
Labels: 3.4.4
