Repository vassalengine/vassal, pull requests merged in 2020-10, with the labels that each got.

#378 3.4.4-13461-Always initialise Deck when New/Load game.
  vassal-app/src/main/java/VASSAL/counters/Deck.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: 3.4.4

#380 3.4.4-13471-Fix bug in handling null property values in expressions. …
  vassal-app/src/main/java/VASSAL/build/BadDataReport.java
  vassal-app/src/main/java/VASSAL/counters/CalculatedProperty.java
  vassal-app/src/main/java/VASSAL/script/ExpressionInterpreter.java
  vassal-app/src/main/java/VASSAL/tools/ErrorDialog.java
Labels: 3.4.4

#385 13469: Temp file cleanup
  vassal-app/src/main/java/VASSAL/Info.java
  vassal-app/src/main/java/VASSAL/build/module/BasicCommandEncoder.java
  vassal-app/src/main/java/VASSAL/build/module/ExtensionsManager.java
  vassal-app/src/main/java/VASSAL/build/module/documentation/BrowserHelpFile.java
  vassal-app/src/main/java/VASSAL/i18n/Resources.java
  vassal-app/src/main/java/VASSAL/i18n/TranslateVassalWindow.java
  vassal-app/src/main/java/VASSAL/launch/AbstractLaunchAction.java
  vassal-app/src/main/java/VASSAL/launch/BasicModule.java
  vassal-app/src/main/java/VASSAL/launch/Config.java
  vassal-app/src/main/java/VASSAL/launch/CreateModuleAction.java
  vassal-app/src/main/java/VASSAL/launch/DummyConfig.java
  vassal-app/src/main/java/VASSAL/launch/EditExtensionAction.java
  vassal-app/src/main/java/VASSAL/launch/EditModuleAction.java
  vassal-app/src/main/java/VASSAL/launch/Editor.java
  vassal-app/src/main/java/VASSAL/launch/Launcher.java
  vassal-app/src/main/java/VASSAL/launch/ModuleManager.java
  vassal-app/src/main/java/VASSAL/launch/ModuleManagerWindow.java
  vassal-app/src/main/java/VASSAL/launch/NewExtensionAction.java
  vassal-app/src/main/java/VASSAL/launch/Player.java
  vassal-app/src/main/java/VASSAL/launch/StandardConfig.java
  vassal-app/src/main/java/VASSAL/launch/TilingHandler.java
  vassal-app/src/main/java/VASSAL/tools/ArchiveWriter.java
  vassal-app/src/main/java/VASSAL/tools/ComponentSplitter.java
  vassal-app/src/main/java/VASSAL/tools/ZipUpdater.java
  vassal-app/src/main/java/VASSAL/tools/image/ImageUtils.java
  vassal-app/src/main/java/VASSAL/tools/image/tilecache/ImageToTiles.java
  vassal-app/src/main/java/VASSAL/tools/image/tilecache/ZipFileImageTiler.java
  vassal-app/src/main/java/VASSAL/tools/imports/ImportAction.java
  vassal-app/src/main/java/VASSAL/tools/imports/adc2/MapBoard.java
  vassal-app/src/main/java/VASSAL/tools/io/ZipArchive.java
  vassal-app/src/main/java/VASSAL/tools/swing/SwingUtils.java
  vassal-app/src/test/java/VASSAL/tools/io/ProcessCallableTest.java
Labels: 3.4.4

#387 3.5 - 13486 - Backspacing in NamedHotKeyConfigurer will no longer shift focus
  vassal-app/src/main/java/VASSAL/configure/NamedHotKeyConfigurer.java
Labels: 3.4.4, 3.5.0

#390 3.5 - 13495 - loading saved game from wizard remembers default name appropriately
  vassal-app/src/main/java/VASSAL/build/module/WizardSupport.java
Labels: 3.5.0

#389 3.5 - 13494 - Expose versions and module strings to module as properties
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: 3.5.0

#391 3.5 - 1804 - Sound "Mute All" preference
  vassal-app/src/main/java/VASSAL/build/module/GlobalOptions.java
  vassal-app/src/main/java/VASSAL/chat/SoundEncoder.java
  vassal-app/src/main/java/VASSAL/command/PlayAudioClipCommand.java
  vassal-app/src/main/java/VASSAL/counters/PlaySound.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: 3.5.0

#398 3.4.6-13503 At-Start Stacks/Decks created in wrong place if <any> board used with Map edge buffers.
  vassal-app/src/main/java/VASSAL/build/module/map/SetupStack.java
Labels: 3.4.6

#395 13467, 13469: HTML img elements refering to images in module hold it open
  vassal-app/src/main/java/VASSAL/build/module/Chatter.java
  vassal-app/src/main/java/VASSAL/build/widget/HtmlChart.java
  vassal-app/src/main/java/VASSAL/tools/swing/DataArchiveHTMLEditorKit.java
  vassal-app/src/main/java/VASSAL/tools/swing/HTMLWindowHelper.java
Labels: 3.4.6

#397 3.4.6 - 12576 and 13456 - setup stack grid locations for 'any' board stacks
  vassal-app/src/main/java/VASSAL/build/module/map/SetupStack.java
Labels: 3.4.6

#399 3.4.6 - 13505 - Deck band select fix
  vassal-app/src/main/java/VASSAL/build/module/map/KeyBufferer.java
  vassal-app/src/main/java/VASSAL/counters/PieceFinder.java
Labels: 3.4.6

#396 13504 - Simpler way to display a PDF file (e.g. a rulebook) from Help menu
  vassal-app/src/main/java/VASSAL/build/module/Documentation.java
  vassal-app/src/main/java/VASSAL/build/module/documentation/BrowserPDFFile.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/HelpMenu.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/HelpFilePDF.png
Labels: 3.5.0

#403 13508: NPE in GamePieceOpImpl.getTileIndices()
  vassal-app/src/main/java/VASSAL/tools/imageop/AbstractTileOpImpl.java
Labels: 3.4.6

#356 3.5 - Trait i18n, config cleanup, for BasicPiece, Clone, Delete, Text Label. Configurer changes and tests. Stage 1
  vassal-app/src/main/java/VASSAL/build/module/map/DeckGlobalKeyCommand.java
  vassal-app/src/main/java/VASSAL/build/module/map/MassKeyCommand.java
  vassal-app/src/main/java/VASSAL/build/module/properties/GlobalProperty.java
  vassal-app/src/main/java/VASSAL/configure/AutoConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/BeanShellFunctionMenu.java
  vassal-app/src/main/java/VASSAL/configure/BooleanConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/ColorConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/Configurer.java
  vassal-app/src/main/java/VASSAL/configure/ConfigurerLayout.java
  vassal-app/src/main/java/VASSAL/configure/ConfigurerPanel.java
  vassal-app/src/main/java/VASSAL/configure/FormattedStringConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/IntConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/NamedHotKeyConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/PropertiesWindow.java
  vassal-app/src/main/java/VASSAL/configure/PropertyExpressionConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/StringConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/TranslatingStringEnumConfigurer.java
  vassal-app/src/main/java/VASSAL/counters/ActionButton.java
  vassal-app/src/main/java/VASSAL/counters/AreaOfEffect.java
  vassal-app/src/main/java/VASSAL/counters/BasicPiece.java
  vassal-app/src/main/java/VASSAL/counters/Clone.java
  vassal-app/src/main/java/VASSAL/counters/CounterGlobalKeyCommand.java
  vassal-app/src/main/java/VASSAL/counters/Decorator.java
  vassal-app/src/main/java/VASSAL/counters/Delete.java
  vassal-app/src/main/java/VASSAL/counters/KeySpecifier.java
  vassal-app/src/main/java/VASSAL/counters/Labeler.java
  vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java
  vassal-app/src/main/java/VASSAL/counters/SendToLocation.java
  vassal-app/src/main/java/VASSAL/counters/TraitConfigPanel.java
  vassal-app/src/main/java/VASSAL/counters/TraitLayout.java
  vassal-app/src/main/java/VASSAL/counters/UsePrototype.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-app/src/test/java/VASSAL/configure/IntConfigurerTest.java
  vassal-app/src/test/java/VASSAL/configure/NamedHotKeyConfigurerTest.java
  vassal-app/src/test/java/VASSAL/configure/StringConfigurerTest.java
  vassal-app/src/test/java/VASSAL/configure/TranslatingStringEnumConfigurerTest.java
  vassal-app/src/test/java/VASSAL/counters/ActionButtonTest.java
  vassal-app/src/test/java/VASSAL/counters/AreaOfEffectTest.java
  vassal-app/src/test/java/VASSAL/counters/BasicPieceTest.java
  vassal-app/src/test/java/VASSAL/counters/CloneTest.java
  vassal-app/src/test/java/VASSAL/counters/CounterGlobalKeyCommandTest.java
  vassal-app/src/test/java/VASSAL/counters/DecoratorTest.java
  vassal-app/src/test/java/VASSAL/counters/DeleteTest.java
  vassal-app/src/test/java/VASSAL/counters/LabelerTest.java
  vassal-app/src/test/java/VASSAL/counters/UsePrototypeTest.java
  vassal-app/src/test/resources/clirr-ignored-differences.xml
Labels: 3.5.0

#404 3.5 - 13509 - Editor's Save As complains about right filename if it fails. Also confirms success and shows filename then too.
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/build/module/ModuleExtension.java
  vassal-app/src/main/java/VASSAL/tools/ArchiveWriter.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: 3.5.0

#416 Don't used deprecated Info.getScreenBounds()
  vassal-app/src/main/java/VASSAL/build/GameModule.java
Labels: 3.5.0

#433 3.4.7 - 13520 - Command+click for Mac deselect
  vassal-app/src/main/java/VASSAL/tools/swing/SwingUtils.java
Labels: 3.4.7

#435 3.5-Fix POG Slow startup issue
  vassal-app/src/main/java/VASSAL/configure/Configurer.java
  vassal-app/src/main/java/VASSAL/configure/ListConfigurer.java
  vassal-app/src/main/java/VASSAL/counters/DynamicProperty.java
  vassal-app/src/test/java/VASSAL/counters/DecoratorTest.java
  vassal-app/src/test/java/VASSAL/counters/DynamicPropertyTest.java
Labels: 3.5.0

#436 13489: Apply device scale factor to system drag ghost
  vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java
Labels: 3.4.7

#439 13450-Marker & Menu Separator
  vassal-app/src/main/java/VASSAL/counters/KeyBuffer.java
  vassal-app/src/main/java/VASSAL/counters/KeyCommand.java
  vassal-app/src/main/java/VASSAL/counters/KeyCommandSubMenu.java
  vassal-app/src/main/java/VASSAL/counters/Marker.java
  vassal-app/src/main/java/VASSAL/counters/MenuSeparator.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-app/src/test/java/VASSAL/counters/MarkerTest.java
  vassal-app/src/test/java/VASSAL/counters/MenuSeparatorTest.java
Labels: 3.5.0

#440 13525: Check for NFD filenames munged by HFS+
  vassal-app/src/main/java/VASSAL/tools/DataArchive.java
Labels: 3.4.7

#443 13537 - Remove unnecessary initial heap preference
  vassal-app/src/main/java/VASSAL/build/module/GlobalOptions.java
  vassal-app/src/main/java/VASSAL/launch/AbstractLaunchAction.java
  vassal-app/src/main/java/VASSAL/launch/ModuleManager.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
  vassal-app/src/test/resources/clirr-ignored-differences.xml
Labels: 3.5.0

#442 3.5-13450-Ongoing-Improved NamedHotKeyConfigurer
  vassal-app/src/main/java/VASSAL/configure/BooleanConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/HintTextField.java
  vassal-app/src/main/java/VASSAL/configure/NamedHotKeyConfigurer.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-app/src/test/java/VASSAL/configure/NamedHotKeyConfigurerTest.java
Labels: 3.5.0

#452 3.4.7 - 13540 - Mac uses Command as modifier key for various grid-resizing, etc.
  vassal-app/src/main/java/VASSAL/build/module/map/SetupStack.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/GridEditor.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/RegionGrid.java
  vassal-app/src/main/java/VASSAL/tools/swing/SwingUtils.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: 3.4.7

#456 3.4.7-13542 Fix Moved Fixed Distance / Rotator interaction
  vassal-app/src/main/java/VASSAL/counters/Translate.java
Labels: 3.4.7

#457 M, N & O traits, all remaining non-trait code in counters, test improvements, small cleanups.
  vassal-app/src/main/java/VASSAL/configure/IconConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/NamedHotKeyConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/PieceAccessConfigurer.java
  vassal-app/src/main/java/VASSAL/counters/BooleanAndPieceFilter.java
  vassal-app/src/main/java/VASSAL/counters/BooleanOrPieceFilter.java
  vassal-app/src/main/java/VASSAL/counters/BoundsTracker.java
  vassal-app/src/main/java/VASSAL/counters/ImagePicker.java
  vassal-app/src/main/java/VASSAL/counters/Immobilized.java
  vassal-app/src/main/java/VASSAL/counters/Labeler.java
  vassal-app/src/main/java/VASSAL/counters/MovementMarkable.java
  vassal-app/src/main/java/VASSAL/counters/MultiImagePicker.java
  vassal-app/src/main/java/VASSAL/counters/NonRectangular.java
  vassal-app/src/main/java/VASSAL/counters/Obscurable.java
  vassal-app/src/main/java/VASSAL/counters/PieceCloner.java
  vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java
  vassal-app/src/main/java/VASSAL/counters/PieceEditor.java
  vassal-app/src/main/java/VASSAL/counters/PieceFilter.java
  vassal-app/src/main/java/VASSAL/counters/PieceFinder.java
  vassal-app/src/main/java/VASSAL/counters/PieceVisitor.java
  vassal-app/src/main/java/VASSAL/counters/PieceVisitorDispatcher.java
  vassal-app/src/main/java/VASSAL/counters/Pivot.java
  vassal-app/src/main/java/VASSAL/counters/Properties.java
  vassal-app/src/main/java/VASSAL/counters/PropertiesPieceFilter.java
  vassal-app/src/main/java/VASSAL/counters/PropertyExporter.java
  vassal-app/src/main/java/VASSAL/counters/RangeFilter.java
  vassal-app/src/main/java/VASSAL/counters/SpecifiedSideAccess.java
  vassal-app/src/main/java/VASSAL/counters/Stack.java
  vassal-app/src/main/java/VASSAL/counters/Translate.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
  vassal-app/src/test/java/VASSAL/counters/DecoratorTest.java
  vassal-app/src/test/java/VASSAL/counters/MovementMarkableTest.java
  vassal-app/src/test/java/VASSAL/counters/NonRectangularTest.java
  vassal-app/src/test/java/VASSAL/counters/ObscurableTest.java
  vassal-app/src/test/java/VASSAL/counters/TranslateTest.java
Labels: 3.5.0

#460 PMD + cleanup
  vassal-app/src/main/java/VASSAL/build/AbstractBuildable.java
  vassal-app/src/main/java/VASSAL/build/module/BasicCommandEncoder.java
  vassal-app/src/main/java/VASSAL/build/module/ChessClockControl.java
  vassal-app/src/main/java/VASSAL/build/module/GlobalOptions.java
  vassal-app/src/main/java/VASSAL/build/module/Inventory.java
  vassal-app/src/main/java/VASSAL/build/module/Map.java
  vassal-app/src/main/java/VASSAL/build/module/PrivateMap.java
  vassal-app/src/main/java/VASSAL/build/module/chessclockcontrol/ChessClock.java
  vassal-app/src/main/java/VASSAL/build/module/documentation/DialogHelpWindow.java
  vassal-app/src/main/java/VASSAL/build/module/documentation/HelpWindow.java
  vassal-app/src/main/java/VASSAL/build/module/gamepieceimage/ColorSwatchConfigurer.java
  vassal-app/src/main/java/VASSAL/build/module/gamepieceimage/InstanceConfigurer.java
  vassal-app/src/main/java/VASSAL/build/module/gamepieceimage/LayoutConfigurer.java
  vassal-app/src/main/java/VASSAL/build/module/map/Flare.java
  vassal-app/src/main/java/VASSAL/build/module/map/GlobalMap.java
  vassal-app/src/main/java/VASSAL/build/module/map/HidePiecesButton.java
  vassal-app/src/main/java/VASSAL/build/module/map/MovementReporter.java
  vassal-app/src/main/java/VASSAL/build/module/noteswindow/PrivateText.java
  vassal-app/src/main/java/VASSAL/build/module/noteswindow/SecretNote.java
  vassal-app/src/main/java/VASSAL/build/widget/HtmlChart.java
  vassal-app/src/main/java/VASSAL/build/widget/PieceSlot.java
  vassal-app/src/main/java/VASSAL/chat/DummyMessageServer.java
  vassal-app/src/main/java/VASSAL/chat/PrivateChatManager.java
  vassal-app/src/main/java/VASSAL/chat/ServerAddressBook.java
  vassal-app/src/main/java/VASSAL/chat/ServerStatus.java
  vassal-app/src/main/java/VASSAL/chat/SimplePlayer.java
  vassal-app/src/main/java/VASSAL/chat/SimpleRoom.java
  vassal-app/src/main/java/VASSAL/chat/node/Node.java
  vassal-app/src/main/java/VASSAL/chat/node/NodeClientFactory.java
  vassal-app/src/main/java/VASSAL/chat/node/NodePlayer.java
  vassal-app/src/main/java/VASSAL/chat/node/PlayerNode.java
  vassal-app/src/main/java/VASSAL/chat/peer2peer/DirectPeerPool.java
  vassal-app/src/main/java/VASSAL/chat/peer2peer/P2PPlayer.java
  vassal-app/src/main/java/VASSAL/chat/peer2peer/UnitTest.java
  vassal-app/src/main/java/VASSAL/command/Command.java
  vassal-app/src/main/java/VASSAL/command/FlareCommand.java
  vassal-app/src/main/java/VASSAL/command/SetPersistentPropertyCommand.java
  vassal-app/src/main/java/VASSAL/configure/PropertyExpression.java
  vassal-app/src/main/java/VASSAL/configure/TableConfigurer.java
  vassal-app/src/main/java/VASSAL/counters/BasicPiece.java
  vassal-app/src/main/java/VASSAL/counters/Deck.java
  vassal-app/src/main/java/VASSAL/counters/Decorator.java
  vassal-app/src/main/java/VASSAL/counters/Deselect.java
  vassal-app/src/main/java/VASSAL/counters/Labeler.java
  vassal-app/src/main/java/VASSAL/counters/MassPieceLoader.java
  vassal-app/src/main/java/VASSAL/counters/PropertiesPieceFilter.java
  vassal-app/src/main/java/VASSAL/counters/ReturnToDeck.java
  vassal-app/src/main/java/VASSAL/counters/Stack.java
  vassal-app/src/main/java/VASSAL/i18n/TranslateWindow.java
  vassal-app/src/main/java/VASSAL/launch/DummyConfig.java
  vassal-app/src/main/java/VASSAL/launch/EditorWindow.java
  vassal-app/src/main/java/VASSAL/preferences/PrefsEditor.java
  vassal-app/src/main/java/VASSAL/script/ExpressionInterpreter.java
  vassal-app/src/main/java/VASSAL/search/AbstractImageFinder.java
  vassal-app/src/main/java/VASSAL/tools/PropertiesEncoder.java
  vassal-app/src/main/java/VASSAL/tools/WrapLayout.java
  vassal-app/src/main/java/VASSAL/tools/concurrent/ConcurrentSoftHashMap.java
  vassal-app/src/main/java/VASSAL/tools/icon/IconFamily.java
  vassal-app/src/main/java/VASSAL/tools/version/VersionUtils.java
  vassal-app/src/test/resources/pmd.xml
Labels: 3.5.0

#408 13522 - Global Key Command performance improvements
  vassal-app/src/main/java/VASSAL/build/module/GlobalKeyCommand.java
  vassal-app/src/main/java/VASSAL/build/module/map/DeckGlobalKeyCommand.java
  vassal-app/src/main/java/VASSAL/build/module/map/MassKeyCommand.java
  vassal-app/src/main/java/VASSAL/configure/FormattedExpressionConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/GlobalCommandTargetConfigurer.java
  vassal-app/src/main/java/VASSAL/counters/CounterGlobalKeyCommand.java
  vassal-app/src/main/java/VASSAL/counters/Deck.java
  vassal-app/src/main/java/VASSAL/counters/GlobalCommand.java
  vassal-app/src/main/java/VASSAL/counters/GlobalCommandTarget.java
  vassal-app/src/main/java/VASSAL/counters/PieceFilter.java
  vassal-app/src/main/java/VASSAL/script/expression/Expression.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-app/src/test/java/VASSAL/counters/CounterGlobalKeyCommandSerializeTest.java
  vassal-app/src/test/java/VASSAL/counters/CounterGlobalKeyCommandTest.java
  vassal-app/src/test/java/VASSAL/counters/GlobalCommandTargetTest.java
  vassal-app/src/test/resources/clirr-ignored-differences.xml
Labels: 3.5.0

#463 3.4.7 13546 Change backup Resource directory from temp folder to base folder
  vassal-app/src/main/java/VASSAL/i18n/Resources.java
Labels: 3.4.7

#466 3.4.7 13524 Fix Masked Card reporting by Report State trait
  vassal-app/src/main/java/VASSAL/counters/PropertyExporter.java
Labels: 3.4.7

#474 3.5 13450 Ongoing - R traits done plus cleanups and minor Configurer improvements
  vassal-app/src/main/java/VASSAL/configure/NamedHotKeyConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/NamedKeyStrokeArrayConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/PlayerIdFormattedStringConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/PropertyExpressionConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/StringArrayConfigurer.java
  vassal-app/src/main/java/VASSAL/counters/Embellishment.java
  vassal-app/src/main/java/VASSAL/counters/FreeRotator.java
  vassal-app/src/main/java/VASSAL/counters/ReportState.java
  vassal-app/src/main/java/VASSAL/counters/RestrictCommands.java
  vassal-app/src/main/java/VASSAL/counters/Restricted.java
  vassal-app/src/main/java/VASSAL/counters/ReturnToDeck.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-app/src/test/java/VASSAL/counters/ReportStateTest.java
  vassal-app/src/test/java/VASSAL/counters/RestrictCommandsTest.java
  vassal-app/src/test/java/VASSAL/counters/RestrictedTest.java
  vassal-app/src/test/java/VASSAL/counters/ReturnToDeckTest.java
  vassal-app/src/test/resources/clirr-ignored-differences.xml
Labels: 3.5.0

#472 13547: Don't raise a bug dialog on failure to read an MP3
  vassal-app/src/main/java/VASSAL/tools/Mp3AudioClip.java
Labels: 3.4.7

#482 13560: Don't register mouse listeners from ActionButton.draw()
  vassal-app/src/main/java/VASSAL/build/module/Map.java
  vassal-app/src/main/java/VASSAL/command/MovePiece.java
  vassal-app/src/main/java/VASSAL/counters/ActionButton.java
Labels: 3.4.8

#510 3.5 Finish Custom Configurers. Increase gapy. Tidy ups
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java
  vassal-app/src/main/java/VASSAL/build/module/PrototypeDefinition.java
  vassal-app/src/main/java/VASSAL/build/module/gamepieceimage/FontConfigurer.java
  vassal-app/src/main/java/VASSAL/build/module/gamepieceimage/OutlineFont.java
  vassal-app/src/main/java/VASSAL/build/module/map/BoardPicker.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/Zone.java
  vassal-app/src/main/java/VASSAL/chat/ServerAddressBook.java
  vassal-app/src/main/java/VASSAL/configure/BooleanConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/ColorConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/Configurer.java
  vassal-app/src/main/java/VASSAL/configure/ConfigurerLayout.java
  vassal-app/src/main/java/VASSAL/configure/FontConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/IconConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/ListConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/SoundConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/StringArrayConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/StringConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/StringEnumConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/TranslatingStringEnumConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/password/ToggleablePasswordConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/password/ToggleablePasswordFieldPanel.java
  vassal-app/src/main/java/VASSAL/counters/DynamicProperty.java
  vassal-app/src/main/java/VASSAL/i18n/LocaleConfigurer.java
  vassal-app/src/main/java/VASSAL/preferences/PrefsEditor.java
  vassal-app/src/main/java/VASSAL/tools/UsernameAndPasswordDialog.java
  vassal-app/src/test/resources/clirr-ignored-differences.xml
Labels: 3.5.0

#517 13572: Stop looking for ancient prefs files written by 3.2.7 or earlier
  vassal-app/src/main/java/VASSAL/launch/ModuleManager.java
Labels: 3.4.8

#518 Module Manager Cleanup
  vassal-app/src/main/java/VASSAL/launch/DummyConfig.java
  vassal-app/src/main/java/VASSAL/launch/LaunchRequestHandler.java
  vassal-app/src/main/java/VASSAL/launch/ModuleManager.java
  vassal-app/src/main/java/VASSAL/launch/ModuleManagerMenuManager.java
  vassal-app/src/main/java/VASSAL/launch/ModuleManagerSocketListener.java
  vassal-app/src/test/java/VASSAL/InfoTest.java
Labels: 3.5.0

#505 3.5 - A SPECIAL PRESENT FOR BRENT! - Fast Match Comparison Modes
  vassal-app/src/main/java/VASSAL/configure/GlobalCommandTargetConfigurer.java
  vassal-app/src/main/java/VASSAL/counters/GlobalCommand.java
  vassal-app/src/main/java/VASSAL/counters/GlobalCommandTarget.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: 3.5.0

#519 Cleanup
  Makefile
  vassal-app/src/main/java/VASSAL/build/module/ObscurableOptions.java
  vassal-app/src/main/java/VASSAL/build/module/PrivateMap.java
  vassal-app/src/main/java/VASSAL/build/module/gamepieceimage/StringEnumConfigurer.java
  vassal-app/src/main/java/VASSAL/build/module/map/MassKeyCommand.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/Board.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/HexGrid.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/MapGrid.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/ZonedGrid.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/GridNumbering.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/HexGridNumbering.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/RegularGridNumbering.java
  vassal-app/src/main/java/VASSAL/chat/peer2peer/ClientTest.java
  vassal-app/src/main/java/VASSAL/chat/peer2peer/EchoClient.java
  vassal-app/src/main/java/VASSAL/chat/peer2peer/TextClient.java
  vassal-app/src/main/java/VASSAL/counters/ActionButton.java
  vassal-app/src/main/java/VASSAL/counters/MovementMarkable.java
  vassal-app/src/main/java/VASSAL/counters/ReportState.java
  vassal-app/src/main/java/VASSAL/counters/Restricted.java
  vassal-app/src/main/java/VASSAL/tools/Sort.java
  vassal-app/src/main/java/VASSAL/tools/io/ZipArchive.java
Labels: 3.5.0

#516 3.5 - Some remaining loc cleanup
  vassal-app/src/main/java/VASSAL/counters/MassPieceLoader.java
  vassal-app/src/main/java/VASSAL/counters/PlaySound.java
  vassal-app/src/main/java/VASSAL/counters/PropertySheet.java
  vassal-app/src/main/java/VASSAL/counters/SimplePieceEditor.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: 3.5.0

#525 Produce SHA256 hashes for releases
  Makefile
Labels: 3.4.8
