Repository vassalengine/vassal, pull requests merged in 2020-11, with the labels that each got.

#528 3.5 - Flare doc improvements/updates
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Flare.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Map.adoc
Labels: 3.5.0

#512 3.4.8 - 13567 - if module write fails, make it easier to actually find your tmp file
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/tools/ErrorDialog.java
  vassal-app/src/main/java/VASSAL/tools/ProblemDialog.java
  vassal-app/src/main/java/VASSAL/tools/WriteErrorDialog.java
  vassal-app/src/main/java/VASSAL/tools/io/ZipArchive.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: 3.4.8

#527 Chess clock doc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/ChessClock.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/GameModule.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/ChessClock.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/ChessClockControl.png
Labels: 3.5.0

#526 3.5 - Clean up a few GKC configurers and new Docs for new Global Key Command stuff
  vassal-app/src/main/java/VASSAL/build/module/map/DeckGlobalKeyCommand.java
  vassal-app/src/main/java/VASSAL/build/module/map/MassKeyCommand.java
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/ActionButton.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/CalculatedProperty.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/DeckGlobalKeyCommand.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Expression.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/GlobalKeyCommand.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Inventory.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Map.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/PropertyMarker.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/PropertyMatchExpression.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/SetGlobalProperty.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/CounterGlobalKeyCommand.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/CounterGlobalKeyCommand2.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/CounterGlobalKeyCommand3.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/DeckGlobalKeyCommand.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/GlobalKeyCommand.png
Labels: 3.5.0

#523 13431: Use ImageOp for caching drawing of grids and grid numbering
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/Board.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/GridOp.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/SolidColorOp.java
Labels: 3.4.8

#531 3.4.8 - 13577 - Stacks properly restore their visual 'layer' level when saved/restored
  vassal-app/src/main/java/VASSAL/build/module/map/LayeredPieceCollection.java
  vassal-app/src/main/java/VASSAL/counters/Stack.java
Labels: 3.4.8

#537 Javadoc brain dump for Stacks and Layers while I have it paged into my brain
  vassal-app/src/main/java/VASSAL/build/module/GameState.java
  vassal-app/src/main/java/VASSAL/build/module/Map.java
  vassal-app/src/main/java/VASSAL/build/module/map/CompoundPieceCollection.java
  vassal-app/src/main/java/VASSAL/build/module/map/DefaultPieceCollection.java
  vassal-app/src/main/java/VASSAL/build/module/map/KeyBufferer.java
  vassal-app/src/main/java/VASSAL/build/module/map/LayeredPieceCollection.java
  vassal-app/src/main/java/VASSAL/build/module/map/MovementReporter.java
  vassal-app/src/main/java/VASSAL/build/module/map/PieceCollection.java
  vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java
  vassal-app/src/main/java/VASSAL/build/module/map/SimplePieceCollection.java
  vassal-app/src/main/java/VASSAL/build/module/map/StackExpander.java
  vassal-app/src/main/java/VASSAL/build/module/map/StackMetrics.java
  vassal-app/src/main/java/VASSAL/command/MovePiece.java
  vassal-app/src/main/java/VASSAL/counters/Deck.java
  vassal-app/src/main/java/VASSAL/counters/PieceFinder.java
  vassal-app/src/main/java/VASSAL/counters/Stack.java
  vassal-app/src/main/java/VASSAL/counters/Translate.java
Labels: 3.5.0

#542 3.5 - Javadoc and 'mild refactor' of GlobalOptions
  vassal-app/src/main/java/VASSAL/build/module/BasicLogger.java
  vassal-app/src/main/java/VASSAL/build/module/GlobalOptions.java
  vassal-app/src/main/java/VASSAL/preferences/Prefs.java
Labels: 3.5.0

#540 3.5 - JAVADOC - PieceMover javadoc improvements and cleanup
  vassal-app/src/main/java/VASSAL/build/module/Map.java
  vassal-app/src/main/java/VASSAL/build/module/map/KeyBufferer.java
  vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java
  vassal-app/src/main/java/VASSAL/counters/KeyBuffer.java
Labels: 3.5.0

#541 3.5 - Belatedly make GKC's use AbstractToolbarItem now that we've come to a more stable point.
  vassal-app/src/main/java/VASSAL/build/AbstractToolbarItem.java
  vassal-app/src/main/java/VASSAL/build/module/map/DeckGlobalKeyCommand.java
  vassal-app/src/main/java/VASSAL/build/module/map/LOS_Thread.java
  vassal-app/src/main/java/VASSAL/build/module/map/MassKeyCommand.java
Labels: 3.5.0

#543 13379 - Mass Piece Loader - Bug fixes
  vassal-app/src/main/java/VASSAL/counters/Embellishment.java
  vassal-app/src/main/java/VASSAL/counters/MassPieceLoader.java
Labels: 3.4.8

#535 Bug 13573 - Allow $$ variables to be used in Sum and Count functions in any expression (not just GKC's)
  vassal-app/src/main/java/VASSAL/script/ExpressionInterpreter.java
Labels: 3.4.8

#536 Bug 13574 - Fix issue reporting on oldXXXXXX properties in ReportState
  vassal-app/src/main/java/VASSAL/counters/BasicPiece.java
  vassal-app/src/main/java/VASSAL/counters/Decorator.java
  vassal-app/src/main/java/VASSAL/counters/PropertyExporter.java
Labels: 3.4.8

#545 3.5 - 13593 - Global Prefs REALLY auto-write, and new boolean pref for "remember screen height"
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/build/module/Map.java
  vassal-app/src/main/java/VASSAL/preferences/GlobalPrefs.java
  vassal-app/src/main/java/VASSAL/preferences/Prefs.java
  vassal-app/src/main/java/VASSAL/preferences/PrefsEditor.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: 3.5.0

#547 3.5 - Fix the Chatter/Palette docking order problem
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/build/module/PieceWindow.java
Labels: 3.5.0

#546 3.5 mass piece load configurer update
  vassal-app/src/main/java/VASSAL/configure/FileConfigurer.java
  vassal-app/src/main/java/VASSAL/counters/MassPieceLoader.java
  vassal-app/src/test/resources/clirr-ignored-differences.xml
Labels: 3.5.0

#550 13598: Cobble source tiles for GridOp tiles
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/GridOp.java
Labels: 3.4.9

#552 3.5 - Fix Wizard config page layouts
  vassal-app/src/main/java/VASSAL/build/module/WizardSupport.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: 3.5.0

#556 13608: Let the GridEditor bypass composing of grids onto board tiles
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/Board.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/GridEditor.java
Labels: 3.4.9

#557 13608: Fix grid editor scrolling
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/GridEditor.java
Labels: 3.4.9

#558 13616: 0 bytes RAM is bogus, use fallback in that case
  vassal-app/src/main/java/VASSAL/launch/AbstractLaunchAction.java
  vassal-app/src/main/java/VASSAL/tools/lang/MemoryUtils.java
Labels: 3.4.9

#560 Deprecated VASSAL.tools.io.IOUtils
  vassal-app/src/main/java/VASSAL/build/module/GameState.java
  vassal-app/src/main/java/VASSAL/build/module/documentation/BrowserHelpFile.java
  vassal-app/src/main/java/VASSAL/build/widget/HtmlChart.java
  vassal-app/src/main/java/VASSAL/chat/Compressor.java
  vassal-app/src/main/java/VASSAL/counters/Deck.java
  vassal-app/src/main/java/VASSAL/launch/ModuleManager.java
  vassal-app/src/main/java/VASSAL/tools/ArchiveWriter.java
  vassal-app/src/main/java/VASSAL/tools/BugUtils.java
  vassal-app/src/main/java/VASSAL/tools/DataArchive.java
  vassal-app/src/main/java/VASSAL/tools/HTTPPostBuilder.java
  vassal-app/src/main/java/VASSAL/tools/ZipUpdater.java
  vassal-app/src/main/java/VASSAL/tools/image/FileImageTypeConverter.java
  vassal-app/src/main/java/VASSAL/tools/image/tilecache/TileUtils.java
  vassal-app/src/main/java/VASSAL/tools/io/DeobfuscatingInputStream.java
  vassal-app/src/main/java/VASSAL/tools/io/IOUtils.java
  vassal-app/src/main/java/VASSAL/tools/io/InputOutputStreamPump.java
  vassal-app/src/main/java/VASSAL/tools/io/ObfuscatingOutputStream.java
  vassal-app/src/main/java/VASSAL/tools/io/ZipArchive.java
  vassal-app/src/main/java/VASSAL/tools/version/VersionUtils.java
  vassal-app/src/test/java/VASSAL/tools/image/tilecache/TileToImageTest.java
  vassal-app/src/test/java/VASSAL/tools/io/CompositeInputStreamTest.java
  vassal-app/src/test/java/VASSAL/tools/io/DeobfuscatingInputStreamTest.java
  vassal-app/src/test/java/VASSAL/tools/io/IOUtilsTest.java
  vassal-app/src/test/resources/IOUtilsTest.txt
Labels: 3.5.0

#562 13636: fixes and test for bug 554
  .gitignore
  vassal-app/src/main/java/VASSAL/build/AbstractBuildable.java
  vassal-app/src/test/java/VASSAL/build/AbstractBuildableTest.java
Labels: 3.4.9

#564 13602-NPE in Mass piece Loader
  vassal-app/src/main/java/VASSAL/counters/MassPieceLoader.java
Labels: 3.4.9

#514 PieceDefiner update
  vassal-app/src/main/java/VASSAL/build/widget/PieceSlot.java
  vassal-app/src/main/java/VASSAL/configure/ConfigurerWindow.java
  vassal-app/src/main/java/VASSAL/configure/PropertiesWindow.java
  vassal-app/src/main/java/VASSAL/counters/Embellishment.java
  vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java
  vassal-app/src/main/java/VASSAL/counters/PlaceMarker.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-app/src/main/resources/icons/16x16/go-bottom.png
  vassal-app/src/main/resources/icons/16x16/go-top.png
  vassal-app/src/main/resources/icons/22x22/go-bottom.png
  vassal-app/src/main/resources/icons/22x22/go-top.png
  vassal-app/src/main/resources/icons/32x32/go-bottom.png
  vassal-app/src/main/resources/icons/32x32/go-top.png
  vassal-app/src/main/resources/icons/scalable/go-bottom.svg
  vassal-app/src/main/resources/icons/scalable/go-top.svg
  vassal-app/src/test/resources/clirr-ignored-differences.xml
Labels: 3.5.0

#568 13655: Turn off grid caching on boards which have zone highlighters
  vassal-app/src/main/java/VASSAL/build/module/Map.java
Labels: 3.4.9

#561 13661: Simplified ZIP writing
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/tools/WriteErrorDialog.java
  vassal-app/src/main/java/VASSAL/tools/io/ZipArchive.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
  vassal-app/src/test/resources/clirr-ignored-differences.xml
Labels: 3.5.0

#569 13659, 13660: Splitter Positioning & Window Height Preferences
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/build/module/GameState.java
  vassal-app/src/main/java/VASSAL/build/module/Map.java
  vassal-app/src/main/java/VASSAL/build/module/PieceWindow.java
  vassal-app/src/main/java/VASSAL/chat/ui/ChatServerControls.java
  vassal-app/src/main/java/VASSAL/launch/ModuleManagerWindow.java
  vassal-app/src/main/java/VASSAL/launch/PlayerWindow.java
  vassal-app/src/main/java/VASSAL/preferences/Prefs.java
  vassal-app/src/main/java/VASSAL/tools/ComponentSplitter.java
  vassal-app/src/main/java/VASSAL/tools/swing/SplitPane.java
  vassal-app/src/main/java/VASSAL/tools/swing/SwingUtils.java
  vassal-app/src/test/resources/clirr-ignored-differences.xml
Labels: 3.5.0

#563 13631 - somebody yanks a piece away
  vassal-app/src/main/java/VASSAL/command/MovePiece.java
Labels: 3.4.9

#566 13675 - Don't allow lone PieceSlots in a Piece Palette
  vassal-app/src/main/java/VASSAL/build/Widget.java
  vassal-app/src/main/java/VASSAL/build/module/ChartWindow.java
  vassal-app/src/main/java/VASSAL/build/module/PieceWindow.java
Labels: 3.5.0

#567 Game Piece Palette doc update
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/PieceWindow.adoc
Labels: 3.5.0

#571 13688 - Bad comparison in OrthoRotateOpBitmapImpl.equals()
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/GridOp.java
  vassal-app/src/main/java/VASSAL/tools/imageop/OrthoRotateOpBitmapImpl.java
Labels: 3.4.10

#386 13706 - Console - Commands from chatter line. (W/ some cheating protection)
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/build/module/BasicLogger.java
  vassal-app/src/main/java/VASSAL/build/module/Chatter.java
  vassal-app/src/main/java/VASSAL/build/module/Console.java
  vassal-app/src/main/java/VASSAL/build/module/ConsoleAppender.java
  vassal-app/src/main/java/VASSAL/build/module/GameState.java
  vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java
  vassal-app/src/main/java/VASSAL/launch/LaunchRequest.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
  vassal-app/src/main/resources/logback.xml
Labels: 3.5.0

#572 13720 - Tiles in the last row, column may be smaller than the standard sized tiles in SolidColorOp
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/SolidColorOp.java
Labels: 3.4.10

#574 Use ZipWriter for one-off ZIP writing
  vassal-app/src/main/java/VASSAL/build/module/BasicLogger.java
  vassal-app/src/main/java/VASSAL/build/module/GameState.java
  vassal-app/src/main/java/VASSAL/build/module/metadata/AbstractMetaData.java
  vassal-app/src/main/java/VASSAL/build/module/metadata/ExtensionMetaData.java
  vassal-app/src/main/java/VASSAL/build/module/metadata/SaveMetaData.java
  vassal-app/src/main/java/VASSAL/tools/io/ZipArchive.java
  vassal-app/src/main/java/VASSAL/tools/io/ZipWriter.java
Labels: 3.5.0

#576 13728 - Transparent board bg fix
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/Board.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/SolidColorOp.java
Labels: 3.4.11

#580 13741 - Don't put empty strings into what getImageNames() returns
  vassal-app/src/main/java/VASSAL/tools/DataArchive.java
Labels: 3.5.0

#579 13661 - Zip fix fix fix
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/build/module/Console.java
  vassal-app/src/main/java/VASSAL/build/module/GameState.java
  vassal-app/src/main/java/VASSAL/build/module/Inventory.java
  vassal-app/src/main/java/VASSAL/build/module/ModuleExtension.java
  vassal-app/src/main/java/VASSAL/build/module/WizardSupport.java
  vassal-app/src/main/java/VASSAL/build/module/documentation/BrowserHelpFile.java
  vassal-app/src/main/java/VASSAL/build/module/documentation/BrowserPDFFile.java
  vassal-app/src/main/java/VASSAL/build/module/map/TextSaver.java
  vassal-app/src/main/java/VASSAL/build/module/metadata/AbstractMetaData.java
  vassal-app/src/main/java/VASSAL/configure/SavedGameUpdaterDialog.java
  vassal-app/src/main/java/VASSAL/counters/Deck.java
  vassal-app/src/main/java/VASSAL/i18n/TranslateVassalWindow.java
  vassal-app/src/main/java/VASSAL/i18n/Translation.java
  vassal-app/src/main/java/VASSAL/i18n/VassalTranslation.java
  vassal-app/src/main/java/VASSAL/launch/ModuleManager.java
  vassal-app/src/main/java/VASSAL/preferences/Prefs.java
  vassal-app/src/main/java/VASSAL/preferences/ReadOnlyPrefs.java
  vassal-app/src/main/java/VASSAL/tools/BugUtils.java
  vassal-app/src/main/java/VASSAL/tools/CRCUtils.java
  vassal-app/src/main/java/VASSAL/tools/DataArchive.java
  vassal-app/src/main/java/VASSAL/tools/HTTPPostBuilder.java
  vassal-app/src/main/java/VASSAL/tools/JarArchive.java
  vassal-app/src/main/java/VASSAL/tools/Mp3AudioClip.java
  vassal-app/src/main/java/VASSAL/tools/ReadErrorDialog.java
  vassal-app/src/main/java/VASSAL/tools/ZipUpdater.java
  vassal-app/src/main/java/VASSAL/tools/image/FileImageTypeConverter.java
  vassal-app/src/main/java/VASSAL/tools/image/JPEGDecoder.java
  vassal-app/src/main/java/VASSAL/tools/image/svg/SVGImageUtils.java
  vassal-app/src/main/java/VASSAL/tools/image/tilecache/ImageTileDiskCache.java
  vassal-app/src/main/java/VASSAL/tools/image/tilecache/ImageToTiles.java
  vassal-app/src/main/java/VASSAL/tools/image/tilecache/TileToImage.java
  vassal-app/src/main/java/VASSAL/tools/image/tilecache/TileUtils.java
  vassal-app/src/main/java/VASSAL/tools/image/tilecache/TilesToImage.java
  vassal-app/src/main/java/VASSAL/tools/imageop/RotateScaleOpSVGImpl.java
  vassal-app/src/main/java/VASSAL/tools/imageop/SourceOpBitmapImpl.java
  vassal-app/src/main/java/VASSAL/tools/imageop/SourceOpSVGImpl.java
  vassal-app/src/main/java/VASSAL/tools/imageop/SourceTileOpSVGImpl.java
  vassal-app/src/main/java/VASSAL/tools/imports/adc2/ADC2Module.java
  vassal-app/src/main/java/VASSAL/tools/imports/adc2/MapBoard.java
  vassal-app/src/main/java/VASSAL/tools/imports/adc2/SymbolSet.java
  vassal-app/src/main/java/VASSAL/tools/io/DeobfuscatingInputStream.java
  vassal-app/src/main/java/VASSAL/tools/io/ObfuscatingOutputStream.java
  vassal-app/src/main/java/VASSAL/tools/io/ZipArchive.java
  vassal-app/src/test/java/VASSAL/chat/CompressorTest.java
  vassal-app/src/test/java/VASSAL/tools/image/ImageIOImageLoaderTest.java
  vassal-app/src/test/java/VASSAL/tools/image/tilecache/TileToImageTest.java
  vassal-app/src/test/java/VASSAL/tools/io/ZipArchiveTest.java
  vassal-app/src/test/resources/clirr-ignored-differences.xml
  vassal-app/src/test/resources/pmd.xml
Labels: 3.5.0

#578 1826 - Scroll bars for all Config Dialogs.
  vassal-app/src/main/java/VASSAL/build/module/MultiActionButton.java
  vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java
  vassal-app/src/main/java/VASSAL/build/module/map/BoardPicker.java
  vassal-app/src/main/java/VASSAL/build/module/map/ImageSaver.java
  vassal-app/src/main/java/VASSAL/build/module/map/MassKeyCommand.java
  vassal-app/src/main/java/VASSAL/build/module/properties/PropertyChangerConfigurer.java
  vassal-app/src/main/java/VASSAL/build/widget/PieceSlot.java
  vassal-app/src/main/java/VASSAL/chat/ui/ShowServerStatusAction.java
  vassal-app/src/main/java/VASSAL/configure/AutoConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/ComponentConfigPanel.java
  vassal-app/src/main/java/VASSAL/configure/ComponentLayout.java
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
  vassal-app/src/main/java/VASSAL/configure/Configurer.java
  vassal-app/src/main/java/VASSAL/configure/EditPropertiesAction.java
  vassal-app/src/main/java/VASSAL/configure/GlobalCommandTargetConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/ImageSelector.java
  vassal-app/src/main/java/VASSAL/configure/ListConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/NamedKeyStrokeArrayConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/PropertiesWindow.java
  vassal-app/src/main/java/VASSAL/counters/AreaOfEffect.java
  vassal-app/src/main/java/VASSAL/counters/BasicPiece.java
  vassal-app/src/main/java/VASSAL/counters/Decorator.java
  vassal-app/src/main/java/VASSAL/counters/DynamicProperty.java
  vassal-app/src/main/java/VASSAL/counters/ImagePicker.java
  vassal-app/src/main/java/VASSAL/counters/Obscurable.java
  vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java
  vassal-app/src/main/java/VASSAL/counters/PlaceMarker.java
  vassal-app/src/main/java/VASSAL/counters/SetGlobalProperty.java
  vassal-app/src/main/java/VASSAL/preferences/PrefsEditor.java
  vassal-app/src/main/java/VASSAL/tools/image/ImageUtils.java
  vassal-app/src/main/java/VASSAL/tools/image/LabelUtils.java
  vassal-app/src/main/java/VASSAL/tools/image/MultiResolutionRenderedImage.java
  vassal-app/src/main/java/VASSAL/tools/swing/SwingUtils.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: 3.5.0

#584 13760 - Upgrade to 15.0.1+9
  bootstrap.sh
Labels: 3.5.0

#582 13761 - MacOS X -> MacOS
  Makefile
  dist/macos/.DS_Store
  dist/macos/Info.plist
  dist/macos/PkgInfo
  dist/macos/VASSAL.icns
  dist/macos/VASSAL.sh
  dist/macos/background.png
  dist/macos/background.svg
  dist/notes/NOTES-bgg.jinja
  dist/notes/NOTES-csw.jinja
  dist/notes/NOTES-news.jinja
  dist/notes/NOTES-vassalforum.jinja
  vassal-app/src/main/java/VASSAL/Info.java
  vassal-app/src/main/java/VASSAL/build/module/GlobalOptions.java
  vassal-app/src/main/java/VASSAL/build/module/Map.java
  vassal-app/src/main/java/VASSAL/build/module/map/Flare.java
  vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java
  vassal-app/src/main/java/VASSAL/build/module/map/SetupStack.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/GridEditor.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/RegionGrid.java
  vassal-app/src/main/java/VASSAL/launch/AbstractLaunchAction.java
  vassal-app/src/main/java/VASSAL/launch/Editor.java
  vassal-app/src/main/java/VASSAL/launch/EditorWindow.java
  vassal-app/src/main/java/VASSAL/launch/Launcher.java
  vassal-app/src/main/java/VASSAL/launch/ModuleManager.java
  vassal-app/src/main/java/VASSAL/launch/ModuleManagerWindow.java
  vassal-app/src/main/java/VASSAL/launch/Player.java
  vassal-app/src/main/java/VASSAL/launch/PlayerWindow.java
  vassal-app/src/main/java/VASSAL/launch/StandardConfig.java
  vassal-app/src/main/java/VASSAL/launch/StartUp.java
  vassal-app/src/main/java/VASSAL/tools/ApplicationIcons.java
  vassal-app/src/main/java/VASSAL/tools/filechooser/FileChooser.java
  vassal-app/src/main/java/VASSAL/tools/image/svg/SVGRenderer.java
  vassal-app/src/main/java/VASSAL/tools/swing/SwingUtils.java
  vassal-app/src/test/java/VASSAL/tools/lang/MemoryUtilsTest.java
  vassal-doc/src/main/designerguide/additional-module-components.adoc
  vassal-doc/src/main/designerguide/additional-topics.adoc
  vassal-doc/src/main/designerguide/game-pieces.adoc
  vassal-doc/src/main/designerguide/overview.adoc
  vassal-doc/src/main/designerguide/preparation.adoc
  vassal-doc/src/main/designerguide/the-module-editor.adoc
  vassal-doc/src/main/userguide/userguide.adoc
Labels: 3.5.0

#586 Added edit-find icon
  vassal-app/src/main/resources/icons/16x16/edit-find.png
  vassal-app/src/main/resources/icons/22x22/edit-find.png
  vassal-app/src/main/resources/icons/32x32/edit-find.png
  vassal-app/src/main/resources/icons/scalable/edit-find.svg
Labels: 3.5.0

#585 13677, 13679 - Ensure AbstractTiledOpImpl.fixTileSize() is atomic
  vassal-app/src/main/java/VASSAL/counters/Labeler.java
  vassal-app/src/main/java/VASSAL/tools/imageop/AbstractTiledOpImpl.java
  vassal-app/src/main/java/VASSAL/tools/imageop/GamePieceOpImpl.java
  vassal-app/src/main/java/VASSAL/tools/imageop/OrthoRotateOpBitmapImpl.java
Labels: 3.4.11

#587 13775 - ChessCock - borrowed the L to put in htmL
  vassal-app/src/main/java/VASSAL/build/module/ChessClockControl.java
Labels: 3.5.0

#588 Set NSIS installer scripts to use Unicode explictly.
  dist/windows/nsis/installer32.nsi
  dist/windows/nsis/installer64.nsi
Labels: 3.5.0

#589 Set main split pane components minimum size later
  vassal-app/src/main/java/VASSAL/build/module/Map.java
Labels: 3.5.0
