Repository vassalengine/vassal, pull requests merged in 2021-02, with the labels that each got.

#666 13959 - 3.5.1 - Wizard should add loaded-file name to app window title
  vassal-app/src/main/java/VASSAL/build/module/WizardSupport.java
Labels: 3.5.1

#663 13954 - Alt, Shift+Ctrl should not change selection.
  vassal-app/src/main/java/VASSAL/build/module/map/KeyBufferer.java
Labels: 3.5.1

#667 13960 - MouseoverStackViewer was mis-centering when 'draw pieces' not selected
  vassal-app/src/main/java/VASSAL/build/module/map/CounterDetailViewer.java
Labels: 3.5.1

#668 13694 - Change extension extension back to .vmdx
  vassal-app/src/main/java/VASSAL/launch/EditExtensionAction.java
  vassal-app/src/main/java/VASSAL/launch/NewExtensionAction.java
  vassal-app/src/main/java/VASSAL/tools/filechooser/ModuleExtensionFileFilter.java
  vassal-doc/src/main/designerguide/additional-topics.adoc
  vassal-doc/src/main/designerguide/creating-module-extensions.adoc
  vassal-doc/src/main/designerguide/publishing-your-module.adoc
  vassal-doc/src/main/userguide/userguide.adoc
Labels: 3.5.1

#671 13970 - dicebutton icons & "mask" images were being improperly suggested for removal …
  vassal-app/src/main/java/VASSAL/build/module/DiceButton.java
  vassal-app/src/main/java/VASSAL/counters/Obscurable.java
Labels: 3.5.1

#672 13971 - Make new extensions openable again
  vassal-app/src/main/java/VASSAL/build/module/ModuleExtension.java
Labels: 3.5.1

#674 13937 - Fixed bad translation key
  vassal-app/src/main/java/VASSAL/build/GameModule.java
Labels: 3.5.1

#677 13984 - NPE when constructing ABRs from the Module Manager
  vassal-app/src/main/java/VASSAL/tools/BugUtils.java
Labels: 3.5.1

#678 13987 - Chessclock buttons with icons were getting adjusted to inappropriate width and height
  vassal-app/src/main/java/VASSAL/build/module/chessclockcontrol/ChessClock.java
Labels: 3.5.1

#676 3.5.1 - 13977 - Alt+Shift now a configurable option for band-selectability of does-not-stack pieces.
  vassal-app/src/main/java/VASSAL/counters/Immobilized.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: 3.5.1

#681 13997 - aesthetic fix to chatter start for larger monitors.
  vassal-app/src/main/java/VASSAL/build/module/Chatter.java
Labels: 3.5.1

#682 3.5.1 - 13999 - fixed an exception in Fast Match for Moved property
  vassal-app/src/main/java/VASSAL/counters/GlobalCommand.java
Labels: 3.5.1

#683 13996 - Sanitize temp filename bases
  vassal-app/src/main/java/VASSAL/tools/io/ZipArchive.java
Labels: 3.5.1

#685 13968 Apparently this can be null for some modules
  vassal-app/src/main/java/VASSAL/build/module/documentation/HelpFile.java
Labels: 3.5.1

#687 14000 - Ensure that this process doesn't already have the prefs file lock when we try to take it
  vassal-app/src/main/java/VASSAL/preferences/Prefs.java
Labels: 3.5.1

#688 13992 - Don't add nulls to used images list. Layers which have no image may
  vassal-app/src/main/java/VASSAL/counters/Embellishment.java
Labels: 3.5.1

#689 13944 - Ensure that deprecated mainWindowDock is fiddled on first pass only
  vassal-app/src/main/java/VASSAL/build/module/Map.java
Labels: 3.5.1

#679 13991- fix GameRefresher stops when NewGame with hasFile flag set to true ex…
  vassal-app/src/main/java/VASSAL/configure/RefreshPredefinedSetupsDialog.java
Labels: 3.5.1

#680 13993 - disable Refresh in Player if gpid errors, delete orphan pieces when r…
  vassal-app/src/main/java/VASSAL/build/module/GameRefresher.java
  vassal-app/src/main/java/VASSAL/configure/RefreshPredefinedSetupsDialog.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: 3.5.1

#690 13981 - Exception generated when using Edit All Contained Pieces
  vassal-app/src/main/java/VASSAL/counters/MassPieceDefiner.java
  vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java
Labels: 3.5.1

#693 14007 - Check for docking PieceWindows when loading extensions
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/build/module/ModuleExtension.java
Labels: 3.5.1

#695 14009 - Dialog cosmetic updates
  vassal-app/src/main/java/VASSAL/build/module/GameRefresher.java
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
  vassal-app/src/main/java/VASSAL/configure/RefreshPredefinedSetupsDialog.java
  vassal-app/src/main/java/VASSAL/configure/RemoveUnusedImagesDialog.java
  vassal-app/src/main/java/VASSAL/counters/TraitLayout.java
  vassal-app/src/main/java/VASSAL/launch/EditorWindow.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-app/src/test/resources/clirr-ignored-differences.xml
Labels: 3.5.1

#696 14011 Fix Run-time Dice dialog formatting
  vassal-app/src/main/java/VASSAL/build/module/DiceButton.java
  vassal-app/src/main/java/VASSAL/build/module/RandomTextButton.java
  vassal-app/src/main/java/VASSAL/configure/AutoConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/ConfigurerWindow.java
  vassal-app/src/main/java/VASSAL/tools/swing/SwingUtils.java
Labels: 3.5.1

#700 14015 Infinite loop detection for PlaceMarker
  vassal-app/src/main/java/VASSAL/counters/PlaceMarker.java
  vassal-app/src/main/java/VASSAL/counters/Replace.java
Labels: 3.5.1

#701 13930 Detect infinite loops in TurnTracker
  vassal-app/src/main/java/VASSAL/build/module/turn/TurnTracker.java
Labels: 3.5.1

#698 14022 - Upgrade bundled Java to 15.0.2+7
  bootstrap.sh
Labels: 3.5.1

#699 3.5.1 - 14023 - proper hit list reporting for search w/r/t prototypes and con…
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
Labels: 3.5.1

#702 13958 - Handle the InterruptedException thrown when cancelling a screenshot
  vassal-app/src/main/java/VASSAL/build/module/map/ImageSaver.java
Labels: 3.5.1

#703 13988 Show Invalid module dialog if trying to load or edit an invalid or missing module from the MM
  vassal-app/src/main/java/VASSAL/launch/Editor.java
  vassal-app/src/main/java/VASSAL/launch/Player.java
Labels: 3.5.1

#704 14019 - Module Manager changes
  vassal-app/src/main/java/VASSAL/build/module/metadata/AbstractMetaData.java
  vassal-app/src/main/java/VASSAL/launch/ModuleManagerWindow.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: 3.5.1

#708 13742 - Action button now arms on press, fires on release
  vassal-app/src/main/java/VASSAL/build/module/map/KeyBufferer.java
  vassal-app/src/main/java/VASSAL/counters/ActionButton.java
Labels: 3.5.1

#705 Fixed
  vassal-app/src/main/java/VASSAL/build/module/GameState.java
Labels: 3.5.1

#707 14026 - Pieces without stacks now refresh too
  vassal-app/src/main/java/VASSAL/build/module/GameRefresher.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: 3.5.1

#709 3.5.1 - 14032 - Fast Match was pulling wrong number of cards from decks
  vassal-app/src/main/java/VASSAL/counters/GlobalCommand.java
Labels: 3.5.1

#712 14033 - Fast Match details not sticking in Global Key Commands
  vassal-app/src/main/java/VASSAL/build/module/map/MassKeyCommand.java
  vassal-app/src/main/java/VASSAL/configure/GlobalCommandTargetConfigurer.java
  vassal-app/src/main/java/VASSAL/counters/GlobalCommandTarget.java
Labels: 3.5.1

#711 14034 - Prevent concurrent updates to prefs
  vassal-app/src/main/java/VASSAL/preferences/Prefs.java
Labels: 3.5.1

#713 14035 - Toolbar Menus and Multi-Action buttons drop off last item in list.
  vassal-app/src/main/java/VASSAL/configure/StringArrayConfigurer.java
Labels: 3.5.1

#714 3.5.1 - 14039 - fixed the trait order table in docs
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/GamePiece.adoc
Labels: 3.5.1

#716 14040 - User Guide cleanup
  vassal-doc/src/main/designerguide/designerguide.adoc
  vassal-doc/src/main/userguide/userguide.adoc
Labels: 3.5.1

#715 14040 - fixed broken designer's guide table
  vassal-doc/src/main/designerguide/additional-module-components.adoc
  vassal-doc/src/main/designerguide/additional-topics.adoc
  vassal-doc/src/main/designerguide/best-practices.adoc
  vassal-doc/src/main/designerguide/creating-module-extensions.adoc
  vassal-doc/src/main/designerguide/decks-and-cards.adoc
  vassal-doc/src/main/designerguide/designerguide.adoc
  vassal-doc/src/main/designerguide/game-piece-image-definitions.adoc
  vassal-doc/src/main/designerguide/game-pieces.adoc
  vassal-doc/src/main/designerguide/generating-random-results.adoc
  vassal-doc/src/main/designerguide/help-menu.adoc
  vassal-doc/src/main/designerguide/maps-and-boards.adoc
  vassal-doc/src/main/designerguide/overview.adoc
  vassal-doc/src/main/designerguide/pre-defined-setups.adoc
  vassal-doc/src/main/designerguide/preparation.adoc
  vassal-doc/src/main/designerguide/prototype-definitions.adoc
  vassal-doc/src/main/designerguide/publishing-your-module.adoc
  vassal-doc/src/main/designerguide/sides.adoc
  vassal-doc/src/main/designerguide/the-module-editor.adoc
  vassal-doc/src/main/designerguide/tutorials.adoc
  vassal-doc/src/main/designerguide/updating-a-module.adoc
  vassal-doc/src/main/designerguide/using-properties.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Expression.adoc
Labels: 3.5.1

#717 14040 - Reference Manual cleanup
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/ActionButton.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/AreaOfEffect.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/BasicPiece.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/CalculatedProperty.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/ChatLog.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/DeckGlobalKeyCommand.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/DynamicProperty.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Editor.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Expression.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/ExpressionBuilder.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Extension.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/GameModule.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/GamePiece.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/GamePieceImage.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/GamePieceLayers.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/GamePieceLayouts.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/GlobalHotKey.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/GlobalKeyCommand.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/GlobalOptions.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/HexGrid.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Hideable.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Label.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Layer.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Map.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/MarkMoved.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Marker.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Mask.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/MassPieceLoader.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/MenuSeparator.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/MessageFormat.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/ModuleUpdater.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/MovementTrail.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/NamedKeyCommand.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/NonRectangular.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/NonStacking.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Pivot.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/PlaySound.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Preferences.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/PrivateWindow.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Properties.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/PropertyMarker.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/PropertyMatchExpression.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/PropertySheet.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Replace.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/ReportChanges.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/RestrictCommands.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/RestrictedAccess.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/ReturnToDeck.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Rotate.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/SavedGameUpdater.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/SendToLocation.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/SetGlobalProperty.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Spreadsheet.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/SubMenu.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Translate.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Translations.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/TriggerAction.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/TurnTracker.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/UsePrototype.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Vassal.adoc
Labels: 3.5.1

#718 toolbar
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Toolbar.adoc
Labels: 3.5.1

#719 14040 - More docs cleanup
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/GamePiece.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Map.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Properties.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Toolbar.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/TurnTracker.adoc
Labels: 3.5.1

#721 3.5.2 - 14043 - fix flare broken help link
  vassal-app/src/main/java/VASSAL/build/module/chessclockcontrol/ChessClock.java
  vassal-app/src/main/java/VASSAL/build/module/map/Flare.java
  vassal-app/src/main/java/VASSAL/counters/Deselect.java
Labels: 3.5.2

#722 14041 - Prevent race when creating GlobalPrefs
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/launch/ShutDownAction.java
  vassal-app/src/main/java/VASSAL/preferences/Prefs.java
  vassal-app/src/main/java/VASSAL/tools/UsernameAndPasswordDialog.java
Labels: 3.5.2

#723 14047 - Use Modules as well as RecentModules for module list
  vassal-app/src/main/java/VASSAL/launch/ModuleManagerWindow.java
Labels: 3.5.2

#725 missing deselect files
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Deselect.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/Deselect.png
Labels: 3.5.2

#727 14055 - trait list
  vassal-app/src/main/java/VASSAL/counters/SetGlobalProperty.java
Labels: 3.5.2

#729 14059 - better piece definer descriptions of Marker traits
  vassal-app/src/main/java/VASSAL/counters/Marker.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: 3.5.2

#730 14061-String Array Configurers broken
  vassal-app/src/main/java/VASSAL/configure/StringArrayConfigurer.java
Labels: 3.5.2

#726 3.5.2 - 14053 - canceling welcome wizard closes app unless show-wizard-at-sta…
  vassal-app/src/main/java/VASSAL/build/module/WizardSupport.java
Labels: 3.5.2

#733 3.5.2 - 14074 - Flares were stealing each others' commands
  vassal-app/src/main/java/VASSAL/build/module/map/Flare.java
Labels: 3.5.2

#735 14076 - Use correct label for max value.
  vassal-app/src/main/java/VASSAL/counters/SetGlobalProperty.java
Labels: 3.5.2

#731 14057, 14065 - Improve Piece Definer image display width
  vassal-app/src/main/java/VASSAL/build/widget/PieceSlot.java
  vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java
Labels: 3.5.2

#736 14077 - Include '(pixels)' in 'Turn Label Display Length' label for clarity
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: 3.5.2

#738 14068 - Use Tango Edit-undo icon for Named Hotkey Configurer undo
  vassal-app/src/main/java/VASSAL/configure/NamedHotKeyConfigurer.java
  vassal-app/src/main/resources/icons/16x16/edit-undo.png
  vassal-app/src/main/resources/icons/22x22/edit-undo.png
  vassal-app/src/main/resources/icons/32x32/edit-undo.png
  vassal-app/src/main/resources/icons/scalable/edit-undo.svg
Labels: 3.5.2

#742 14098 - add module version to window title
  vassal-app/src/main/java/VASSAL/build/GameModule.java
Labels: 3.5.2

#737 14070 - Array Configurers move cursor to newly created entry
  vassal-app/src/main/java/VASSAL/configure/AbstractConfigurableListEntry.java
  vassal-app/src/main/java/VASSAL/configure/Configurer.java
  vassal-app/src/main/java/VASSAL/configure/DynamicKeyCommandConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/DynamicKeyCommandListConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/NamedHotKeyConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/NamedKeyStrokeArrayConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/StringArrayConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/StringConfigurer.java
Labels: 3.5.2

#745 14104 - Don't use "No Image" display text as the image name.
  vassal-app/src/main/java/VASSAL/configure/ImageSelector.java
  vassal-app/src/main/java/VASSAL/counters/ImagePicker.java
Labels: 3.5.2

#732 14064 - RefreshPredefinedSetups in Extension Editor
  vassal-app/src/main/java/VASSAL/build/module/GameRefresher.java
  vassal-app/src/main/java/VASSAL/configure/RefreshPredefinedSetupsDialog.java
  vassal-app/src/main/java/VASSAL/launch/EditorWindow.java
  vassal-app/src/main/java/VASSAL/launch/ModuleEditorWindow.java
  vassal-app/src/test/resources/clirr-ignored-differences.xml
Labels: 3.5.2

#746 14111 - Fix duplicate i18n key - Dynamic Property incorrect description for initial value
  vassal-app/src/main/java/VASSAL/counters/DynamicProperty.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: 3.5.2

#748 14116 - Module sort order
  vassal-app/src/main/java/VASSAL/launch/ModuleManagerWindow.java
  vassal-app/src/main/java/VASSAL/tools/version/VersionUtils.java
Labels: 3.5.2

#749 14117 - Need to check armed button position against Map.positionOf() to take into account stacking offset.
  vassal-app/src/main/java/VASSAL/counters/ActionButton.java
Labels: 3.5.2

#750 14078 - Prevent Bad Data Errors from unstacked counters
  vassal-app/src/main/java/VASSAL/script/ExpressionInterpreter.java
Labels: 3.5.3

#752 14121 - Global Property descriptions appear next to the names in the main Editor window.
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
Labels: 3.4.3

#753 14122 - Must check that the map hasn't changed for the armed ActionButton.
  vassal-app/src/main/java/VASSAL/counters/ActionButton.java
Labels: 3.5.3

#756 14124-Remove '(Optional)' from Send To Location Board Name hint
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: 3.5.4

#757 14112-Dynamic Property List of Values cursor jumps after typing 1 character
  vassal-app/src/main/java/VASSAL/build/module/properties/PropertyChangerConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/StringArrayConfigurer.java
  vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java
Labels: 3.5.4

#758 3.5.4 - 14136 - Module level GKCs were not honoring fast match
  vassal-app/src/main/java/VASSAL/build/module/GlobalKeyCommand.java
Labels: 3.5.4

#755 14131 - Beanshell recognises all usable Java 11 String functions
  vassal-app/src/main/java/bsh/BeanShellExpressionValidator.java
Labels: 3.5.4

#760 14139 - Delete trait to set old... properties before deleting unit
  vassal-app/src/main/java/VASSAL/counters/Delete.java
Labels: 3.5.4

#762 14153 - Fix Chatter losing first character of chat when counters selected
  vassal-app/src/main/java/VASSAL/build/module/map/ForwardToKeyBuffer.java
  vassal-app/src/main/java/VASSAL/command/Command.java
Labels: 3.5.4

#740 14088 - Give the ImageOp a kick when the source changes.
  vassal-app/src/main/java/VASSAL/configure/ImageSelector.java
  vassal-app/src/main/java/VASSAL/counters/ImagePicker.java
Labels: 3.5.4

#741 14066 - Remove Unused Image dialog improvements - Layout and file sizes
  vassal-app/src/main/java/VASSAL/configure/RemoveUnusedImagesDialog.java
  vassal-app/src/main/java/VASSAL/launch/ExtensionEditorWindow.java
  vassal-app/src/main/java/VASSAL/tools/DataArchive.java
  vassal-app/src/main/java/VASSAL/tools/io/FileArchive.java
  vassal-app/src/main/java/VASSAL/tools/io/FileUtils.java
  vassal-app/src/main/java/VASSAL/tools/io/ZipArchive.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-app/src/main/resources/icons/16x16/go-first.png
  vassal-app/src/main/resources/icons/16x16/go-last.png
  vassal-app/src/main/resources/icons/22x22/go-first.png
  vassal-app/src/main/resources/icons/22x22/go-last.png
  vassal-app/src/main/resources/icons/32x32/go-first.png
  vassal-app/src/main/resources/icons/32x32/go-last.png
  vassal-app/src/main/resources/icons/scalable/go-first.svg
  vassal-app/src/main/resources/icons/scalable/go-last.svg
Labels: 3.5.4

#754 14149 - Packaging cleanup + add VASSAL.conf property
  Makefile
  dist/windows/VASSAL.l4j.xml.in
  dist/windows/nsis/installer.nsi
  dist/windows/nsis/installer32.nsi
  release-prepare/pom.xml
  vassal-app/src/main/java/VASSAL/launch/AbstractLaunchAction.java
  vassal-app/src/main/java/VASSAL/launch/StandardConfig.java
  vassal-app/src/main/resources/logback.xml
Labels: 3.5.4

#763 14148 - Fix truncated labels in Module Editor
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
  vassal-app/src/main/java/VASSAL/configure/EditPropertiesAction.java
Labels: 3.5.4
