Repository vassalengine/vassal, pull requests merged in 2021-10, with the labels that each got.

#10477 10476 Key Command editing bug
  vassal-app/src/main/java/VASSAL/configure/NamedHotKeyConfigurer.java
Labels: Ready for Review

#10484 10484 - Deselect trait improvements and double-click Mat
  vassal-app/src/main/java/VASSAL/build/module/map/KeyBufferer.java
  vassal-app/src/main/java/VASSAL/counters/Deselect.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Deselect.adoc
Labels: Ready for Review

#10487 10468 Refresh Counters support for Mats and Cargo
  vassal-app/src/main/java/VASSAL/build/module/GameRefresher.java
  vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java
  vassal-app/src/main/java/VASSAL/counters/Mat.java
  vassal-app/src/main/java/VASSAL/counters/MatCargo.java
  vassal-app/src/main/java/VASSAL/counters/Translate.java
Labels: Ready for Review

#10486 10486 Better obscurable option for insetting
  vassal-app/src/main/java/VASSAL/counters/Obscurable.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Mask.adoc
Labels: Review-Changes Complete

#10471 10470 - 3.6.0 Documentation updates
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/GamePiece.adoc
Labels: documentation, Ready for Review

#10547 10547 Improve fast match expressions interaction w/ $...$ and Beanshell
  vassal-app/src/main/java/VASSAL/counters/GlobalCommand.java
  vassal-app/src/main/java/VASSAL/counters/GlobalCommandTarget.java
  vassal-app/src/test/resources/clirr-ignored-differences.xml
Labels: Ready for Review

#10543 10543 - Place Marker trait properly initializes OldMat properties
  vassal-app/src/main/java/VASSAL/counters/PlaceMarker.java
Labels: Ready for Review

#10558 10558 - "Current Mat" Fast-Match option
  vassal-app/src/main/java/VASSAL/configure/GlobalCommandTargetConfigurer.java
  vassal-app/src/main/java/VASSAL/counters/GlobalCommand.java
  vassal-app/src/main/java/VASSAL/counters/GlobalCommandTarget.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/FastMatch.adoc
Labels: Ready for Review

#10563 10563 - Paste button in PieceDefiner no longer gets stuck greyed out
  vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java
Labels: Ready for Review

#10552 10552 - CounterDetailViewer - can combine layer filters with property match expression
  vassal-app/src/main/java/VASSAL/build/module/map/CounterDetailViewer.java
  vassal-app/src/main/java/VASSAL/counters/Embellishment.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/MouseOver.adoc
Labels: Ready for Review

#10565 10565 - While double-clicking to open component in Editor, holding Alt, Shift, and/or Ctrl affects the location the new window opens.
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
  vassal-app/src/main/java/VASSAL/configure/EditPropertiesAction.java
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Editor.adoc
Labels: Ready for Review

#10578 10578 - MatCargo now provides OldMatOffsetX and OldMatOffsetY properties
  vassal-app/src/main/java/VASSAL/counters/BasicPiece.java
  vassal-app/src/main/java/VASSAL/counters/Decorator.java
  vassal-app/src/main/java/VASSAL/counters/PlaceMarker.java
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/MatCargo.adoc
Labels: Review-Changes Complete

#10643 10643 - Players loading games through the starting Wizard should actually see saved game mismatch warnings (e.g. loading wrong version)
  vassal-app/src/main/java/VASSAL/build/module/GameState.java
  vassal-app/src/main/java/VASSAL/build/module/WizardSupport.java
Labels: Ready for Review

#10636 13837 - Warn when Global Property has a blank name (which causes NPE on game load)
  vassal-app/src/main/java/VASSAL/build/module/properties/GlobalProperty.java
  vassal-app/src/main/java/VASSAL/configure/NotNullConfigureName.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-app/src/main/resources/VASSAL/i18n/Editor_es.properties
Labels: Ready for Review

#10648 5493 - Private chat windows will no longer steal focus
  vassal-app/src/main/java/VASSAL/chat/PrivMsgCommand.java
  vassal-app/src/main/java/VASSAL/chat/ui/PrivateMessageAction.java
Labels: Ready for Review

#10654 10115 - Fixed corner-case NPE when closing a game
  vassal-app/src/main/java/VASSAL/build/module/GameState.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: Ready for Review

#10628 10628 - Autopeek Rollover
  vassal-app/src/main/java/VASSAL/counters/Obscurable.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Mask.adoc
Labels: Ready to Merge

#10633 10633 - Remove doubled images from Ghost Bug Pref
  vassal-app/src/main/java/VASSAL/build/module/GlobalOptions.java
  vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
  vassal-app/src/test/resources/clirr-ignored-differences.xml
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Preferences.adoc
Labels: Ready to Merge

#10641 9226 - When Editor changes a prototype, clear the prototype cache and all pieceslot caches
  vassal-app/src/main/java/VASSAL/build/module/PrototypeDefinition.java
  vassal-app/src/main/java/VASSAL/build/module/PrototypesContainer.java
  vassal-app/src/main/java/VASSAL/build/module/map/SetupStack.java
  vassal-app/src/main/java/VASSAL/build/widget/PieceSlot.java
Labels: Ready to Merge

#10646 7958 - Fixed a retire button exploit
  vassal-app/src/main/java/VASSAL/build/module/GameState.java
  vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java
Labels: Ready to Merge

#10647 6946 - Private Maps visible to non-owning players will correctly display Mouseover text
  vassal-app/src/main/java/VASSAL/build/module/PrivateMap.java
Labels: Ready to Merge

#10658 10306 - Fix NPE if try to open translations but the buildable doesn't exist
  vassal-app/src/main/java/VASSAL/i18n/TranslateWindow.java
Labels: Ready to Merge

#10659 10028 - Sanitize temporary file names a bit earlier
  vassal-app/src/main/java/VASSAL/tools/io/ZipArchive.java
Labels: Ready to Merge

#10649 4546 - Deck can start face-up or face-down when using right-click menu setting
  vassal-app/src/main/java/VASSAL/build/module/map/DrawPile.java
  vassal-app/src/main/java/VASSAL/counters/Deck.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: Ready to Merge

#10660 9295 Report translated name for Symbolic Die Faces
  vassal-app/src/main/java/VASSAL/build/module/SpecialDie.java
Labels: Ready for Review

#10670 Min/Max were reversed in Embellishment
  vassal-app/src/main/java/VASSAL/counters/Embellishment.java
Labels: Ready for Review
