Repository vassalengine/vassal, pull requests merged in 2021-04, with the labels that each got.

#849 14290 - GlobalKeyCommands causing unnecessary Deck reshuffles and corruption
  vassal-app/src/main/java/VASSAL/counters/Deck.java
  vassal-app/src/main/java/VASSAL/counters/GlobalCommand.java
  vassal-app/src/main/java/VASSAL/counters/Stack.java
  vassal-app/src/test/java/VASSAL/counters/DeckTest.java
  vassal-app/src/test/java/VASSAL/counters/StackTest.java
  vassal-app/src/test/resources/clirr-ignored-differences.xml
Labels: 3.5.5

#850 14296 - prevent keys-held-down from running off end of step/undo buffer
  vassal-app/src/main/java/VASSAL/build/module/BasicLogger.java
Labels: 3.5.5

#851 14309 - Added accidentally dropped Deck.deck key
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: 3.5.5

#852 14262 - Added missing Editor.GridEditor.command_arrow_keys translation key
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: 3.5.5

#853 14310 Property Sheet losing Menu and Description
  vassal-app/src/main/java/VASSAL/counters/PropertySheet.java
Labels: 3.5.5

#854 14321,14322 - IllegalComponentStateException in PropertySheet.myKeyEvent(), TableInfo.myKeyEvent()
  vassal-app/src/main/java/VASSAL/counters/PropertySheet.java
  vassal-app/src/main/java/VASSAL/counters/TableInfo.java
Labels: 3.5.5

#855 14327 - Deprecated LaunchButton fields, fixed bug in ToolbarMenu
  vassal-app/src/main/java/VASSAL/build/module/DiceButton.java
  vassal-app/src/main/java/VASSAL/build/module/DoActionButton.java
  vassal-app/src/main/java/VASSAL/build/module/Inventory.java
  vassal-app/src/main/java/VASSAL/build/module/Map.java
  vassal-app/src/main/java/VASSAL/build/module/NotesWindow.java
  vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java
  vassal-app/src/main/java/VASSAL/build/module/SpecialDiceButton.java
  vassal-app/src/main/java/VASSAL/build/module/ToolbarMenu.java
  vassal-app/src/main/java/VASSAL/build/module/map/ImageSaver.java
  vassal-app/src/main/java/VASSAL/build/module/map/LOS_Thread.java
  vassal-app/src/main/java/VASSAL/build/module/map/LayerControl.java
  vassal-app/src/main/java/VASSAL/build/module/map/MapShader.java
  vassal-app/src/main/java/VASSAL/build/module/map/MassKeyCommand.java
  vassal-app/src/main/java/VASSAL/build/module/map/PieceRecenterer.java
  vassal-app/src/main/java/VASSAL/build/module/map/TextSaver.java
  vassal-app/src/main/java/VASSAL/build/module/properties/ChangePropertyButton.java
Labels: 3.5.5

#856 14332 - Fixed NPE in Expression.resetCachedExpressions()
  vassal-app/src/main/java/VASSAL/script/expression/Expression.java
Labels: 3.5.5

#846 Bug13203 - GameRefresher refreshes Double Deckers as well now.
  vassal-app/src/main/java/VASSAL/build/module/GameRefresher.java
Labels: 3.5.5

#859 14331 - Make offsets work in SelectionHighlighter
  vassal-app/src/main/java/VASSAL/build/module/map/SelectionHighlighter.java
Labels: 3.5.5

#858 14336 - CounterDetailViewer - adjusted to not improperly exclude non-moveable units when "include move-when-selected" is unchecked
  vassal-app/src/main/java/VASSAL/build/module/map/CounterDetailViewer.java
Labels: 3.5.5

#861 14317 - Deck names can be null sometimes, apparently
  vassal-app/src/main/java/VASSAL/counters/ReturnToDeck.java
Labels: 3.5.5

#860 14301 - GKC/GHK trigger actions out of order at remote end in online play
  vassal-app/src/main/java/VASSAL/build/GameModule.java
Labels: 3.5.5

#869 14351 - don't crash with no Player Roster
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/build/module/Console.java
  vassal-app/src/main/java/VASSAL/build/module/GameState.java
  vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java
Labels: 3.5.6

#873 3.6 - Restores TranslatableMessage support to 3.6 (that we hid in 3.5)
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java
  vassal-app/src/main/java/VASSAL/preferences/Prefs.java
Labels: 3.6.0

#872 3.5.6(!!) - 14286 - prevent fastmatch expression 'bad module data' from throwing exceptions
  vassal-app/src/main/java/VASSAL/script/expression/Expression.java
Labels: 3.5.6

#876 3.6 - 14360 - Window title less verbose on subwindows
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/build/module/Map.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: 3.6.0

#878 3.6 - 14365 - DeckPosition was sometimes reporting 1 higher than the actual…
  vassal-app/src/main/java/VASSAL/counters/BasicPiece.java
Labels: 3.6.0

#820 3.6 - 14257 - option to reverse order pieces are displayed in CounterDetailViewer
  vassal-app/src/main/java/VASSAL/build/module/GlobalOptions.java
  vassal-app/src/main/java/VASSAL/build/module/map/CounterDetailViewer.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: 3.6.0

#835 3.6 - 14276 - expose Mapname_isVisible property
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/build/module/Map.java
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Map.adoc
Labels: 3.6.0

#840 3.6 - 14283 [Global Options] can be configured to let toolbar items on clos…
  vassal-app/src/main/java/VASSAL/build/module/GlobalOptions.java
  vassal-app/src/main/java/VASSAL/tools/LaunchButton.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/GlobalOptions.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/GlobalOptions.png
Labels: 3.6.0

#879 14368 Using String functions on property names containing double quotes in value causes Bad Module Data
  vassal-app/src/main/java/VASSAL/script/ExpressionInterpreter.java
Labels: 3.5.6

#886 14311-Changes to Hotkey Commands in Components not reverted on Cancel
  vassal-app/src/main/java/VASSAL/configure/GlobalCommandTargetConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/NamedHotKeyConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/TranslatingStringEnumConfigurer.java
Labels: 3.5.6

#888 Minor docs corrections
  vassal-app/src/main/resources/help/Intro.html
Labels: 3.5.6

#870 3.6 - 14358 - ReportState checkbox overrides GKC suppression of individual reports
  vassal-app/src/main/java/VASSAL/build/module/Map.java
  vassal-app/src/main/java/VASSAL/counters/ReportState.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/ReportChanges.adoc
Labels: 3.6.0

#877 3.6 - 14364 - removed ignored 'button tooltip' field from Turn Tracker config
  vassal-app/src/main/java/VASSAL/build/module/turn/TurnTracker.java
Labels: 3.6.0, Review-In Progress

#871 3.6 - 14359 - CountStack() added to beanshell for piece expressions
  vassal-app/src/main/java/VASSAL/configure/BeanShellFunctionMenu.java
  vassal-app/src/main/java/VASSAL/counters/Stack.java
  vassal-app/src/main/java/VASSAL/script/ExpressionInterpreter.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-app/src/main/resources/VASSAL/script/init_expression.bsh
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Expression.adoc
Labels: 3.6.0, Review-Changes Requested

#865 3.6 - 14346 - Deck reports suppressed during GKC report suppresssion
  vassal-app/src/main/java/VASSAL/counters/Deck.java
Labels: 3.6.0, Review-Changes Complete

#884 3.6 - 14376 - Inventory window allows a hotkey for Refresh
  vassal-app/src/main/java/VASSAL/build/module/Inventory.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: 3.6.0, Review-In Progress

#890 3.5.6 - 14386 - Don't show bogus 'module saved' confirmations if save was cancelled by user at a dialog.
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/tools/ArchiveWriter.java
  vassal-app/src/test/resources/clirr-ignored-differences.xml
Labels: 3.5.6, Ready for Review

#891 14386 PART DEUX - huh huh, WHOOPS!
  vassal-app/src/main/java/VASSAL/tools/ArchiveWriter.java
Labels: 3.5.6

#887 3.6 - Default Font Size change
  vassal-app/src/main/java/VASSAL/launch/StartUp.java
  vassal-app/src/main/java/VASSAL/preferences/Prefs.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: 3.6.0, Review-Changes Complete

#894 3.6 - (Font Size adjustment) 0 to use 'default' java awt fonts
  vassal-app/src/main/java/VASSAL/launch/StartUp.java
Labels: 3.6.0, Review-In Progress

#881 3.6 - 14372 - OH BLESSED DAY! Duplicate a copy of component 'in place' in editor!
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: 3.6.0, Review-Changes Complete

#892 3.5.6 - 14337 - Allow non-docking-Palettes to handle keystrokes properly when they have focus.
  vassal-app/src/main/java/VASSAL/build/module/PieceWindow.java
Labels: 3.5.6, Ready for Review

#882 3.6 - 14373 - (and 1944!) - HELL YES! Drag-and-drop for Editor items.
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
  vassal-app/src/main/java/VASSAL/configure/ExtensionTree.java
Labels: 3.6.0, Review-In Progress

#867 Log connection failures
  vassal-app/src/main/java/VASSAL/tools/BugDialog.java
Labels: 3.5.6

#896 3.5.6 - 14271 - notes window is a keystrokesource so that it won't "eat" keys
  vassal-app/src/main/java/VASSAL/build/module/NotesWindow.java
Labels: 3.5.6

#897 14388-Add Scrollbars to Prefs Dialog when needed.
  vassal-app/src/main/java/VASSAL/configure/BooleanConfigurer.java
  vassal-app/src/main/java/VASSAL/preferences/PrefsEditor.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: 3.6.0, Ready for Review

#885 3.6 - 14377 - Map Windows - non-toggle hotkeys to show and hide
  vassal-app/src/main/java/VASSAL/build/module/Map.java
  vassal-app/src/main/java/VASSAL/configure/PropertiesWindow.java
  vassal-app/src/main/java/VASSAL/tools/LaunchButton.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: 3.6.0, Review-In Progress

#798 3.6 - 14278 - Increased # of default zoom levels (since modern monitors mean people use vassal at a wider variety of resolutions)
  vassal-app/src/main/java/VASSAL/build/module/map/Zoomer.java
Labels: 3.6.0, Awaiting Testing/Feedback

#901 3.6 - 14372 - This finishes up Duplicate/Insert for Extensions
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
  vassal-app/src/main/java/VASSAL/configure/ExtensionTree.java
Labels: 3.6.0, Review-Changes Complete

#902 3.6 - FOLDERS!!!! YEEEEEEEE-HAW!!!!
  vassal-app/src/main/java/VASSAL/build/AbstractBuildable.java
  vassal-app/src/main/java/VASSAL/build/AbstractConfigurable.java
  vassal-app/src/main/java/VASSAL/build/AbstractFolder.java
  vassal-app/src/main/java/VASSAL/build/Builder.java
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/build/module/DiceButton.java
  vassal-app/src/main/java/VASSAL/build/module/Map.java
  vassal-app/src/main/java/VASSAL/build/module/PrototypesContainer.java
  vassal-app/src/main/java/VASSAL/build/module/SpecialDiceButton.java
  vassal-app/src/main/java/VASSAL/build/module/ToolbarMenu.java
  vassal-app/src/main/java/VASSAL/build/module/folder/DeckSubFolder.java
  vassal-app/src/main/java/VASSAL/build/module/folder/GlobalPropertyFolder.java
  vassal-app/src/main/java/VASSAL/build/module/folder/MapSubFolder.java
  vassal-app/src/main/java/VASSAL/build/module/folder/ModuleSubFolder.java
  vassal-app/src/main/java/VASSAL/build/module/folder/PrototypeFolder.java
  vassal-app/src/main/java/VASSAL/build/module/map/CounterDetailViewer.java
  vassal-app/src/main/java/VASSAL/build/module/map/DeckGlobalKeyCommand.java
  vassal-app/src/main/java/VASSAL/build/module/map/DrawPile.java
  vassal-app/src/main/java/VASSAL/build/module/map/Flare.java
  vassal-app/src/main/java/VASSAL/build/module/map/GlobalMap.java
  vassal-app/src/main/java/VASSAL/build/module/map/LOS_Thread.java
  vassal-app/src/main/java/VASSAL/build/module/map/MapShader.java
  vassal-app/src/main/java/VASSAL/build/module/map/MassKeyCommand.java
  vassal-app/src/main/java/VASSAL/build/module/map/SetupStack.java
  vassal-app/src/main/java/VASSAL/build/module/properties/GlobalProperties.java
  vassal-app/src/main/java/VASSAL/build/module/properties/GlobalProperty.java
  vassal-app/src/main/java/VASSAL/i18n/ComponentI18nData.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: 3.6.0, Ready for Review

#906 3.5.6 - 14401 - cancelling scenario load during wizard shouldn't show success message
  vassal-app/src/main/java/VASSAL/build/module/GameState.java
Labels: 3.5.6, Ready for Review

#910 Fix folder duplication crash in prototypes, and make insert go 'above…
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
Labels: 3.6.0, Ready for Review, bug

#863 3.6 - 14341 - Ability to specify Return-to-Deck target as an expression
  vassal-app/src/main/java/VASSAL/configure/DeckSelectionConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/GlobalCommandTargetConfigurer.java
  vassal-app/src/main/java/VASSAL/counters/ReturnToDeck.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: 3.6.0, Review-Changes Complete

#915 MassPieceUploader adoc clarification
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/MassPieceLoader.adoc
Labels: 3.6.0, Review-Query

#914 14408 - Write directily to the output file and lock it
  vassal-app/src/main/java/VASSAL/tools/io/ZipWriter.java
Labels: 3.5.6

#913 1949-Add 'Stack Normally' option Does Not Stack trait
  vassal-app/src/main/java/VASSAL/build/module/GameRefresher.java
  vassal-app/src/main/java/VASSAL/counters/Immobilized.java
  vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java
  vassal-app/src/main/java/VASSAL/counters/Stack.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-app/src/test/java/VASSAL/counters/ImmobilizedSerializeTest.java
  vassal-app/src/test/java/VASSAL/counters/ImmobilizedTest.java
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/NonStacking.adoc
Labels: 3.6.0, Ready for Review

#919 14423 - True is a better always-active default for brand new Layer traits
  vassal-app/src/main/java/VASSAL/counters/Embellishment.java
Labels: 3.6.0, Review-In Progress

#900 14394 - DGKC option to suppress or not suppress messages
  vassal-app/src/main/java/VASSAL/build/module/map/DeckGlobalKeyCommand.java
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/DeckGlobalKeyCommand.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/DeckGlobalKeyCommand.png
Labels: 3.6.0, Review-Changes Complete
