Repository vassalengine/vassal, pull requests merged in 2021-05, with the labels that each got.

#921 10114 - ArrayIndexOutOfBoundsException in SecretNotesController
  vassal-app/src/main/java/VASSAL/build/module/noteswindow/SecretNotesController.java
Labels: 3.5.6, Ready for Review

#920 14418 Mass Piece Loader paste correct type of Layer trait
  vassal-app/src/main/java/VASSAL/counters/MassPieceLoader.java
  vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java
Labels: 3.5.6, Ready for Review

#926 14452 - Don't throw exception on Bad Module Data when syntax error in a user-provided regex
  vassal-app/src/main/java/VASSAL/counters/GlobalCommand.java
Labels: 3.5.6

#925 14440 for 3.5.6
  vassal-app/src/main/java/VASSAL/build/module/GameRefresher.java
Labels: 3.5.6

#911 3.6 - Mats & Cargo - "Pieces that loosely prefer to move together"
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/build/module/BasicCommandEncoder.java
  vassal-app/src/main/java/VASSAL/build/module/map/KeyBufferer.java
  vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java
  vassal-app/src/main/java/VASSAL/counters/FreeRotator.java
  vassal-app/src/main/java/VASSAL/counters/Mat.java
  vassal-app/src/main/java/VASSAL/counters/MatCargo.java
  vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java
  vassal-app/src/main/java/VASSAL/counters/PieceFinder.java
  vassal-app/src/main/java/VASSAL/counters/Pivot.java
  vassal-app/src/main/java/VASSAL/counters/SendToLocation.java
  vassal-app/src/main/java/VASSAL/counters/Translate.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: 3.6.0, Ready for Review

#923 14451 - Wizard/Password flow more intuitive especially w/r/t skipping
  vassal-app/src/main/java/VASSAL/build/module/WizardSupport.java
  vassal-app/src/main/java/VASSAL/tools/UsernameAndPasswordDialog.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: 3.5.6

#928 Mat Touchups - proper default names, proper default checkbox, and don't put spurious description in piece definer's version of the name
  vassal-app/src/main/java/VASSAL/counters/Mat.java
  vassal-app/src/main/java/VASSAL/counters/MatCargo.java
  vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java
Labels: 3.6.0, Ready for Review

#929 14464 - Scaling factors for Layers and Non-Rectangular
  vassal-app/src/main/java/VASSAL/build/module/BasicCommandEncoder.java
  vassal-app/src/main/java/VASSAL/counters/Embellishment.java
  vassal-app/src/main/java/VASSAL/counters/NonRectangular.java
  vassal-app/src/main/java/VASSAL/tools/SequenceEncoder.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Layer.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/NonRectangular.adoc
Labels: 3.6.0, Ready for Review

#930 14460 - Catch infinite loops in Layer following expression and provide hint to reason
  vassal-app/src/main/java/VASSAL/counters/Embellishment.java
  vassal-app/src/main/java/VASSAL/tools/RecursionLimitException.java
  vassal-app/src/main/java/VASSAL/tools/RecursionLimiter.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: 3.5.6, Ready for Review

#934 14468 - CounterDetailViewer fix
  vassal-app/src/main/java/VASSAL/build/module/map/CounterDetailViewer.java
Labels: 3.5.6

#935 14456 - Fix Concurrent List modification exception
  vassal-app/src/main/java/VASSAL/build/module/GameState.java
Labels: 3.5.6, Ready for Review

#936 14461 - Fix exotic TableInfo interaction with search
  vassal-app/src/main/java/VASSAL/counters/TableInfo.java
Labels: 3.5.6

#932 Mat Documentation
  vassal-app/src/main/java/VASSAL/counters/MatCargo.java
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/GamePiece.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Mat.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/MatCargo.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/Mat.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/Mat2.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/MatCargo.png
Labels: 3.6.0, Ready for Review

#939 10755 - Don't infinite loop while reporting one
  vassal-app/src/main/java/VASSAL/counters/CalculatedProperty.java
Labels: 3.5.6, Ready for Review

#940 14261 - fix infinite loop protection for Labeler
  vassal-app/src/main/java/VASSAL/counters/Labeler.java
Labels: 3.5.6

#933 Updated comments in MatCargo.java
  vassal-app/src/main/java/VASSAL/counters/MatCargo.java
Labels: 3.6.0, Review-Changes Complete

#942 14453 - friendlier message when Load Deck attempts to load an incompatible deck
  vassal-app/src/main/java/VASSAL/counters/Deck.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: 3.5.6, Ready for Review

#943 2623 - Can Rotate trait respects mask image when sides change
  vassal-app/src/main/java/VASSAL/counters/Obscurable.java
Labels: 3.5.6, Ready for Review

#948 14502 - Don't use RandomAccessFile.readLine() for tailing the errorLog
  vassal-app/src/main/java/VASSAL/tools/io/Tailer.java
Labels: 3.5.6

#938 Password UX improvements (aka "Just shoot me now")
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/build/module/BasicCommandEncoder.java
  vassal-app/src/main/java/VASSAL/build/module/ObscurableOptions.java
  vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java
  vassal-app/src/main/java/VASSAL/build/module/WizardSupport.java
  vassal-app/src/main/java/VASSAL/build/module/chessclockcontrol/ChessClock.java
  vassal-app/src/main/java/VASSAL/build/module/map/TextSaver.java
  vassal-app/src/main/java/VASSAL/build/module/noteswindow/PrivateNotesController.java
  vassal-app/src/main/java/VASSAL/build/module/noteswindow/SecretNotesController.java
  vassal-app/src/main/java/VASSAL/command/MoveTracker.java
  vassal-app/src/main/java/VASSAL/counters/PlayerAccess.java
  vassal-app/src/main/java/VASSAL/counters/Restricted.java
  vassal-app/src/main/java/VASSAL/counters/Translate.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: 3.5.6, 3.6.0, Ready for Review

#950 14484 - Set extension as edited when it's being edited, not the module
  vassal-app/src/main/java/VASSAL/launch/ModuleManagerWindow.java
Labels: 3.5.6

#941 14477 - MouseoverStackViewer show a single card when used in Player Hand Window
  vassal-app/src/main/java/VASSAL/build/module/map/CounterDetailViewer.java
Labels: 3.5.6, Ready for Review

#951 14505 - Don't clobber the initial state of the EditExtensionLaunchAction
  vassal-app/src/main/java/VASSAL/launch/ModuleManagerWindow.java
Labels: 3.5.6

#949 14503 - Set errorLog encoding to UTF-8 explicitly
  vassal-app/src/main/resources/logback.xml
  vassal-app/src/test/resources/logback.xml
Labels: 3.5.6

#953 14469 - URL-encode high Unicode paths for ProcessBuilder on Windows (blech!)
  vassal-app/src/main/java/VASSAL/launch/LaunchRequest.java
  vassal-app/src/main/java/VASSAL/launch/ModuleManagerUpdateHelper.java
  vassal-app/src/main/java/VASSAL/launch/TilingHandler.java
  vassal-app/src/main/java/VASSAL/tools/image/tilecache/ZipFileImageTiler.java
  vassal-app/src/main/java/VASSAL/tools/io/ArgEncoding.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL_de.properties
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL_es.properties
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL_fr.properties
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL_it.properties
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL_ja.properties
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL_nl.properties
  vassal-app/src/test/resources/clirr-ignored-differences.xml
Labels: 3.5.6

#957 14506 - Fixed exception opening just-added piece palette
  vassal-app/src/main/java/VASSAL/build/module/PieceWindow.java
Labels: 3.5.6

#955 14325 'Option Deux' - Don't remove tile cache when removing module
  vassal-app/src/main/java/VASSAL/launch/ModuleManagerWindow.java
Labels: 3.5.6, Ready for Review

#959 14518 - Check that the event is from the map's window before zooming
  vassal-app/src/main/java/VASSAL/build/module/map/Zoomer.java
Labels: 3.5.6

#961 14526 - Don't try rendering empty labels
  vassal-app/src/main/java/VASSAL/tools/image/LabelUtils.java
Labels: 3.5.7
