Repository vassalengine/vassal, pull requests merged in 2021-08, with the labels that each got.

#10277 10277 - When editing an IrregularGrid, start the map view somewhere near the grid or its parent Zone
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/RegionGrid.java
Labels: Ready to Merge

#10275 10276 Expose property if we're currently drawing Counter Detail Viewer
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/build/module/map/CounterDetailViewer.java
  vassal-doc/src/main/designerguide/maps-and-boards.adoc
Labels: Ready to Merge

#10271 9973 - Deck supports configurable strings for Draw Multiple, Draw Specific, Face Up, Face Down
  vassal-app/src/main/java/VASSAL/build/module/map/DrawPile.java
  vassal-app/src/main/java/VASSAL/configure/AutoConfigurer.java
  vassal-app/src/main/java/VASSAL/counters/Deck.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: Ready to Merge

#10270 10273 Mat Cargo can be set to detect mats way from their exact center
  vassal-app/src/main/java/VASSAL/counters/MatCargo.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/MatCargo.adoc
Labels: Ready to Merge

#10269 10272 Don't auto-name new regions a long string
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/Region.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: Ready to Merge

#10285 Some additional useful properties for Mats and Mat Cargo, along with documentation
  vassal-app/src/main/java/VASSAL/counters/BasicPiece.java
  vassal-app/src/main/java/VASSAL/counters/Delete.java
  vassal-app/src/main/java/VASSAL/counters/Mat.java
  vassal-app/src/main/java/VASSAL/counters/MatCargo.java
  vassal-app/src/main/java/VASSAL/counters/Replace.java
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Mat.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/MatCargo.adoc
Labels: Ready for Review

#916 10034 - MassPieceLoader - do not create empty layer levels
  vassal-app/src/main/java/VASSAL/counters/MassPieceLoader.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/MassPieceLoader.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/MassPieceLoader-2.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/MassPieceLoader-3.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/MassPieceLoader.png
Labels: Ready to Merge

#10294 Let FreeRotator start with a specific angle index
  vassal-app/src/main/java/VASSAL/counters/FreeRotator.java
Labels: Review-Changes Complete

#10292 Properties for OldMat, OldMatID, etc.
  vassal-app/src/main/java/VASSAL/counters/BasicPiece.java
  vassal-app/src/main/java/VASSAL/counters/Decorator.java
  vassal-app/src/main/java/VASSAL/counters/Mat.java
  vassal-app/src/main/java/VASSAL/counters/MatCargo.java
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/BasicPiece.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/MatCargo.adoc
Labels: Review-Changes Complete

#10297 10297 - EDITOR - After duplicating an item in the Editor and saving it, select the duplicate
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
Labels: Ready for Review

#10296 6130 Grid Numbering dialog can appear blank when grid size is very large
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/HexGridNumbering.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/RegularGridNumbering.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/SquareGridNumbering.java
Labels: Ready for Review

#10329 Various Audit Trail fixes
  vassal-app/src/main/java/VASSAL/counters/Embellishment.java
  vassal-app/src/main/java/VASSAL/script/ExpressionInterpreter.java
  vassal-app/src/main/java/VASSAL/script/expression/AuditTrail.java
  vassal-app/src/main/java/VASSAL/script/expression/Expression.java
Labels: Ready for Review

#10289 9979 Deck Sort Command, Deck Send Command
  vassal-app/src/main/java/VASSAL/build/module/folder/DeckSubFolder.java
  vassal-app/src/main/java/VASSAL/build/module/map/DrawPile.java
  vassal-app/src/main/java/VASSAL/build/module/map/deck/AbstractDeckKeyCommand.java
  vassal-app/src/main/java/VASSAL/build/module/map/deck/DeckKeyCommand.java
  vassal-app/src/main/java/VASSAL/build/module/map/deck/DeckSendKeyCommand.java
  vassal-app/src/main/java/VASSAL/build/module/map/deck/DeckSortKeyCommand.java
  vassal-app/src/main/java/VASSAL/build/module/map/deck/SortParameter.java
  vassal-app/src/main/java/VASSAL/build/module/map/deck/SortParameterArrayConfigurer.java
  vassal-app/src/main/java/VASSAL/build/module/map/deck/SortParameterComparator.java
  vassal-app/src/main/java/VASSAL/build/module/map/deck/SortParameterConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/AutoConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/BooleanConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/NamedHotKeyConfigurer.java
  vassal-app/src/main/java/VASSAL/counters/Deck.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Deck.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/DeckSendKeyCommand.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/DeckSortKeyCommand.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/DeckAdd.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/DeckSendKeyCommand.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/DeckSendKeyCommand2.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/DeckSendKeyCommand3.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/DeckSortKeyCommand.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/DeckSortKeyCommand2.png
Labels: Ready for Review

#10355 10095 - Make PlayerRoster auto-configure instead of using a custom configurer
  vassal-app/src/main/java/VASSAL/build/module/DiceButton.java
  vassal-app/src/main/java/VASSAL/build/module/Map.java
  vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java
Labels: Ready for Review
