Repository vassalengine/vassal, pull requests merged in 2021-11, with the labels that each got.

#10667 6024 Private Message windows no longer prompt to ignore every time you close them. Incoming private messages do not grab focus.
  vassal-app/src/main/java/VASSAL/chat/PrivMsgCommand.java
  vassal-app/src/main/java/VASSAL/chat/PrivateChatManager.java
  vassal-app/src/main/java/VASSAL/chat/ui/PrivateMessageAction.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: Ready for Review

#10663 10333 - Fix occasional draw-side exceptions during loading game and saving screenshots.
  vassal-app/src/main/java/VASSAL/build/module/map/StackMetrics.java
  vassal-app/src/main/java/VASSAL/counters/Stack.java
Labels: Ready for Review

#10673 10456 - Added Game Refresher documentation
  vassal-app/src/main/java/VASSAL/build/module/GameRefresher.java
  vassal-app/src/main/java/VASSAL/configure/RemoveUnusedImagesDialog.java
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Editor.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Expression.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/ExpressionBuilder.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/GameModule.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/GameRefresher.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Preferences.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/PropertyMatchExpression.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/RemoveUnusedImages.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/SavedGameUpdater.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Tools.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/GameRefresher.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/RemoveUnusedImages.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/SavedGameUpdater.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/index.adoc
Labels: Ready to Merge

#10681 6557 - Better documented pieceName vs PieceName
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/BasicPiece.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Label.adoc
Labels: documentation, Ready to Merge

#10679 9800 - Fixed bug where Place Marker, Send-to-Location, and Translate traits didn't always repaint maps
  vassal-app/src/main/java/VASSAL/counters/PlaceMarker.java
  vassal-app/src/main/java/VASSAL/counters/SendToLocation.java
  vassal-app/src/main/java/VASSAL/counters/Translate.java
Labels: Ready to Merge

#10678 9759 - UNDO of movement will no longer deny lone stackable pieces their own stack (fixes some obscure stack-related bugs)
  vassal-app/src/main/java/VASSAL/command/MovePiece.java
Labels: Ready to Merge

#10671 8589 Calculate Hex Range correctly, regardless of hex shape.
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/HexGrid.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/HexGridNumbering.java
  vassal-app/src/main/java/VASSAL/tools/hex/Hex.java
  vassal-app/src/main/java/VASSAL/tools/hex/OffsetCoord.java
Labels: Ready for Review

#10652 10652 - Zone Editor shows coordinates of vertices while editing
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/PolygonEditor.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/Zone.java
Labels: Ready to Merge

#10672 10672 Multiplayer Server controls have improved feedback / UX
  vassal-app/src/main/java/VASSAL/chat/ui/BasicChatControlsInitializer.java
  vassal-app/src/main/java/VASSAL/chat/ui/ChatServerControls.java
  vassal-app/src/main/java/VASSAL/chat/ui/JoinRoomAction.java
  vassal-app/src/main/java/VASSAL/chat/ui/RoomInteractionControlsInitializer.java
  vassal-app/src/main/java/VASSAL/chat/ui/SimpleStatusControlsInitializer.java
  vassal-app/src/main/java/VASSAL/chat/ui/SynchAction.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: Ready to Merge

#10683 10509 - Fix bug in DiceButton 'Keep Dice' option
  vassal-app/src/main/java/VASSAL/build/module/DiceButton.java
Labels: Ready for Review

#10682 4400 - Move Camera Button
  vassal-app/src/main/java/VASSAL/build/module/Map.java
  vassal-app/src/main/java/VASSAL/build/module/map/MoveCameraButton.java
  vassal-app/src/main/java/VASSAL/configure/PropertyExpression.java
  vassal-app/src/main/java/VASSAL/counters/SendToLocation.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Map.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/MoveCameraButton.png
Labels: Ready for Review

#10696 9981 - Global Key Commands - "Within a Deck, select Fixed number of pieces" field now supports expressions
  vassal-app/src/main/java/VASSAL/build/module/map/DeckGlobalKeyCommand.java
  vassal-app/src/main/java/VASSAL/build/module/map/MassKeyCommand.java
  vassal-app/src/main/java/VASSAL/counters/CounterGlobalKeyCommand.java
  vassal-app/src/main/java/VASSAL/counters/GlobalCommand.java
  vassal-app/src/main/java/VASSAL/tools/imports/adc2/ADC2Module.java
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/GlobalKeyCommand.adoc
Labels: Ready for Review

#10701 5090 - Zone defining - when dragging a square to define initial zone, dragging at edge of screen scrolls
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/PolygonEditor.java
Labels: Ready to Merge

#10702 10698 - When inventory grouping specifies properties that aren't internally strings ... don't break
  vassal-app/src/main/java/VASSAL/build/module/Inventory.java
Labels: Ready to Merge

#10703 9571 - Correct inconsistency in use of GetConfigureBoard
  vassal-app/src/main/java/VASSAL/build/module/map/SetupStack.java
Labels: Ready to Merge

#10711 10711 - When rotating a mat, jointly rotating cargo should prefer to stay with current mat
  vassal-app/src/main/java/VASSAL/counters/FreeRotator.java
Labels: Ready to Merge

#10674 9890 - Startup Global Key Commands - always fire in order, can't be undone, and can be configured to e.g. "once per game"
  vassal-app/src/main/java/VASSAL/build/module/BasicLogger.java
  vassal-app/src/main/java/VASSAL/build/module/GameState.java
  vassal-app/src/main/java/VASSAL/build/module/PredefinedSetup.java
  vassal-app/src/main/java/VASSAL/build/module/StartupGlobalKeyCommand.java
  vassal-app/src/main/java/VASSAL/build/module/WizardSupport.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Map.adoc
Labels: Review-Changes Complete

#10700 5489 - Improved bug dialog text
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: Ready to Merge

#10686 Deck fill out the rest of the commands with hotkeys and report formats
  vassal-app/src/main/java/VASSAL/build/module/Inventory.java
  vassal-app/src/main/java/VASSAL/build/module/map/DrawPile.java
  vassal-app/src/main/java/VASSAL/build/module/map/MenuDisplayer.java
  vassal-app/src/main/java/VASSAL/build/module/map/SetupStack.java
  vassal-app/src/main/java/VASSAL/build/widget/PieceSlot.java
  vassal-app/src/main/java/VASSAL/counters/Deck.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: Ready to Merge

#10691 10691 - Mouseover Stack Viewer - Unstatic a naughty field in CounterDetailViewer, and add ability to count face down cards in a deck
  vassal-app/src/main/java/VASSAL/build/module/map/CounterDetailViewer.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Hideable.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Layer.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/MarkMoved.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Mask.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/MouseOver.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/MovementTrail.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/NonStacking.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/PieceWindow.adoc
Labels: Review-Changes Complete

#10718 10718 - NPE due to dropTargetSelector being unset
  vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java
Labels: Ready for Review

#10717 Deck access - allow access to decks to be restricted by player
  vassal-app/src/main/java/VASSAL/build/module/map/DrawPile.java
  vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java
  vassal-app/src/main/java/VASSAL/counters/Deck.java
  vassal-app/src/main/java/VASSAL/counters/GlobalCommand.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: Ready to Merge

#10699 6476 Repositioning Stacks/Decks optionally draws ghosted images of other stacks/decks
  vassal-app/src/main/java/VASSAL/build/module/map/SetupStack.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: Review-Changes Complete

#10726 Unbreak DGKC
  vassal-app/src/main/java/VASSAL/build/module/map/DeckGlobalKeyCommand.java
  vassal-app/src/main/java/VASSAL/counters/GlobalCommand.java
Labels: Ready for Review

#10728 10728 Allow 'Prompt' Dice Button values to be locked by designer
  vassal-app/src/main/java/VASSAL/build/module/DiceButton.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/DiceButton.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/DiceButton4.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/DiceButton5.png
Labels: Ready for Review

#10730 10730 - DOCS - Improve Game Piece Palette doc per forum suggestion (AsciiDoc file only)
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/PieceWindow.adoc
Labels: documentation, Ready to Merge

#10719 9063 - Deck Refresher
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/build/module/BasicLogger.java
  vassal-app/src/main/java/VASSAL/build/module/GameRefresher.java
  vassal-app/src/main/java/VASSAL/build/module/GameState.java
  vassal-app/src/main/java/VASSAL/build/module/map/BoardPicker.java
  vassal-app/src/main/java/VASSAL/build/module/map/DrawPile.java
  vassal-app/src/main/java/VASSAL/build/module/map/SetupStack.java
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
  vassal-app/src/main/java/VASSAL/configure/RefreshPredefinedSetupsDialog.java
  vassal-app/src/main/java/VASSAL/counters/Deck.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/GameRefresher.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/SavedGameUpdater.adoc
Labels: Ready for Review

#10731 9635 - Add description fields to most important editor components
  vassal-app/src/main/java/VASSAL/build/AbstractFolder.java
  vassal-app/src/main/java/VASSAL/build/AbstractToolbarItem.java
  vassal-app/src/main/java/VASSAL/build/Widget.java
  vassal-app/src/main/java/VASSAL/build/module/ChartWindow.java
  vassal-app/src/main/java/VASSAL/build/module/ChessClockControl.java
  vassal-app/src/main/java/VASSAL/build/module/GlobalOptions.java
  vassal-app/src/main/java/VASSAL/build/module/Map.java
  vassal-app/src/main/java/VASSAL/build/module/NotesWindow.java
  vassal-app/src/main/java/VASSAL/build/module/PieceWindow.java
  vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java
  vassal-app/src/main/java/VASSAL/build/module/PredefinedSetup.java
  vassal-app/src/main/java/VASSAL/build/module/PrototypeDefinition.java
  vassal-app/src/main/java/VASSAL/build/module/SpecialDiceButton.java
  vassal-app/src/main/java/VASSAL/build/module/chessclockcontrol/ChessClock.java
  vassal-app/src/main/java/VASSAL/build/module/map/DrawPile.java
  vassal-app/src/main/java/VASSAL/build/module/map/Flare.java
  vassal-app/src/main/java/VASSAL/build/module/map/LayerControl.java
  vassal-app/src/main/java/VASSAL/build/module/map/LayeredPieceCollection.java
  vassal-app/src/main/java/VASSAL/build/module/turn/TurnComponent.java
  vassal-app/src/main/java/VASSAL/build/module/turn/TurnTracker.java
  vassal-app/src/main/java/VASSAL/build/widget/Chart.java
  vassal-app/src/main/java/VASSAL/build/widget/HtmlChart.java
  vassal-app/src/main/java/VASSAL/build/widget/ListWidget.java
  vassal-app/src/main/java/VASSAL/build/widget/MapWidget.java
  vassal-app/src/main/java/VASSAL/build/widget/PanelWidget.java
  vassal-app/src/main/java/VASSAL/build/widget/TabWidget.java
  vassal-app/src/main/java/VASSAL/configure/ComponentDescription.java
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
Labels: Ready for Review

#10734 10734 - No refresh allowed during replay
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/build/module/GameRefresher.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: Ready for Review

#10727 Module "Debug" Window
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/build/module/Map.java
  vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java
  vassal-app/src/main/java/VASSAL/launch/PlayerWindow.java
  vassal-app/src/main/java/VASSAL/tools/DebugControls.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: Ready for Review, Review-Changes Complete

#10736 6524 - 'Deal cards out' to other players
  vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java
  vassal-app/src/main/java/VASSAL/counters/Obscurable.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Mask.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/Mask2.png
Labels: Ready for Review

#10750 10750 - Place Marker should put stacking markers in a stack (even if parent marker is non-stacking)
  vassal-app/src/main/java/VASSAL/counters/PlaceMarker.java
Labels: Ready to Merge

#10751 10751 - Better description of Player Hand
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/PlayerHand.adoc
Labels: documentation, Ready to Merge

#10752 9118 - Fixed bug where Deck 'count expressions' wouldn't count beanshell, only old-style (now will count either)
  vassal-app/src/main/java/VASSAL/counters/Deck.java
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Deck.adoc
Labels: Ready to Merge

#10753 10076 - Clarify documentation of sum(PropertyName) in Mouseover
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/MouseOver.adoc
Labels: documentation, Ready to Merge

#10754 9206 - remove incorrect FIXME markers
  vassal-app/src/main/java/VASSAL/build/module/BasicLogger.java
Labels: Ready to Merge

#10749 10749 - Move Camera Button can also change Zoom
  vassal-app/src/main/java/VASSAL/build/module/map/MoveCameraButton.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Map.adoc
Labels: Ready to Merge

#10757 10757 - Prevent undo of Refresh Counters from causing contents of Decks to disappear
  vassal-app/src/main/java/VASSAL/build/module/GameRefresher.java
  vassal-app/src/main/java/VASSAL/counters/Deck.java
Labels: Review-Changes Complete

#10755 9487 - When switching sides, close private hands/windows that we no longer have access to.
  vassal-app/src/main/java/VASSAL/build/module/PrivateMap.java
Labels: Ready to Merge

#10760 10760 - Further unbreak local-only trails
  vassal-app/src/main/java/VASSAL/counters/Footprint.java
Labels: Ready to Merge

#10777 Fix duplicate DragShadow for Cargo at zoom < 100%
  vassal-app/src/main/java/VASSAL/counters/Mat.java
Labels: Ready for Review

#10764 10764 - Server text improvements
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: documentation, Ready to Merge

#10784 4391 - LOS thread thickness is adjustable
  vassal-app/src/main/java/VASSAL/build/module/map/LOS_Thread.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: Ready for Review

#10793 10792 - Fix NPE (Always cache bounding box)
  vassal-app/src/main/java/VASSAL/build/module/map/SetupStack.java
Labels: Ready for Review

#10774 10774 - Validation messages when Movement Trail traits placed inside of Rotate, Pivot, or Mat Cargo
  vassal-app/src/main/java/VASSAL/counters/Footprint.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: Review-Changes Complete

#10783 6195 - Don't thrash Deck properties when just rearranging order
  vassal-app/src/main/java/VASSAL/counters/Deck.java
  vassal-app/src/main/java/VASSAL/counters/Stack.java
Labels: Ready for Review

#10772 10772 Allow module images to have English localizations
  vassal-app/src/main/java/VASSAL/i18n/I18nResourcePathFinder.java
Labels: Ready for Review

#10762 10762 - Fix sum() collision with beanshell for e.g. Rollovers, etc by introducing sumProperties() alternative
  vassal-app/src/main/java/VASSAL/build/module/properties/SumProperties.java
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/MouseOver.adoc
Labels: Ready for Review

#10763 4479 - Can Shift+Click and Ctrl+Click on Game Piece Palette, allowing groups of pieces to be dragged onto the map.
  vassal-app/src/main/java/VASSAL/build/widget/PieceSlot.java
  vassal-app/src/main/java/VASSAL/counters/KeyBuffer.java
Labels: Review-Changes Complete

#10781 9209 - Beanshell expressions now support GetString() to get value of property "but always as a string".
  vassal-app/src/main/java/VASSAL/configure/BeanShellFunctionMenu.java
  vassal-app/src/main/java/VASSAL/script/ExpressionInterpreter.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-app/src/main/resources/VASSAL/script/init_expression.bsh
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Expression.adoc
Labels: Ready for Review

#10766 9366 - Inventory window allows 3-level zoom
  vassal-app/src/main/java/VASSAL/build/module/Inventory.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: Ready for Review

#10782 9124 - Property incrementers no longer apply turned-off min/max constraints
  vassal-app/src/main/java/VASSAL/build/module/properties/IncrementProperty.java
Labels: Ready for Review

#10794 Action Buttons now respect rotation. Also fixed a bug in getOuter()
  vassal-app/src/main/java/VASSAL/counters/ActionButton.java
  vassal-app/src/main/java/VASSAL/counters/Decorator.java
  vassal-app/src/main/java/VASSAL/counters/FreeRotator.java
  vassal-app/src/main/java/VASSAL/counters/MatCargo.java
  vassal-app/src/main/java/VASSAL/counters/Translate.java
Labels: Ready for Review

#10799 10007 - Ctrl/Cmd to select for Does Not Stack
  vassal-app/src/main/java/VASSAL/counters/Immobilized.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/NonStacking.adoc
Labels: Ready for Review

#10800 5569 - Preference to turn off automatic update notification
  vassal-app/src/main/java/VASSAL/launch/ModuleManager.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: Review-Changes Complete

#10796 4496 - Fancier action button definition
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/PolygonConfigurer.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/PolygonEditor.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/Zone.java
  vassal-app/src/main/java/VASSAL/counters/ActionButton.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-app/src/test/resources/clirr-ignored-differences.xml
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/ActionButton.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/ActionButton.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/ActionButtonDefiner.png
Labels: Review-Changes Complete

#10761 10761 - Toolbar button disabler - Buttons on toolbar can be disabled when a specified global property is true
  vassal-app/src/main/java/VASSAL/build/AbstractToolbarItem.java
  vassal-app/src/main/java/VASSAL/build/module/DiceButton.java
  vassal-app/src/main/java/VASSAL/build/module/DoActionButton.java
  vassal-app/src/main/java/VASSAL/build/module/Map.java
  vassal-app/src/main/java/VASSAL/build/module/NotesWindow.java
  vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java
  vassal-app/src/main/java/VASSAL/build/module/SpecialDiceButton.java
  vassal-app/src/main/java/VASSAL/build/module/StartupGlobalKeyCommand.java
  vassal-app/src/main/java/VASSAL/build/module/map/DeckGlobalKeyCommand.java
  vassal-app/src/main/java/VASSAL/build/module/map/ImageSaver.java
  vassal-app/src/main/java/VASSAL/build/module/map/LOS_Thread.java
  vassal-app/src/main/java/VASSAL/build/module/map/LayerControl.java
  vassal-app/src/main/java/VASSAL/build/module/map/MapShader.java
  vassal-app/src/main/java/VASSAL/build/module/map/MassKeyCommand.java
  vassal-app/src/main/java/VASSAL/build/module/map/TextSaver.java
  vassal-app/src/main/java/VASSAL/build/module/properties/ChangePropertyButton.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/DiceButton.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/DoActionButton.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Inventory.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/LineOfSight.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Map.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/MultiActionButton.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/SpecialDiceButton.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Toolbar.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/ToolbarMenu.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/DiceButton.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/DiceButton3.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/DiceButton4.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/DoActionButton.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/DoActionButtonShort.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/GlobalKeyCommand.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/Inventory.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/LOS_Thread.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/MultiActionButton.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/RandomTextButton.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/SpecialDiceButton.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/ToolbarConfig.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/ToolbarMenu.png
Labels: Work In Progress

#10803 10803 Speeds Game Refresh and general performance in modules with many maps defined
  vassal-app/src/main/java/VASSAL/build/GameModule.java
Labels: Ready for Review

#10807 Fix an action button oops
  vassal-app/src/main/java/VASSAL/counters/ActionButton.java
Labels: Ready for Review

#10806 Profiling stuff
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-doc/src/main/designerguide/maps-and-boards.adoc
Labels: Ready for Review

#10808 Misc property lookup optimizations
  vassal-app/src/main/java/VASSAL/counters/Decorator.java
  vassal-app/src/main/java/VASSAL/script/ExpressionInterpreter.java
Labels: Ready for Review

#10810 10795 - protect against no available trait being yet selected
  vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java
Labels: Ready for Review

#10811 Optimization: Check for possible keystrokes in Restrict Commands before evaluating match epression
  vassal-app/src/main/java/VASSAL/counters/RestrictCommands.java
Labels: Ready for Review

#10812 Optimize Single Property Beanshell expressions
  vassal-app/src/main/java/VASSAL/script/expression/BeanShellExpression.java
  vassal-app/src/main/java/VASSAL/script/expression/Expression.java
  vassal-app/src/test/java/VASSAL/script/expression/BeanShellExpressionTest.java
  vassal-app/src/test/java/VASSAL/script/expression/ExpressionTest.java
Labels: Ready for Review

#10815 10814 Fix Dice Button reporting when Keeping and Sorting results
  vassal-app/src/main/java/VASSAL/build/module/DiceButton.java
Labels: Ready for Review

#10818 DrawingMouseoverIndex correctly returned as string. Console now displays null valued properties instead of NPE
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/build/module/Console.java
Labels: Ready for Review

#10826 10826 - Even more fun with Movement Trails
  vassal-app/src/main/java/VASSAL/counters/Footprint.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/MovementTrail.adoc
Labels: Ready for Review

#10828 10828 - Skip All / Skip None buttons for Mass Piece Loader
  vassal-app/src/main/java/VASSAL/counters/MassPieceLoader.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: Ready for Review

#10827 Fix Deck refreshing when running Game Refresher
  vassal-app/src/main/java/VASSAL/build/module/GameRefresher.java
  vassal-app/src/main/java/VASSAL/build/module/map/DrawPile.java
Labels: Ready for Review

#10834 10834 - (Text only) Server text tweaks
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: Ready for Review

#10840 Directly setting coordinates in Zone definer fails to create a Zone
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/PolygonEditor.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/Zone.java
  vassal-app/src/main/java/VASSAL/counters/ActionButton.java
Labels: Ready for Review

#10853 10853 - Prototypes can be selected from popup menu
  vassal-app/src/main/java/VASSAL/counters/UsePrototype.java
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/UsePrototype.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/UsePrototype.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/UsePrototype2.png
Labels: Ready for Review

#10839 10839 - Improved flow for users with blank passwords
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/build/module/GameSetupStep.java
  vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java
  vassal-app/src/main/java/VASSAL/build/module/WizardSupport.java
  vassal-app/src/main/java/VASSAL/launch/LoadModuleAction.java
  vassal-app/src/main/java/VASSAL/launch/Player.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: Ready for Review
