Repository vassalengine/vassal, pull requests merged in 2021-06, with the labels that each got.

#956 14392 - Remove ?s from checkbox preference strings
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: 3.6.0

#952 3.6 - Stay compatible with 3.5 non-rectangular traits as long as possible
  vassal-app/src/main/java/VASSAL/counters/NonRectangular.java
Labels: 3.6.0, Ready for Review

#963 14521 - fix mouseover stack viewer exception with stacks
  vassal-app/src/main/java/VASSAL/build/module/map/CounterDetailViewer.java
Labels: 3.5.7

#967 14540 - Fix isEnabled() forwarding for hotkeys
  vassal-app/src/main/java/VASSAL/tools/KeyStrokeListener.java
Labels: 3.5.7

#966 14238 Improve Validity Checking
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/build/module/Documentation.java
  vassal-app/src/main/java/VASSAL/build/module/GlobalOptions.java
  vassal-app/src/main/java/VASSAL/build/module/Map.java
  vassal-app/src/main/java/VASSAL/build/module/PrototypesContainer.java
  vassal-app/src/main/java/VASSAL/build/module/gamepieceimage/ColorManager.java
  vassal-app/src/main/java/VASSAL/build/module/gamepieceimage/FontManager.java
  vassal-app/src/main/java/VASSAL/build/module/gamepieceimage/GamePieceImageDefinitions.java
  vassal-app/src/main/java/VASSAL/build/module/gamepieceimage/GamePieceLayoutsContainer.java
  vassal-app/src/main/java/VASSAL/build/module/map/CounterDetailViewer.java
  vassal-app/src/main/java/VASSAL/build/module/map/HighlightLastMoved.java
  vassal-app/src/main/java/VASSAL/build/module/map/LayeredPieceCollection.java
  vassal-app/src/main/java/VASSAL/build/module/map/Zoomer.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/Board.java
  vassal-app/src/main/java/VASSAL/configure/MandatoryComponent.java
  vassal-app/src/main/java/VASSAL/configure/SingleChildInstance.java
  vassal-app/src/main/java/VASSAL/configure/ValidationReportDialog.java
  vassal-app/src/main/java/VASSAL/i18n/Localization.java
  vassal-app/src/main/java/VASSAL/script/ScriptContainer.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: 3.6.0, Ready for Review

#971 14479 - GamePieceImages recognized by unused image removal tool
  vassal-app/src/main/java/VASSAL/configure/RemoveUnusedImagesDialog.java
Labels: 3.5.8

#970 14570 Let wizard divider float further right
  vassal-app/src/main/java/VASSAL/build/module/WizardSupport.java
Labels: 3.5.8

#977 14579 Allow standard Layer traits in Mass Piece Loader
  vassal-app/src/main/java/VASSAL/counters/MassPieceLoader.java
  vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: 3.5.8

#983 14596 - Removed unused initial heap configurer for Importer
  vassal-app/src/main/java/VASSAL/launch/ModuleManager.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL_de.properties
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL_es.properties
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL_fr.properties
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL_it.properties
Labels: 3.5.8
