Repository vassalengine/vassal, pull requests merged in 2022-01, with the labels that each got.

#11031 11013 Turn Tracker List configure box missing labels
  vassal-app/src/main/java/VASSAL/build/module/turn/ListTurnLevel.java
Labels: Ready for Review

#11038 11038 Allow 'Use Same Boards' option on Private Map to be removed
  vassal-app/src/main/java/VASSAL/build/module/PrivateMap.java
Labels: Review-Changes Complete

#11039 11039 Display Loaded message instead of Cancelled when refreshing Predefined Setups
  vassal-app/src/main/java/VASSAL/build/module/GameState.java
Labels: Ready for Review

#11049 List key improvements
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
  vassal-app/src/main/java/VASSAL/configure/ListKeyCommandsDialog.java
  vassal-app/src/main/java/VASSAL/launch/EditorWindow.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: Ready for Review

#11052 11025 - Gaurd against ClassCastException when MultiActionButtons change property values
  vassal-app/src/main/java/VASSAL/build/module/ToolbarMenu.java
Labels: Ready for Review

#11053 11053 Suppress Empty Deck Hotkeys when refreshing game
  vassal-app/src/main/java/VASSAL/build/module/GameRefresher.java
Labels: Ready for Review

#11056 11043 - Don't attempt to send to already-hung-up connection
  vassal-app/src/main/java/VASSAL/chat/node/NodeClient.java
Labels: Ready for Review

#11059 11059 - Right Click menu added to Show Error Log window in Module Manager
  vassal-app/src/main/java/VASSAL/launch/ModuleManagerWindow.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: Ready for Review

#11054 11054 - Don't let old versions of PoG load and crash
  vassal-app/src/main/java/VASSAL/launch/Editor.java
  vassal-app/src/main/java/VASSAL/launch/Launcher.java
  vassal-app/src/main/java/VASSAL/launch/Player.java
  vassal-app/src/main/java/VASSAL/tools/ProblemDialog.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: Ready for Review

#11060 11060 - Fixes to various Toolbar Buttons that weren't respecting the "disable-on-global-property" settings
  vassal-app/src/main/java/VASSAL/build/AbstractToolbarItem.java
  vassal-app/src/main/java/VASSAL/build/module/Inventory.java
  vassal-app/src/main/java/VASSAL/build/module/Map.java
  vassal-app/src/main/java/VASSAL/build/module/NotesWindow.java
  vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java
  vassal-app/src/main/java/VASSAL/build/module/SpecialDiceButton.java
  vassal-app/src/main/java/VASSAL/build/module/ToolbarMenu.java
  vassal-app/src/main/java/VASSAL/build/module/map/ImageSaver.java
  vassal-app/src/main/java/VASSAL/build/module/map/LOS_Thread.java
  vassal-app/src/main/java/VASSAL/build/module/map/LayerControl.java
  vassal-app/src/main/java/VASSAL/build/module/map/MapShader.java
  vassal-app/src/main/java/VASSAL/build/module/map/MassKeyCommand.java
  vassal-app/src/main/java/VASSAL/build/module/map/PieceRecenterer.java
  vassal-app/src/main/java/VASSAL/build/module/map/TextSaver.java
  vassal-app/src/main/java/VASSAL/build/module/properties/ChangePropertyButton.java
Labels: Ready for Review

#11062 11062 - Fix problem on Windows where a click at edge made it slowly scroll all the way in that direction
  vassal-app/src/main/java/VASSAL/build/module/Map.java
Labels: Ready for Review

#11070 Documentation updates for DrawingMouseover / DrawingMouseover Index
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/BasicPiece.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/MouseOver.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Properties.adoc
Labels: Ready to Merge

#11073 11073 - Fix situation where Send-to-Location throws exceptions when it can't find target counters
  vassal-app/src/main/java/VASSAL/counters/SendToLocation.java
Labels: Ready for Review

#11075 11069 - Fix crash in Load Deck when an invalid deck file selected in file picker
  vassal-app/src/main/java/VASSAL/counters/Deck.java
Labels: Ready for Review

#11076 11076 - Editor's search function (and List Key Commands) will now "find" the keys for Undo & Step Forward
  vassal-app/src/main/java/VASSAL/build/module/BasicLogger.java
  vassal-app/src/main/java/VASSAL/build/module/GlobalOptions.java
Labels: Ready for Review

#11077 11067 - Fix NPE in SetupStack
  vassal-app/src/main/java/VASSAL/build/module/map/SetupStack.java
Labels: Ready for Review

#11066 "Path" column for List Key Commands
  vassal-app/src/main/java/VASSAL/configure/ListKeyCommandsDialog.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: Ready for Review

#11074 11074 - Support Send-to-Location source/target matching with $...$ expressions
  vassal-app/src/main/java/VASSAL/counters/SendToLocation.java
Labels: Ready for Review, Ready to Merge

#11079 11079 - Main window & map accept Drag-and-Drop for loading saves and logs
  vassal-app/src/main/java/VASSAL/build/module/Chatter.java
  vassal-app/src/main/java/VASSAL/build/module/GameState.java
  vassal-app/src/main/java/VASSAL/build/module/Map.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
  vassal-doc/src/main/userguide/userguide.adoc
Labels: Ready for Review

#11094 11094 - Exclude GamePieceLayout image names from unused image list
  vassal-app/src/main/java/VASSAL/build/module/gamepieceimage/GamePieceLayout.java
Labels: Ready for Review

#11098 11098 - Screenshot "typo" fix for Turn Tracker's global hotkey
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/TurnTrackerGlobalHotkey.png
Labels: Ready to Merge

#11105 11105 - Added missing Editor.SendToLocation.getSendLocation translation key
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: Ready to Merge

#11111 11107 Warn if Decks or Stacks defined before [Map Boards]
  vassal-app/src/main/java/VASSAL/build/module/Map.java
  vassal-app/src/main/java/VASSAL/build/module/map/BoardPicker.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: Ready for Review

#11109 11099 Correct HexGrid range between points within a hex
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/HexGrid.java
Labels: Ready for Review

#11115 11112 - Fix ClassCastException due to Zone properties not accounting for folders
  vassal-app/src/main/java/VASSAL/build/module/properties/ZoneProperty.java
Labels: Ready for Review

#11096 Remove "duplicate this item" option from Game Piece Image
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
Labels: Ready for Review

#11120 Permit hyphens and periods in GamePieceImage names
  vassal-app/src/main/java/VASSAL/build/module/gamepieceimage/GamePieceImage.java
Labels: Ready to Merge

#11121 11121 - Fix problem where undo wasn't allowed when starting a new game with logging turned on
  vassal-app/src/main/java/VASSAL/build/module/BasicLogger.java
Labels: Ready for Review

#11130 11127 - Don't throw exception if there's a drive letter in a filename
  vassal-app/src/main/java/VASSAL/build/GameModule.java
Labels: Ready for Review

#11139 11139 - Deal-to-Other key in Mask Trait now recognized in Search
  vassal-app/src/main/java/VASSAL/counters/Obscurable.java
Labels: Ready for Review

#11156 11156 - Games incorrectly load normally during 'Load Continuation'
  vassal-app/src/main/java/VASSAL/build/module/GameState.java
Labels: Ready for Review
