Repository vassalengine/vassal, pull requests merged in 2022-07, with the labels that each got.

#11542 11540 - Display translated Basic Piece/Basic Name in Scrollable lists in Game Piece Palette
  vassal-app/src/main/java/VASSAL/build/Widget.java
  vassal-app/src/main/java/VASSAL/build/module/PieceWindow.java
  vassal-app/src/main/java/VASSAL/build/widget/PieceSlot.java
  vassal-app/src/main/java/VASSAL/build/widget/TabWidget.java
  vassal-app/src/main/java/VASSAL/i18n/Localization.java
Labels: bug, Ready to Merge

#11510 Updated Opt-in version of the 'Leading Zeros in Integers' handing
  vassal-app/src/main/java/VASSAL/build/module/GlobalOptions.java
  vassal-app/src/main/java/VASSAL/counters/DynamicProperty.java
  vassal-app/src/main/java/VASSAL/script/ExpressionInterpreter.java
  vassal-app/src/main/java/VASSAL/script/expression/Expression.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/GlobalOptions.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/GridNumbering.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/SendToLocation.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/GlobalOptions.png
Labels: Ready to Merge

#11556 11537 Cancel key in Multi-Piece Editor (Edit all contained pieces) correctly backs out with no changes.
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
  vassal-app/src/main/java/VASSAL/configure/EditContainedPiecesAction.java
  vassal-app/src/main/java/VASSAL/counters/MassPieceDefiner.java
  vassal-app/src/main/java/VASSAL/counters/PieceCloner.java
Labels: Ready for Review

#11536 11534 - Add Open all Contained Pieces option
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
  vassal-app/src/main/java/VASSAL/configure/EditContainedPiecesAction.java
  vassal-app/src/main/java/VASSAL/configure/ExtensionTree.java
  vassal-app/src/main/java/VASSAL/configure/OpenContainedPiecesAction.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Editor.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Search.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/configuration_window2.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/search_advanced.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/search_basic.png
Labels: enhancement, Ready for Review

#11546 11546 - Default dialog-closing button behaviors for Enter/Esc
  vassal-app/src/main/java/VASSAL/build/module/Chatter.java
  vassal-app/src/main/java/VASSAL/build/module/GameRefresher.java
  vassal-app/src/main/java/VASSAL/build/module/ModuleExtension.java
  vassal-app/src/main/java/VASSAL/build/module/NotesWindow.java
  vassal-app/src/main/java/VASSAL/build/module/PrototypeDefinition.java
  vassal-app/src/main/java/VASSAL/build/module/map/BoardPicker.java
  vassal-app/src/main/java/VASSAL/build/module/map/SetupStack.java
  vassal-app/src/main/java/VASSAL/build/module/map/Zoomer.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/GridEditor.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/RegionGrid.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/Zone.java
  vassal-app/src/main/java/VASSAL/build/module/noteswindow/SecretNotesController.java
  vassal-app/src/main/java/VASSAL/build/module/turn/ListTurnLevel.java
  vassal-app/src/main/java/VASSAL/build/module/turn/TurnTracker.java
  vassal-app/src/main/java/VASSAL/build/widget/PieceSlot.java
  vassal-app/src/main/java/VASSAL/chat/messageboard/MessageBoardControls.java
  vassal-app/src/main/java/VASSAL/configure/ChooseComponentDialog.java
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
  vassal-app/src/main/java/VASSAL/configure/Configurer.java
  vassal-app/src/main/java/VASSAL/configure/ConfigurerWindow.java
  vassal-app/src/main/java/VASSAL/configure/NamedHotKeyConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/PropertiesWindow.java
  vassal-app/src/main/java/VASSAL/configure/RefreshPredefinedSetupsDialog.java
  vassal-app/src/main/java/VASSAL/configure/StringConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/TextConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/ValidationReportDialog.java
  vassal-app/src/main/java/VASSAL/counters/ActionButton.java
  vassal-app/src/main/java/VASSAL/counters/Deck.java
  vassal-app/src/main/java/VASSAL/counters/Embellishment.java
  vassal-app/src/main/java/VASSAL/counters/MassPieceLoader.java
  vassal-app/src/main/java/VASSAL/counters/MultiImagePicker.java
  vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java
  vassal-app/src/main/java/VASSAL/counters/PieceEditor.java
  vassal-app/src/main/java/VASSAL/counters/ReturnToDeck.java
  vassal-app/src/main/java/VASSAL/i18n/TranslateVassalWindow.java
  vassal-app/src/main/java/VASSAL/i18n/TranslateWindow.java
  vassal-app/src/main/java/VASSAL/preferences/PrefsEditor.java
  vassal-app/src/main/java/VASSAL/script/expression/ExpressionBuilder.java
  vassal-app/src/main/java/VASSAL/script/expression/FunctionBuilder.java
  vassal-app/src/main/java/VASSAL/script/expression/StrBuilder.java
  vassal-app/src/main/java/VASSAL/tools/swing/SwingUtils.java
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/GamePiece.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Layer.adoc
Labels: Ready for Review

#11572 11570 - Update Module Extension window, add missing description.
  vassal-app/src/main/java/VASSAL/build/module/ModuleExtension.java
Labels: Ready for Review

#11573 11564 - Prevent Notes windows always starting open at very last character of note.
  vassal-app/src/main/java/VASSAL/configure/TextConfigurer.java
Labels: Ready for Review

#11585 Expression Builder - enable undo of text
  vassal-app/src/main/java/VASSAL/configure/BeanShellExpressionConfigurer.java
Labels: Ready for Review

#11612 Fix NPE I found (in earlier PR for 3.6.8) - no changelist item needed, bug hasn't shipped
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
Labels: Ready to Merge
