Repository vassalengine/vassal, pull requests merged in 2023-01, with the labels that each got.

#11866 11846 - Protect from null property results during search
  vassal-app/src/main/java/VASSAL/build/AbstractToolbarItem.java
  vassal-app/src/main/java/VASSAL/build/module/ChartWindow.java
  vassal-app/src/main/java/VASSAL/build/module/DoActionButton.java
  vassal-app/src/main/java/VASSAL/build/module/PieceWindow.java
  vassal-app/src/main/java/VASSAL/build/module/map/Zoomer.java
  vassal-app/src/main/java/VASSAL/build/module/turn/TurnTracker.java
Labels: bug, Ready to Merge

#11870 11759 - Do not allow negative number of Dice or Sides
  vassal-app/src/main/java/VASSAL/build/module/DiceButton.java
Labels: bug, Ready for Review

#11871 11452 - Prevent NPE if invalid file specified in img tag
  vassal-app/src/main/java/VASSAL/tools/swing/DataArchiveHTMLEditorKit.java
Labels: bug, Ready for Review

#11867 11813 - NPE in PieceSlot.getLocalizedConfigureName()
  vassal-app/src/main/java/VASSAL/build/widget/PieceSlot.java
Labels: bug, Ready for Review

#11872 11455 - Prevent NPE when adding empty KeyStrokes to list
  vassal-app/src/main/java/VASSAL/configure/NamedKeyStrokeArrayConfigurer.java
Labels: bug, Ready for Review

#11878 11860 - Warn when same piece is both Mat and Mat Cargo
  vassal-app/src/main/java/VASSAL/counters/Mat.java
  vassal-app/src/main/java/VASSAL/counters/MatCargo.java
Labels: Ready for Review

#11877 11748 - NPE when cutting and pasting a prototype folder
  vassal-app/src/main/java/VASSAL/build/module/folder/PrototypeFolder.java
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
Labels: Ready for Review

#11869 11823 - NPE in GameRefresher when refreshing unnamed Decks
  vassal-app/src/main/java/VASSAL/build/module/GameRefresher.java
Labels: bug, Ready for Review

#11882 11879 NPE when cutting and pasting a GlobalPropertyFolder
  vassal-app/src/main/java/VASSAL/build/module/properties/GlobalProperty.java
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
Labels: Ready to Merge

#11890 11890 - NPE when current-stack option used on non-stacking piece
  vassal-app/src/main/java/VASSAL/counters/GlobalCommand.java
Labels: Ready for Review

#11904 Global Key Command fastmatch for Mats fixed to avoid certain trait-order bugs
  vassal-app/src/main/java/VASSAL/counters/GlobalCommand.java
Labels: Ready for Review

#11906 MatCargo's mat detection did unnecessary computations for lack of parentheses
  vassal-app/src/main/java/VASSAL/counters/MatCargo.java
Labels: Ready for Review

#11911 11911 - Debug window shows board-relative coordinates if they are different from the map-relative ones
  vassal-app/src/main/java/VASSAL/build/module/Map.java
  vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java
  vassal-app/src/main/java/VASSAL/tools/DebugControls.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: Ready for Review

#11925 11924 - Re-instate translation of Player Sides
  vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java
Labels: Ready for Review

#11931 11929 - Show translated module name and descriptions in Module Manager
  vassal-app/src/main/java/VASSAL/build/module/metadata/AbstractMetaData.java
  vassal-app/src/main/java/VASSAL/build/module/metadata/ModuleMetaData.java
Labels: Ready for Review

#11927 11502 Insert items into formatted strings from drop-down list into the correctly selected position
  vassal-app/src/main/java/VASSAL/configure/FormattedStringConfigurer.java
Labels: Ready to Merge

#11938 11520 IndexOutOfBoundsException trying to open a private note
  vassal-app/src/main/java/VASSAL/build/module/noteswindow/SecretNotesController.java
Labels: Ready to Merge
