Repository vassalengine/vassal, pull requests merged in 2023-02, with the labels that each got.

#11933 11933 - At-Start stacks were getting confused by blank boards
  vassal-app/src/main/java/VASSAL/build/module/map/SetupStack.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/Board.java
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Board.adoc
Labels: Ready to Merge

#11941 Since 3.6.7, French/Belgian AZERTY keyboards on Mac were experiencing problems with Ctrl / Alt keys on the number key row
  vassal-app/src/main/java/VASSAL/tools/swing/SwingUtils.java
Labels: Ready to Merge

#11957 11957 - Spaces in GKC reports made consistent with all other reports
  vassal-app/src/main/java/VASSAL/build/module/map/DeckGlobalKeyCommand.java
  vassal-app/src/main/java/VASSAL/counters/GlobalCommand.java
Labels: Ready for Review

#11988 11986 - Add missing Section size symbol to NATO markers
  vassal-app/src/main/java/VASSAL/build/module/gamepieceimage/Symbol.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: bug

#11935 11935 - Allow option for only first Mouseover-stack Viewer that generates a tooltip will be drawn
  vassal-app/src/main/java/VASSAL/build/module/Map.java
  vassal-app/src/main/java/VASSAL/build/module/map/CounterDetailViewer.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/Board.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/MouseOver.adoc
Labels: Ready to Merge

#11975 11884 - 'OldMat' properties now set correctly regardless of order of Mat Cargo and Send-to-Location (etc.) traits
  vassal-app/src/main/java/VASSAL/counters/Decorator.java
Labels: Ready to Merge

#11968 11961 - Clear up mark-when-moved problems for modules which still had a legacy value set
  vassal-app/src/main/java/VASSAL/build/module/GlobalOptions.java
  vassal-app/src/main/java/VASSAL/build/module/map/MovementReporter.java
  vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java
Labels: Ready for Review

#11980 11437 - Right-clicking on a Deck with no menu items no longer produces an exception
  vassal-app/src/main/java/VASSAL/build/module/map/MenuDisplayer.java
Labels: Ready to Merge

#11973 11880 - Triggers set to count 0 times don't spuriously execute 1 time.
  vassal-app/src/main/java/VASSAL/counters/TriggerAction.java
Labels: Ready for Review, Ready to Merge

#11978 11462 - Don't +1 inventory sum if property isn't even defined
  vassal-app/src/main/java/VASSAL/build/module/Inventory.java
Labels: Ready for Review

#11993 11993 - ActionButtons set to count 0 times don't spuriously execute 1 time.
  vassal-app/src/main/java/VASSAL/build/module/DoActionButton.java
Labels: Ready for Review

#12007 12007 - Update Apple Silicon terminology
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Preferences.adoc
Labels: Ready to Merge

#11970 11627 - ActionButtons with context menu flag no longer trigger context menu when a different ActionButton on same piece (that doesn't have the flag set) is clicked
  vassal-app/src/main/java/VASSAL/build/module/map/MenuDisplayer.java
  vassal-app/src/main/java/VASSAL/counters/ActionButton.java
Labels: Ready for Review, Ready to Merge

#11963 11963 - SendToLocation, Can Rotate, and MoveFixedDistance were all unlinking from deck/stack at wrong time, causing buggy behavior in some instances especially involving decks
  vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java
  vassal-app/src/main/java/VASSAL/build/module/map/deck/DeckSendKeyCommand.java
  vassal-app/src/main/java/VASSAL/counters/Deck.java
  vassal-app/src/main/java/VASSAL/counters/EditablePiece.java
  vassal-app/src/main/java/VASSAL/counters/FreeRotator.java
  vassal-app/src/main/java/VASSAL/counters/GamePiece.java
  vassal-app/src/main/java/VASSAL/counters/ReturnToDeck.java
  vassal-app/src/main/java/VASSAL/counters/SendToLocation.java
  vassal-app/src/main/java/VASSAL/counters/Translate.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/DeckSendKeyCommand.adoc
Labels: Ready for Review

#12004 11995 - ActionButtons with reports shouldn't display them if report is empty
  vassal-app/src/main/java/VASSAL/build/module/DoActionButton.java
Labels: Ready for Review

#11977 11693 - Fixed exception when copying folders containing Mouse-over Stack Viewers
  vassal-app/src/main/java/VASSAL/build/module/map/CounterDetailViewer.java
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
Labels: Ready for Review

#12018 11173 - Fixed crash in sorting a deck
  vassal-app/src/main/java/VASSAL/counters/Deck.java
Labels: Ready for Review

#12020 11897 - Ensure that deleted extensions don't crash the Module Manager
  vassal-app/src/main/java/VASSAL/launch/ModuleManagerWindow.java
Labels: Ready for Review

#12016 12016 - Fix a possible crash scenario in At-Start Stacks
  vassal-app/src/main/java/VASSAL/build/module/map/SetupStack.java
Labels: Ready for Review

#12022 11451 - Don't permit drag-and-drop within PlaceMarker, Replace with Other selection dialogs
  vassal-app/src/main/java/VASSAL/configure/ChooseComponentDialog.java
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
Labels: Ready for Review

#12023 10877 - Added a 'player joined' message when playing online
  vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: Ready for Review

#12024 9786 - Text Label traits will respond to GameRefresher (unless trait has a manually-change-label hotkey defined)
  vassal-app/src/main/java/VASSAL/build/GpIdChecker.java
  vassal-app/src/main/java/VASSAL/counters/Labeler.java
Labels: Ready for Review

#12019 11967 - When dragging piece out of face-down deck, use unrotated shape
  vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java
Labels: Ready to Merge

#12040 12037 - Fix concurrent modification exception in Decks
  vassal-app/src/main/java/VASSAL/counters/DeckManager.java
Labels: Ready for Review

#12044 12042 - Fix bug when copying Decks and At-Start Stacks to other maps
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
Labels: Ready for Review

#11178 11178 - Omit empty lines in non-blank property setting prompts
  vassal-app/src/main/java/VASSAL/build/module/GlobalOptions.java
  vassal-app/src/main/java/VASSAL/build/module/properties/EnumeratedPropertyPrompt.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/DynamicProperty.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/GlobalOptions.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/SetGlobalProperty.adoc
Labels: Ready for Review

#11937 11937 - SumMat and CountMat functions for Beanshell expressions
  vassal-app/src/main/java/VASSAL/configure/BeanShellFunctionMenu.java
  vassal-app/src/main/java/VASSAL/script/ExpressionInterpreter.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-app/src/main/resources/VASSAL/script/init_expression.bsh
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Expression.adoc
Labels: Ready for Review

#12003 12003 - OldDeckName now supported as a piece property
  vassal-app/src/main/java/VASSAL/counters/BasicPiece.java
  vassal-app/src/main/java/VASSAL/counters/Decorator.java
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/BasicPiece.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Properties.adoc
Labels: Ready for Review

#12046 Extracted duplicated code
  vassal-app/src/main/java/VASSAL/script/ExpressionInterpreter.java
Labels: Ready to Merge

#11918 11918 - Startup GKC that fires when player joins or changes sides
  vassal-app/src/main/java/VASSAL/build/module/GameState.java
  vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java
  vassal-app/src/main/java/VASSAL/build/module/StartupGlobalKeyCommand.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/GameModule.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Map.adoc
Labels: Ready for Review

#11983 11100 - Allow begin-logfile and end-logfile to have configurable hotkeys in Global Options
  vassal-app/src/main/java/VASSAL/build/module/BasicLogger.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: Ready for Review

#12032 12032 - Mark-When-Moved trait can be configured to only flag when piece changes LocationName or Mat. Similarly Map auto-report can be configured to ignore same-location movements.
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/build/module/Map.java
  vassal-app/src/main/java/VASSAL/build/module/map/MovementReporter.java
  vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java
  vassal-app/src/main/java/VASSAL/counters/Deck.java
  vassal-app/src/main/java/VASSAL/counters/EditablePiece.java
  vassal-app/src/main/java/VASSAL/counters/Footprint.java
  vassal-app/src/main/java/VASSAL/counters/FreeRotator.java
  vassal-app/src/main/java/VASSAL/counters/GamePiece.java
  vassal-app/src/main/java/VASSAL/counters/MovementMarkable.java
  vassal-app/src/main/java/VASSAL/counters/Properties.java
  vassal-app/src/main/java/VASSAL/counters/ReturnToDeck.java
  vassal-app/src/main/java/VASSAL/counters/SendToLocation.java
  vassal-app/src/main/java/VASSAL/counters/Translate.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Map.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/MarkMoved.adoc
Labels: Ready for Review

#11535 11530 - Add new StackPos and StackSize properties to Basic Piece.
  vassal-app/src/main/java/VASSAL/counters/BasicPiece.java
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/BasicPiece.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Properties.adoc
Labels: enhancement, Ready for Review

#12048 12048 - Fix bugs when deleting groups of decks/stacks from the editor
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
  vassal-app/src/main/java/VASSAL/configure/ExtensionTree.java
Labels: Ready for Review

#12034 11913 - Numeric global properties with increments other than 1 and -1 now wrap around correctly
  vassal-app/src/main/java/VASSAL/build/module/properties/IncrementProperty.java
Labels: Ready to Merge

#12049 Duplicating a prototype no longer disables that prototype until next module reload
  vassal-app/src/main/java/VASSAL/build/module/PrototypesContainer.java
Labels: Ready for Review

#11964 11964 - Mouse-over Stack Viewers can display an image of underlying terrain
  vassal-app/src/main/java/VASSAL/build/module/Map.java
  vassal-app/src/main/java/VASSAL/build/module/map/CounterDetailViewer.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/Board.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/HexGrid.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/MapGrid.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/RegionGrid.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/SquareGrid.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/ZonedGrid.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/Zone.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/MouseOver.adoc
Labels: Ready for Review

#11969 11969 - Border Outline trait. What?!?! Oh no it's a new trait! FLEE FOR THE HILLS, HAIR ON FIRE!!!
  vassal-app/src/main/java/VASSAL/build/module/BasicCommandEncoder.java
  vassal-app/src/main/java/VASSAL/counters/BorderOutline.java
  vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/BorderOutline.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/BorderOutline.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/BorderOutline2.png
Labels: Ready for Review

#12052 11249 - Enhanced recursion protection to catch self-referencing prototypes
  vassal-app/src/main/java/VASSAL/counters/UsePrototype.java
Labels: Ready for Review

#11987 10820 - Make Action Button available on all windows where other similar buttons (eg GKC, Multi-Action, etc) are available
  vassal-app/src/main/java/VASSAL/build/AbstractToolbarItem.java
  vassal-app/src/main/java/VASSAL/build/module/DoActionButton.java
  vassal-app/src/main/java/VASSAL/build/module/Map.java
  vassal-app/src/main/java/VASSAL/build/module/folder/MapSubFolder.java
Labels: Ready for Review

#12050 12041 - Rollover border color of 'no color' did not save to file, nor copy correctly
  vassal-app/src/main/java/VASSAL/configure/ColorConfigurer.java
Labels: Ready for Review

#12035 12035 - Mouse-over Stack Viewers allow configuring thickness of outer border, and more padding/stretching options
  vassal-app/src/main/java/VASSAL/build/module/map/CounterDetailViewer.java
  vassal-app/src/main/java/VASSAL/tools/image/LabelUtils.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-app/src/test/resources/clirr-ignored-differences.xml
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/MouseOver.adoc
Labels: Ready for Review

#11985 10821 - Symbolic Dice buttons how have full Action Button capabilities (sounds, hotkeys, etc.)
  vassal-app/src/main/java/VASSAL/build/module/DoActionButton.java
  vassal-app/src/main/java/VASSAL/build/module/SpecialDiceButton.java
  vassal-app/src/main/java/VASSAL/tools/LaunchButton.java
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/SpecialDiceButton.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/SpecialDiceButton.png
Labels: Ready for Review

#12059 Various PMD and Spotbugs fixes
  vassal-app/pom.xml
  vassal-app/src/main/java/VASSAL/build/module/map/MoveCameraButton.java
  vassal-app/src/main/java/VASSAL/build/module/map/deck/AbstractDeckKeyCommand.java
  vassal-app/src/main/java/VASSAL/build/module/map/deck/SortParameterConfigurer.java
  vassal-app/src/main/java/VASSAL/build/module/noteswindow/SecretNotesController.java
  vassal-app/src/main/java/VASSAL/build/module/turn/ListTurnLevel.java
  vassal-app/src/main/java/VASSAL/chat/node/NodeClient.java
  vassal-app/src/main/java/VASSAL/configure/Configurer.java
  vassal-app/src/main/java/VASSAL/configure/DynamicKeyCommandConfigurer.java
  vassal-app/src/main/java/VASSAL/counters/GlobalCommandTarget.java
  vassal-app/src/main/java/VASSAL/counters/Stack.java
  vassal-app/src/main/java/VASSAL/tools/NamedKeyManager.java
  vassal-app/src/main/java/VASSAL/tools/NamedKeyStroke.java
  vassal-app/src/main/java/VASSAL/tools/filechooser/FileFilter.java
  vassal-app/src/main/java/VASSAL/tools/image/ImageUtils.java
  vassal-app/src/main/java/VASSAL/tools/imageop/AbstractOpImpl.java
  vassal-app/src/main/java/VASSAL/tools/io/IOUtils.java
  vassal-app/src/test/resources/clirr-ignored-differences.xml
Labels: Ready to Merge

#12064 12063 - Fixed Deck save/load hotkeys being mixed up
  vassal-app/src/main/java/VASSAL/counters/Deck.java
Labels: Ready for Review

#11531 11523 Area of Effect improvements
  vassal-app/pom.xml
  vassal-app/src/main/java/VASSAL/counters/AreaOfEffect.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-app/src/test/java/VASSAL/counters/AreaOfEffectTest.java
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/AreaOfEffect.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Properties.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/AreaOfEffect.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/AreaOfEffect2.png
Labels: enhancement, Ready for Review

#11917 11917 - Create Non-Rectangular mask directly from SVG outline
  vassal-app/src/main/java/VASSAL/counters/NonRectangular.java
  vassal-app/src/main/java/VASSAL/tools/imageop/Op.java
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/NonRectangular.adoc
Labels: Ready to Merge
