Repository vassalengine/vassal, pull requests merged in 2023-10, with the labels that each got.

#12767 Update selectDotSavFile() description (vsav).
  vassal-app/src/main/java/VASSAL/tools/filechooser/FileChooser.java
Labels: documentation, Ready to Merge

#12783 12781 - Fix bad translation keys for Attachment, Deselect, Send To Location traits
  vassal-app/src/main/java/VASSAL/counters/Attachment.java
  vassal-app/src/main/java/VASSAL/counters/Deselect.java
  vassal-app/src/main/java/VASSAL/counters/SendToLocation.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: bug, documentation, Ready for Review

#12782 12770 Prevent NPE when escaping from GKC trait after adding 'Set Dynamic Properties' entries
  vassal-app/src/main/java/VASSAL/configure/ParameterListConfigurer.java
Labels: bug, Ready for Review, Testing Complete

#12791 12784 - Fix rendering of external Text Label images
  vassal-app/src/main/java/VASSAL/counters/Labeler.java
Labels: Ready for Review

#12788 12769 - Fix support for expressions in Sound Clip Configurer
  vassal-app/src/main/java/VASSAL/configure/AudioClipConfigurer.java
Labels: bug, Ready for Review, Testing Complete

#12780 Correctly adjust Player window title to reflect actions taken in Welcome Wizard
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/build/module/WizardSupport.java
Labels: bug, Ready to Merge

#12808 12808 - Horizontal scrolling now supports 2-finger-trackpad and mice with additional horizontal wheels
  vassal-app/src/main/java/VASSAL/tools/ScrollPane.java
Labels: Ready to Merge

#12828 12802 Prevent NPE in Named KeyStroke Configurer
  vassal-app/src/main/java/VASSAL/configure/NamedHotKeyConfigurer.java
Labels: bug, Ready for Review

#12829 12829 Set Piece Property Documentation clarification
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/SetPieceProperty.adoc
Labels: documentation, Ready for Review

#12827 12825 Allow Unique components to be copied; change Game Piece Layers to be non-mandatory.
  vassal-app/src/main/java/VASSAL/build/module/map/LayeredPieceCollection.java
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
Labels: bug, Ready for Review

#12826 12826 Fix bug where pieces sometimes teleport from deck back to different map in multiplayer (Ensure map recorded in pieces matches map in parent Stack/Deck)
  vassal-app/src/main/java/VASSAL/counters/BasicPiece.java
  vassal-app/src/main/java/VASSAL/counters/Stack.java
Labels: bug, Ready for Review, Ready to Merge

#12824 Ensure ColorManager and FontManager are created exactly once, before use
  vassal-app/src/main/java/VASSAL/build/module/gamepieceimage/ColorManager.java
  vassal-app/src/main/java/VASSAL/build/module/gamepieceimage/FontManager.java
  vassal-app/src/main/java/VASSAL/build/module/gamepieceimage/GamePieceImageDefinitions.java
Labels: Ready to Merge

#12831 12830 Prevent Load Continuation from auto-forwarding to end of log
  vassal-app/src/main/java/VASSAL/command/CommandFilter.java
Labels: bug, Ready for Review

#12842 12841 Ensure labels are correctly updated in Replace With Other trait
  vassal-app/src/main/java/VASSAL/counters/Replace.java
Labels: bug, Ready for Review

#12856 12846 Fix missing custom colors and font styles in Game Piece Layouts
  vassal-app/src/main/java/VASSAL/build/module/gamepieceimage/ColorManager.java
  vassal-app/src/main/java/VASSAL/build/module/gamepieceimage/FontManager.java
  vassal-app/src/main/java/VASSAL/build/module/gamepieceimage/GamePieceImageDefinitions.java
Labels: bug, Ready for Review

#12855 12852 Prevent SumZone from generating Bad Data Errors
  vassal-app/src/main/java/VASSAL/script/ExpressionInterpreter.java
Labels: bug, Ready for Review, Testing Complete

#12865 Documentation: Editor Search section - add a cross-link to main search details.
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Editor.adoc
Labels: documentation, Ready for Review

#12861 Number in-use traits in Piece Definer
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
  vassal-app/src/main/java/VASSAL/counters/Comment.java
  vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java
Labels: enhancement, Ready to Merge
