Repository vassalengine/vassal, pull requests merged in 2023-06, with the labels that each got.

#12340 Fix Inaccurate Hex Grid location reports
  vassal-app/src/main/java/VASSAL/build/module/Map.java
  vassal-app/src/main/java/VASSAL/build/module/map/CounterDetailViewer.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/Board.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/HexGrid.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/MapGrid.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/RegionGrid.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/SquareGrid.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/ZonedGrid.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/Zone.java
Labels: Ready for Review

#12358 12302 - Description field now properly appears with Startup GKC set to send Global Hotkey
  vassal-app/src/main/java/VASSAL/build/AbstractToolbarItem.java
  vassal-app/src/main/java/VASSAL/build/module/StartupGlobalKeyCommand.java
Labels: Ready for Review

#12361 12303 - Dynamic button text was resolved too soon
  vassal-app/src/main/java/VASSAL/tools/LaunchButton.java
Labels: Ready to Merge

#12362 12362 - Rollover component help button goes to MouseOver.html instead of Map.html
  vassal-app/src/main/java/VASSAL/build/module/map/CounterDetailViewer.java
Labels: Ready for Review

#12267 12267 - Optimize Ranged GKC's and remaining Location based fastmatch options
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/build/module/ChessClockControl.java
  vassal-app/src/main/java/VASSAL/build/module/GameState.java
  vassal-app/src/main/java/VASSAL/build/module/GlobalOptions.java
  vassal-app/src/main/java/VASSAL/build/module/Map.java
  vassal-app/src/main/java/VASSAL/build/module/index/IndexManager.java
  vassal-app/src/main/java/VASSAL/build/module/index/PiecePropertyIndex.java
  vassal-app/src/main/java/VASSAL/build/module/index/VassalMapPieceIndex.java
  vassal-app/src/main/java/VASSAL/build/module/index/VassalMapQuadTree.java
  vassal-app/src/main/java/VASSAL/build/module/map/MassKeyCommand.java
  vassal-app/src/main/java/VASSAL/build/module/map/StackMetrics.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/HexGrid.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/MapGrid.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/SquareGrid.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/ZonedGrid.java
  vassal-app/src/main/java/VASSAL/configure/AudioClipConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/BeanShellFunctionMenu.java
  vassal-app/src/main/java/VASSAL/configure/GlobalCommandTargetConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/PlayerIdFormattedExpressionConfigurer.java
  vassal-app/src/main/java/VASSAL/counters/Attachment.java
  vassal-app/src/main/java/VASSAL/counters/CounterGlobalKeyCommand.java
  vassal-app/src/main/java/VASSAL/counters/Decorator.java
  vassal-app/src/main/java/VASSAL/counters/Embellishment.java
  vassal-app/src/main/java/VASSAL/counters/FreeRotator.java
  vassal-app/src/main/java/VASSAL/counters/GlobalCommand.java
  vassal-app/src/main/java/VASSAL/counters/MultiLocationCommand.java
  vassal-app/src/main/java/VASSAL/counters/Obscurable.java
  vassal-app/src/main/java/VASSAL/counters/PlaceMarker.java
  vassal-app/src/main/java/VASSAL/counters/PlaySound.java
  vassal-app/src/main/java/VASSAL/counters/ReportState.java
  vassal-app/src/main/java/VASSAL/counters/RestrictCommands.java
  vassal-app/src/main/java/VASSAL/counters/SendToLocation.java
  vassal-app/src/main/java/VASSAL/counters/SetPieceProperty.java
  vassal-app/src/main/java/VASSAL/counters/Stack.java
  vassal-app/src/main/java/VASSAL/counters/TriggerAction.java
  vassal-app/src/main/java/VASSAL/script/ExpressionInterpreter.java
  vassal-app/src/main/java/VASSAL/tools/qtree/QFunc.java
  vassal-app/src/main/java/VASSAL/tools/qtree/QNode.java
  vassal-app/src/main/java/VASSAL/tools/qtree/QNodeType.java
  vassal-app/src/main/java/VASSAL/tools/qtree/QPoint.java
  vassal-app/src/main/java/VASSAL/tools/qtree/QuadTree.java
  vassal-app/src/main/java/VASSAL/tools/qtree/QuadTreeException.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-app/src/main/resources/VASSAL/script/init_expression.bsh
  vassal-app/src/test/java/VASSAL/build/module/index/PiecePropertyIndexTest.java
  vassal-app/src/test/java/VASSAL/tools/qtree/QuadTreeTest.java
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Attachment.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Expression.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/ExpressionSumCount.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/GlobalOptions.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/GlobalOptions.png
Labels: Ready for Review

#12327 12327 ! operator will always return false, not error if arg is invalid
  vassal-app/src/main/java/bsh/BSHUnaryExpression.java
Labels: Ready for Review

#12396 Add missing Global Option message
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: bug, Ready for Review

#12399 12363 - Initialise Global Option preferences that have no Tab name
  vassal-app/src/main/java/VASSAL/preferences/BasicPreference.java
Labels: bug, Ready for Review

#12404 12341 - Expression Documentation improvements
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Expression.adoc
Labels: documentation, Ready for Review

#12405 12401 - Allow Ctrl-V to be entered as a Key Command
  vassal-app/src/main/java/VASSAL/configure/NamedHotKeyConfigurer.java
Labels: bug, Ready for Review

#12407 12347 - Refresh Dynamic Properties correctly when they have no value.
  vassal-app/src/main/java/VASSAL/build/GpIdChecker.java
Labels: bug, Ready for Review

#12423 12261 - Report error if more than one grid added to a Zone
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/Zone.java
Labels: bug, Ready for Review
