Repository vassalengine/vassal, pull requests merged in 2023-12, with the labels that each got.

#12946 12912 Prevent Welcome Wizard loading multiple pre-defined setups concurrently
  vassal-app/src/main/java/VASSAL/build/module/WizardSupport.java
Labels: bug, Ready for Review

#12964 12912 Add wait cursor while loading setup
  vassal-app/src/main/java/VASSAL/build/module/WizardSupport.java
Labels: Ready for Review

#12886 Suppress piece palette boolean bad data errors
  vassal-app/src/main/java/VASSAL/configure/PropertyExpression.java
Labels: bug, Awaiting Testing/Feedback

#12798 Editor search revamp: more options and enhanced navigation
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Search.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/Search.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/search_advanced.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/search_basic.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/search_output.png
Labels: bug, enhancement, Review-Changes Requested

#12972 Editor search improvements - revisions to PR #12798
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: bug, enhancement

#12982 12981 Fixed IndexOutOfBoundsException in empty chat room
  vassal-app/src/main/java/VASSAL/chat/ui/RoomTreeRenderer.java
Labels: bug, Ready for Review
