Repository vassalengine/vassal, pull requests merged in 2023-05, with the labels that each got.

#12282 12282 - Fix javadoc build errors.
  vassal-app/src/main/java/VASSAL/Info.java
  vassal-app/src/main/java/VASSAL/build/BadDataReport.java
  vassal-app/src/main/java/VASSAL/build/module/GameRefresher.java
  vassal-app/src/main/java/VASSAL/build/module/GameState.java
  vassal-app/src/main/java/VASSAL/build/module/GlobalOptions.java
  vassal-app/src/main/java/VASSAL/build/module/Inventory.java
  vassal-app/src/main/java/VASSAL/build/module/Map.java
  vassal-app/src/main/java/VASSAL/build/module/SpecialDiceButton.java
  vassal-app/src/main/java/VASSAL/build/module/StartupGlobalKeyCommand.java
  vassal-app/src/main/java/VASSAL/build/module/documentation/BrowserHelpFile.java
  vassal-app/src/main/java/VASSAL/build/module/documentation/HelpFile.java
  vassal-app/src/main/java/VASSAL/build/module/map/DefaultPieceCollection.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/PolygonEditor.java
  vassal-app/src/main/java/VASSAL/build/widget/ListWidget.java
  vassal-app/src/main/java/VASSAL/chat/HttpRequestWrapper.java
  vassal-app/src/main/java/VASSAL/command/RemovePiece.java
  vassal-app/src/main/java/VASSAL/configure/Configurer.java
  vassal-app/src/main/java/VASSAL/counters/BasicName.java
  vassal-app/src/main/java/VASSAL/counters/Deck.java
  vassal-app/src/main/java/VASSAL/counters/GlobalCommand.java
  vassal-app/src/main/java/VASSAL/counters/GlobalCommandTarget.java
  vassal-app/src/main/java/VASSAL/counters/MultiLocationCommand.java
  vassal-app/src/main/java/VASSAL/counters/PieceFilter.java
  vassal-app/src/main/java/VASSAL/counters/PropertiesPieceFilter.java
  vassal-app/src/main/java/VASSAL/counters/SendToLocation.java
  vassal-app/src/main/java/VASSAL/counters/Stack.java
  vassal-app/src/main/java/VASSAL/property/AbstractPropertyContainer.java
  vassal-app/src/main/java/VASSAL/script/expression/AuditTrail.java
  vassal-app/src/main/java/VASSAL/script/expression/Expression.java
  vassal-app/src/main/java/VASSAL/tools/FormattedString.java
  vassal-app/src/main/java/VASSAL/tools/ProblemDialog.java
  vassal-app/src/main/java/VASSAL/tools/Sort.java
  vassal-app/src/main/java/VASSAL/tools/UniqueIdManager.java
  vassal-app/src/main/java/VASSAL/tools/icon/IconFamily.java
  vassal-app/src/main/java/VASSAL/tools/image/LabelUtils.java
  vassal-app/src/main/java/VASSAL/tools/imports/adc2/ADC2ModuleFileFilter.java
  vassal-app/src/main/java/VASSAL/tools/imports/adc2/MapBoard.java
  vassal-app/src/main/java/VASSAL/tools/imports/adc2/MapBoardFileFilter.java
  vassal-app/src/main/java/VASSAL/tools/imports/adc2/SymbolSetFileFilter.java
  vassal-app/src/main/java/VASSAL/tools/opcache/AbstractOpImpl.java
Labels: Ready to Merge

#12284 12284 - Add Danish localization
  vassal-app/src/main/java/VASSAL/i18n/Resources.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL_da.properties
Labels: Ready to Merge

#12279 12279 - Default heap raised to 1024MB
  vassal-app/src/main/java/VASSAL/build/module/GlobalOptions.java
  vassal-app/src/main/java/VASSAL/launch/AbstractLaunchAction.java
  vassal-app/src/main/java/VASSAL/launch/Launcher.java
Labels: Ready to Merge

#12315 Prevent NPE in MouseOverStackViewer trying to show top piece of empty stack
  vassal-app/src/main/java/VASSAL/build/module/map/CounterDetailViewer.java
  vassal-app/src/main/java/VASSAL/counters/Stack.java
Labels: bug, Ready for Review

#12304 12287 - Enable text field DnD
  vassal-app/src/main/java/VASSAL/configure/BeanShellExpressionConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/StringConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/TextConfigurer.java
Labels: Ready for Review
