Repository vassalengine/vassal, pull requests merged in 2023-09, with the labels that each got.

#12656 3.7 Documentation clarification
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/GlobalKeyCommands.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Marker.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Replace.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/SetPieceProperty.adoc
Labels: documentation, Ready for Review, Beta

#12663 12235 - HTML Help file starting page can now be an expression
  vassal-app/src/main/java/VASSAL/build/module/documentation/BrowserHelpFile.java
Labels: enhancement, Ready for Review

#12661 Translate side names in change sides message
  vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java
Labels: bug, Ready to Merge

#12659 Translate current side before checking for "next side".
  vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java
Labels: bug, Ready for Review

#12685 12582 - Corrected divide-by-zero problem for Zones defined by zero-point polygons
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/Zone.java
Labels: Ready for Review

#12655 12645 Respect localisation when filtering sides
  vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java
Labels: Ready to Merge

#12671 12670 - Prevent essential components being accidentally deleted
  vassal-app/src/main/java/VASSAL/build/Buildable.java
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/build/module/Chatter.java
  vassal-app/src/main/java/VASSAL/build/module/ChessClockControl.java
  vassal-app/src/main/java/VASSAL/build/module/Documentation.java
  vassal-app/src/main/java/VASSAL/build/module/GlobalOptions.java
  vassal-app/src/main/java/VASSAL/build/module/KeyNamer.java
  vassal-app/src/main/java/VASSAL/build/module/Map.java
  vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java
  vassal-app/src/main/java/VASSAL/build/module/PrototypesContainer.java
  vassal-app/src/main/java/VASSAL/build/module/gamepieceimage/ColorManager.java
  vassal-app/src/main/java/VASSAL/build/module/gamepieceimage/FontManager.java
  vassal-app/src/main/java/VASSAL/build/module/gamepieceimage/GamePieceImageDefinitions.java
  vassal-app/src/main/java/VASSAL/build/module/gamepieceimage/GamePieceLayoutsContainer.java
  vassal-app/src/main/java/VASSAL/build/module/map/BoardPicker.java
  vassal-app/src/main/java/VASSAL/build/module/map/ForwardToChatter.java
  vassal-app/src/main/java/VASSAL/build/module/map/ForwardToKeyBuffer.java
  vassal-app/src/main/java/VASSAL/build/module/map/HighlightLastMoved.java
  vassal-app/src/main/java/VASSAL/build/module/map/ImageSaver.java
  vassal-app/src/main/java/VASSAL/build/module/map/KeyBufferer.java
  vassal-app/src/main/java/VASSAL/build/module/map/LayeredPieceCollection.java
  vassal-app/src/main/java/VASSAL/build/module/map/MapCenterer.java
  vassal-app/src/main/java/VASSAL/build/module/map/MenuDisplayer.java
  vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java
  vassal-app/src/main/java/VASSAL/build/module/map/Scroller.java
  vassal-app/src/main/java/VASSAL/build/module/map/SelectionHighlighters.java
  vassal-app/src/main/java/VASSAL/build/module/map/StackExpander.java
  vassal-app/src/main/java/VASSAL/build/module/map/StackMetrics.java
  vassal-app/src/main/java/VASSAL/build/module/map/Zoomer.java
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/mapgrid/ZonedGridHighlighter.java
  vassal-app/src/main/java/VASSAL/build/module/properties/GlobalProperties.java
  vassal-app/src/main/java/VASSAL/build/module/properties/GlobalTranslatableMessages.java
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
  vassal-app/src/main/java/VASSAL/configure/RecursiveSingleChildInstance.java
  vassal-app/src/main/java/VASSAL/i18n/Language.java
  vassal-app/src/main/java/VASSAL/i18n/Localization.java
  vassal-app/src/main/java/VASSAL/script/ScriptContainer.java
Labels: enhancement, Ready for Review

#12692 12411 - Fixed NPE when updating ConfigureTree
  vassal-app/src/main/java/VASSAL/configure/ChooseComponentDialog.java
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
Labels: bug, Ready for Review

#12693 12307 Prevent NPE when Return to Deck of a deleted Deck.
  vassal-app/src/main/java/VASSAL/counters/ReturnToDeck.java
Labels: bug, Ready for Review

#12689 12688-Replace with other should not update text of unchangeable labels
  vassal-app/src/main/java/VASSAL/build/GpIdChecker.java
  vassal-app/src/main/java/VASSAL/counters/Labeler.java
  vassal-app/src/main/java/VASSAL/counters/Replace.java
Labels: bug, Ready for Review, Testing Complete

#12707 12706-keep the "retire" button disabled unless a game is running.
  vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java
Labels: bug, Ready for Review

#12720 12683 Prevent NPE on starting game in Main Room
  vassal-app/src/main/java/VASSAL/command/CommandFilter.java
Labels: bug, Ready for Review

#12700 12708 - Prevent ArrayIndexOutOfBoundsException if side translation count does not match module
  vassal-app/src/main/java/VASSAL/build/module/ChessClockControl.java
  vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: bug, Ready for Review

#12715 Enable help button for editor Search dialog
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
Labels: bug, Ready for Review

#12680 12679 Set Piece Property respects target property numeric constraints unless over-ridden.
  vassal-app/src/main/java/VASSAL/build/module/properties/EnumeratedPropertyPrompt.java
  vassal-app/src/main/java/VASSAL/counters/SetPieceProperty.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/SetPieceProperty.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/SetPieceProperty.png
Labels: bug, Ready for Review

#12716 Support regular expressions in Editor search
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Search.adoc
Labels: enhancement, Ready for Review

#12667 12542 - Mitigate race condition when selecting player sides
  vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL_da.properties
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL_de.properties
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL_es.properties
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL_fr.properties
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL_it.properties
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL_nl.properties
  vassal-app/src/test/resources/test-images/cc.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/GameModule.adoc
Labels: bug, Ready for Review, Testing Complete

#12694 12260-Pre & Post Refresh Hotkeys
  vassal-app/src/main/java/VASSAL/build/module/GameRefresher.java
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/GameRefresher.adoc
Labels: enhancement, Ready for Review

#12730 12729 Set Global Property to again record old GP value in oldValues for reporting
  vassal-app/src/main/java/VASSAL/counters/SetGlobalProperty.java
Labels: bug, Ready for Review
