Repository vassalengine/vassal, pull requests merged in 2023-04, with the labels that each got.

#12175 Fix Stretchy Images in chat
  vassal-app/src/main/java/VASSAL/tools/swing/DataArchiveHTMLEditorKit.java
Labels: Ready to Merge

#12199 FIX DECK TEST - HOW DID THIS EVER PASS FOR THE LAST THREE WEEKS?!?!
  vassal-app/src/test/java/VASSAL/counters/DeckTest.java
Labels: Ready for Review

#12177 12155 - Change-property buttons don't generate completely empty chat lines.
  vassal-app/src/main/java/VASSAL/build/module/properties/ChangePropertyButton.java
Labels: Ready for Review

#12172 12172 - Metadata now contains the 'extra' fields, and Module Manager display if numeric
  vassal-app/src/main/java/VASSAL/build/module/metadata/AbstractMetaData.java
  vassal-app/src/main/java/VASSAL/build/module/metadata/ModuleMetaData.java
  vassal-app/src/main/java/VASSAL/launch/ModuleManagerWindow.java
Labels: Ready for Review

#12204 Harden Embellishment a bit more
  vassal-app/src/main/java/VASSAL/counters/Embellishment.java
Labels: Ready for Review

#12210 12209 - Report correct trait in expression Audit Trail
  vassal-app/src/main/java/VASSAL/tools/FormattedString.java
Labels: bug, Ready for Review

#12205 12205 - Area of Effect trait was eating other traits' visibility info in some cases
  vassal-app/src/main/java/VASSAL/counters/AreaOfEffect.java
Labels: Ready to Merge

#12221 12221 - Fixed various missing searchability on various components
  vassal-app/src/main/java/VASSAL/build/module/DoActionButton.java
  vassal-app/src/main/java/VASSAL/build/module/Map.java
  vassal-app/src/main/java/VASSAL/build/module/map/MassKeyCommand.java
Labels: Ready for Review

#12213 Patch only-display-when configurer to use correct initial value
  vassal-app/src/main/java/VASSAL/counters/Embellishment.java
Labels: Ready for Review

#12220 Add BorderOutline's property names to the searchable target list
  vassal-app/src/main/java/VASSAL/counters/BorderOutline.java
Labels: Ready for Review

#12232 Notify user about mismatch between module and save version instead of throwing IllegalStateException
  vassal-app/src/main/java/VASSAL/build/module/GameState.java
  vassal-app/src/main/java/VASSAL/build/module/WizardSupport.java
  vassal-app/src/main/java/VASSAL/counters/Decorator.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: Ready for Review

#12247 12247 - Fix error dialog broken since 3.6.15 for exceptions with null messages
  vassal-app/src/main/java/VASSAL/tools/ErrorDialog.java
Labels: Ready for Review

#12237 12237 - Fix edge case Mat Refresh bugs
  vassal-app/src/main/java/VASSAL/build/module/GameRefresher.java
Labels: Ready to Merge

#12254 12215 - New MarkMoved commands shouldn't default to being displayed if no key commands entered
  vassal-app/src/main/java/VASSAL/counters/Decorator.java
  vassal-app/src/main/java/VASSAL/counters/MovementMarkable.java
Labels: Ready for Review

#12187 12187 - Improved Rectangular Grid range metric names and made them translatable.
  vassal-app/src/main/java/VASSAL/build/module/map/boardPicker/board/SquareGrid.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/RectangularGrid.adoc
Labels: Ready to Merge

#12176 12176 - Preference to not *display* Mark Moved status of pieces
  vassal-app/src/main/java/VASSAL/build/module/GlobalOptions.java
  vassal-app/src/main/java/VASSAL/counters/MovementMarkable.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Map.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Preferences.adoc
Labels: Ready for Review

#12184 12184 - Pivot can have two key commands/angles
  vassal-app/src/main/java/VASSAL/counters/Pivot.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Pivot.adoc
Labels: Ready for Review

#12191 12191 - Dunh Dunh DUNH! -- New "Attachment" trait
  vassal-app/src/main/java/VASSAL/build/module/AttachmentManager.java
  vassal-app/src/main/java/VASSAL/build/module/BasicCommandEncoder.java
  vassal-app/src/main/java/VASSAL/build/module/GameRefresher.java
  vassal-app/src/main/java/VASSAL/build/module/GameState.java
  vassal-app/src/main/java/VASSAL/build/module/map/DeckGlobalKeyCommand.java
  vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java
  vassal-app/src/main/java/VASSAL/command/RemovePiece.java
  vassal-app/src/main/java/VASSAL/configure/BeanShellFunctionMenu.java
  vassal-app/src/main/java/VASSAL/configure/GlobalCommandTargetConfigurer.java
  vassal-app/src/main/java/VASSAL/counters/Attachment.java
  vassal-app/src/main/java/VASSAL/counters/Clone.java
  vassal-app/src/main/java/VASSAL/counters/Decorator.java
  vassal-app/src/main/java/VASSAL/counters/Deselect.java
  vassal-app/src/main/java/VASSAL/counters/GlobalAttach.java
  vassal-app/src/main/java/VASSAL/counters/GlobalCommand.java
  vassal-app/src/main/java/VASSAL/counters/GlobalCommandTarget.java
  vassal-app/src/main/java/VASSAL/counters/GlobalCommandVisitor.java
  vassal-app/src/main/java/VASSAL/counters/GlobalDetach.java
  vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java
  vassal-app/src/main/java/VASSAL/counters/PlaceMarker.java
  vassal-app/src/main/java/VASSAL/counters/PropertyExporter.java
  vassal-app/src/main/java/VASSAL/counters/SetAttachmentProperty.java
  vassal-app/src/main/java/VASSAL/counters/SetGlobalProperty.java
  vassal-app/src/main/java/VASSAL/script/ExpressionInterpreter.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
  vassal-app/src/main/resources/VASSAL/script/init_expression.bsh
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Attachment.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/BasicPiece.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Expression.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/FastMatch.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/SetAttachmentProperty.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/Attachment.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/SetAttachmentProperty.png
Labels: Ready for Review

#12262 12208 - Remove hide-when-disabled feature for toolbar buttons that was breaking other things
  vassal-app/src/main/java/VASSAL/build/AbstractToolbarItem.java
Labels: Ready for Review

#11962 11932 - Support for setting Scenario Options
  vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java
  vassal-app/src/main/java/VASSAL/build/module/folder/GlobalPropertyFolder.java
  vassal-app/src/main/java/VASSAL/build/module/properties/AbstractScenarioProperty.java
  vassal-app/src/main/java/VASSAL/build/module/properties/BooleanScenarioProperty.java
  vassal-app/src/main/java/VASSAL/build/module/properties/GlobalProperties.java
  vassal-app/src/main/java/VASSAL/build/module/properties/ListScenarioProperty.java
  vassal-app/src/main/java/VASSAL/build/module/properties/NumberScenarioProperty.java
  vassal-app/src/main/java/VASSAL/build/module/properties/ScenarioOptions.java
  vassal-app/src/main/java/VASSAL/build/module/properties/ScenarioPropertiesOptionTab.java
  vassal-app/src/main/java/VASSAL/build/module/properties/StringScenarioProperty.java
  vassal-app/src/main/java/VASSAL/configure/BooleanConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/Configurer.java
  vassal-app/src/main/java/VASSAL/configure/NotNullConfigureName.java
  vassal-app/src/main/java/VASSAL/configure/StringConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/StringEnumConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/TranslatingStringEnumConfigurer.java
  vassal-app/src/main/java/VASSAL/configure/UniquelyNamedChildren.java
  vassal-app/src/main/java/VASSAL/counters/Labeler.java
  vassal-app/src/main/java/VASSAL/launch/PlayerWindow.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/GameModule.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/GlobalProperties.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/ScenarioProperties.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Tools.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/ScenarioOptions1.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/ScenarioOptions2.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/ScenarioOptions3.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/ScenarioOptions4.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/ScenarioOptions5.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/ScenarioOptions6.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/ScenarioOptions7.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/ScenarioOptions8.png
Labels: Ready for Review
