Repository vassalengine/vassal, pull requests merged in 2024-01, with the labels that each got.

#12973 12765 - Cancelling Return To Deck no longer causes crash
  vassal-app/src/main/java/VASSAL/counters/ReturnToDeck.java
Labels: bug, Ready for Review, Review-Changes Complete

#13011 Spelling correction on Global Options panel
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: Ready to Merge

#13023 13021 - Allow wizard to load setups from extensions
  vassal-app/src/main/java/VASSAL/build/module/WizardSupport.java
  vassal-app/src/main/java/VASSAL/tools/DataArchive.java
Labels: bug, Ready for Review, Testing Complete

#13005 13003 - Do not record Map Id's in saved Deck files so they will load on any Map
  vassal-app/src/main/java/VASSAL/counters/BasicPiece.java
Labels: bug, Ready for Review, Testing Complete

#12975 12894 Prevent crash if I/O Exception during CRC calculation
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/tools/CRCUtils.java
Labels: bug, Ready for Review

#13001 Fix poor performance of Piece Definer; remove spurious blank line from Mass Piece Loader
  vassal-app/src/main/java/VASSAL/counters/MassPieceLoader.java
  vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java
Labels: bug, Ready to Merge, Testing Complete

#12768 "Player joins as side" message now broadcast to all players
  vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java
Labels: bug, Ready to Merge

#13038 13037 - Make Zoom component a default component of all maps
  vassal-app/src/main/java/VASSAL/build/module/Map.java
Labels: enhancement, Ready for Review

#12976 Search: Add option to exclude module elements when editing extension
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Concepts.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Search.adoc
Labels: enhancement, Ready for Review

#13033 13022 - Prevent room non-owners starting new games
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/build/module/GameState.java
  vassal-app/src/main/java/VASSAL/build/module/PredefinedSetup.java
  vassal-app/src/main/java/VASSAL/chat/node/NodeClient.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: bug, Ready for Review, Testing Complete

#12971 12971 - Refresh visible portions of Maps after each UI, log or network action
  vassal-app/src/main/java/VASSAL/build/AbstractToolbarItem.java
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/build/module/BasicLogger.java
  vassal-app/src/main/java/VASSAL/build/module/ToolbarMenu.java
  vassal-app/src/main/java/VASSAL/build/module/map/MenuDisplayer.java
  vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java
  vassal-app/src/main/java/VASSAL/chat/CommandDecoder.java
  vassal-app/src/main/java/VASSAL/counters/ActionButton.java
Labels: bug, Ready for Review, Testing Complete

#13051 13049 - Compute correct _Degrees property for free rotations
  vassal-app/src/main/java/VASSAL/counters/FreeRotator.java
  vassal-app/src/test/java/VASSAL/counters/FreeRotatorTest.java
Labels: bug, Ready for Review, Review-Changes Requested

#13041 13040 - Show correct sides in Wizard after using Prev button
  vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java
  vassal-app/src/main/java/org/netbeans/api/wizard/displayer/WizardDisplayerImpl.java
Labels: bug, Ready for Review, Awaiting Testing/Feedback

#12898 PDS refresh improved controls with GHK feature
  .gitignore
  vassal-app/src/main/java/VASSAL/build/GpIdChecker.java
  vassal-app/src/main/java/VASSAL/build/module/GameRefresher.java
  vassal-app/src/main/java/VASSAL/build/module/PredefinedSetup.java
  vassal-app/src/main/java/VASSAL/configure/RefreshPredefinedSetupsDialog.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/GameRefresher.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/SavedGameUpdater.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/GameRefresher.png
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/images/SavedGameUpdater.png
Labels: bug, enhancement, Ready for Review

#13058 13057-Remove Unused Images does not find any images in use in an Extension
  vassal-app/src/main/java/VASSAL/build/module/ExtensionElement.java
Labels: bug, Ready for Review, Testing Complete

#12944 Add pieceCount to the map auto reporter
  vassal-app/src/main/java/VASSAL/build/module/Map.java
  vassal-app/src/main/java/VASSAL/build/module/map/MovementReporter.java
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Map.adoc
Labels: enhancement, Ready to Merge, 3.8

#12763 Added VassalGameFileName property
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Properties.adoc
Labels: enhancement, Ready for Review

#12938 Last file name property
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Properties.adoc
Labels: enhancement

#13089 13083 Show Piece Property menu on Expression Builder trait fields
  vassal-app/src/main/java/VASSAL/configure/Configurer.java
Labels: bug, Ready for Review, 3.7.8

#13090 13081 - Sleep function now sleeps correct number of milliseconds instead of 2000
  vassal-app/src/main/java/VASSAL/tools/swing/DialogCloser.java
Labels: bug, Ready for Review, 3.7.8

#13091 13087 - Fix 'Apply on Move' description in Deck Send Key Command
  vassal-app/src/main/java/VASSAL/build/module/map/deck/DeckSendKeyCommand.java
  vassal-app/src/main/resources/VASSAL/i18n/Editor.properties
Labels: bug, Ready for Review, 3.7.8

#13088 13073 - Attachments are lost after Undo
  vassal-app/src/main/java/VASSAL/build/module/AttachmentManager.java
Labels: bug, Ready for Review, 3.7.8

#13096 5813 Prevent Wizard crashing when using Prev/Next when no Password exists
  vassal-app/src/main/java/VASSAL/build/module/WizardSupport.java
Labels: bug, Ready for Review

#13101 Added Return to Deck to trait list in Reference Manual
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/GamePiece.adoc
Labels: 3.7.8

#13103 13102 - Current Location Fast Match was not recognizing pieces in same location but not same X, Y position
  vassal-app/src/main/java/VASSAL/counters/GlobalCommand.java
Labels: bug, Ready to Merge, 3.7.8

#13119 Upgrade bundled Java to 21.0.2
  bootstrap.sh
Labels: 3.7.8

#13093 13072 - Cargo now correctly follows Mat after Moved Fixed Distance
  vassal-app/src/main/java/VASSAL/counters/Translate.java
Labels: bug, Ready for Review, 3.7.8

#13104 13097 - CountMap() by Property gives Bad Data error
  vassal-app/src/main/java/VASSAL/script/ExpressionInterpreter.java
Labels: bug, Ready for Review, 3.7.8
