Repository vassalengine/vassal, pull requests merged in 2024-04, with the labels that each got.

#13174 13174 - Update Labels on remote maps after DragnDrop
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-app/src/main/java/VASSAL/build/module/map/MenuDisplayer.java
  vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java
  vassal-app/src/main/java/VASSAL/counters/KeyBuffer.java
Labels: bug, Ready for Review, Testing Complete, 3.7.10

#13273 13167 - Ensure side selection always appears in Wizard
  vassal-app/src/main/java/VASSAL/build/module/WizardSupport.java
Labels: bug, Ready for Review, Testing Complete, 3.7.10

#13272 13203 - Don't fail when replaying older log from module version with more Special Dice defined
  vassal-app/src/main/java/VASSAL/build/module/SpecialDiceButton.java
Labels: bug, Ready for Review, 3.7.10

#13275 13268 - Prevent crash after saving blank parameter list in GKC
  vassal-app/src/main/java/VASSAL/configure/ParameterListConfigurer.java
Labels: bug, Ready for Review, 3.7.10

#13287 13167 - Fix missing Player list after online game request
  vassal-app/src/main/java/VASSAL/build/module/WizardSupport.java
Labels: bug, Ready for Review, Testing Complete, 3.7.11

#13302 Upgrade Java to 21.0.3 (32-bit Windows), 22.0.1 (everything else)
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  bootstrap.sh
  mvnw
  mvnw.cmd
Labels: 3.7.11
