Repository vassalengine/vassal, pull requests merged in 2025-03, with the labels that each got.

#13872 13871 - Show layers in hidden pieces (to owner) correctly.
  vassal-app/src/main/java/VASSAL/counters/Hideable.java
Labels: bug, Ready for Review

#13875 No clicks, no drop!
  vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java
Labels: Ready to Merge

#13873 Suppress exceptions when establishing an MP3 audio stream
  vassal-app/src/main/java/VASSAL/tools/Mp3AudioClip.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: Ready for Review

#13882 Reset map on a piece that has lost its way
  vassal-app/src/main/java/VASSAL/build/module/map/MenuDisplayer.java
Labels: Ready for Review

#13876 Filter out null sender in sendToOthers(Command)
  vassal-app/src/main/java/VASSAL/chat/node/NodeClient.java
Labels: Ready for Review

#13863 Property ModuleGameFileName makes last opened game file name available to the current player
  vassal-app/src/main/java/VASSAL/build/GameModule.java
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Properties.adoc
Labels: enhancement, Ready for Review
