Repository vassalengine/vassal, pull requests merged in 2025-02, with the labels that each got.

#13833 Do not subject Continuation file to online restrictions.
  vassal-app/src/main/java/VASSAL/build/module/GameState.java
  vassal-app/src/main/resources/VASSAL/i18n/VASSAL.properties
Labels: enhancement, Ready for Review, Testing Complete

#13845 Sleep() performance improvement
  vassal-app/src/main/java/VASSAL/script/ExpressionInterpreter.java
  vassal-app/src/main/java/VASSAL/tools/swing/DialogCloser.java
Labels: bug, Ready for Review, Testing Complete

#13793 13791 - Prevent Checkbox Scenario Option switch description side option being forced on.
  vassal-app/src/main/java/VASSAL/build/module/properties/BooleanScenarioProperty.java
Labels: bug, Ready for Review

#13732 Bring section up to date with Module Library interface.
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Extension.adoc
Labels: documentation, Ready for Review

#13802 Fix offset placement for Place Marker & Replace with Other
  vassal-app/src/main/java/VASSAL/counters/PlaceMarker.java
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Marker.adoc
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/Replace.adoc
Labels: bug, Ready for Review

#13855 MacOS: Editor's shortcut for deleting components modified to Command+Delete on Mac, to prevent inadvertent use when a FileDialog is showing
  vassal-app/src/main/java/VASSAL/configure/ConfigureTree.java
Labels: bug, Ready to Merge

#13865 Fix a bad reference manual link
  vassal-app/src/main/java/VASSAL/build/module/StartupGlobalKeyCommand.java
  vassal-app/src/main/java/VASSAL/build/module/documentation/HelpFile.java
  vassal-doc/src/main/readme-referencemanual/ReferenceManual/GlobalKeyCommands.adoc
Labels: bug, documentation, Ready for Review

#13854 Workaround to height zoom issue
  vassal-app/src/main/java/VASSAL/build/module/map/Zoomer.java
Labels: bug, Ready for Review
